#!/usr/bin/bash
# inkVerb updater for Verber™, verb.ink

#set -e

# This "updates" the serfs and "upgrades" Verber
## serfs are updated every time. Upgrades only relate to Verber framework which has verber version numbers related to each patch/release.
## This contains many version patches for a Verber™ sequentially, one version at a time.
## This is run at the path: /opt/verb/${vUpdateRepo}/update

# To call a changelog for a specific version, use: `/usr/bin/echo "$vCLEANVerno"` Eg: `echo "$v08702"` for v0.87.02

# DEV NOTE: A directory, even empty, must exist in the same directory as this "update" file named by by each update version ie: 0.87.01/

# DEV NOTE: Larger versions must be at the bottom, smaller versions at the top, so "descending"

# DEV INSTRUCTIONS: Put all related files for each patch in a folder named by the version number, ie: 0.87.01/

# DEV NOTE: Serfs are automatically copied & updated from ${vUpdateRepo}/serfs to the Verber before any patches run, after the verno check.


minVerNo="0.90.00"
vUpdateRepo="verb-update"

# Include the config
if [ -d "/opt/verb/inst" ]; then
  ## This allows updates on a -premade or -made verber
  ServerUpdateOrg="inkverb"
  ServerUpdateRepo="verb-update"
else
  ## This is for updates on a setup verber
  . /opt/verb/conf/servernameip
fi

## Sample version updater:
#upgradePatchVerno=0.88.02
#if [ $(/usr/bin/echo ${upgradePatchVerno} | /usr/bin/sed -e "s/\.//g" | /usr/bin/sed -e "s/^0*//g") -gt $(/usr/bin/echo ${Verno} | /usr/bin/sed -e "s/\.//g" | /usr/bin/sed -e "s/^0*//g") ] ; then
#cleanPatchVerno=$(/usr/bin/echo $upgradePatchVerno | /usr/bin/sed -e "s/\.//g")
#PCLdoc="$(/usr/bin/cat <<UPCL
#Patch ${upgradePatchVerno} Changelog:
### Patch Notes Here...
#UPCL
#)"
#/usr/bin/echo "$PCLdoc"
## So we can call a specific version later if needed
#eval "v$cleanPatchVerno='$(/usr/bin/echo "$PCLdoc")'"
#
## Move to working directory of the patch
#if [ -d "/opt/verb/${vUpdateRepo}/${upgradePatchVerno}/" ]; then
#cd /opt/verb/${vUpdateRepo}/${upgradePatchVerno}/; fi
#
## Run the update scripts for this patch
#
###### SCRIPTS GO HERE #####
## NOTE: PWD is /opt/verb/${vUpdateRepo}/${upgradePatchVerno}/
#
## eg: /usr/bin/echo "I would update the serfs here, but that happens automatically."
#
#
#
###### END SCRIPTS #########
## Set and refresh the current version into inklists
#/usr/bin/sed -i "s/Verno=.*/Verno=\"${upgradePatchVerno}\"/g" /opt/verb/conf/inklists/verberverno
#. /opt/verb/conf/inklists/verberverno
#/usr/bin/echo "Verber upgraded to v${Verno}"
#else
#/usr/bin/echo "${upgradePatchVerno} patch not necessary..."
#fi
###############END#UPGRADE#PATCH#


# Pull scripts and settings from the original verb repo
/usr/bin/rm -rf /opt/verb/${vUpdateRepo}/u_tmp
/usr/bin/mkdir -p /opt/verb/${vUpdateRepo}/u_tmp
cd /opt/verb/${vUpdateRepo}/u_tmp || exit 6
/usr/bin/git clone https://github.com/${ServerUpdateOrg}/verb

# Update tools
/usr/bin/rm -rf /opt/verb/conf/lib
/usr/bin/cp -rf /opt/verb/${vUpdateRepo}/u_tmp/verb/conf/lib /opt/verb/conf/
/usr/bin/rm -rf /opt/verb/donjon/*.sh
/usr/bin/cp -f /opt/verb/${vUpdateRepo}/u_tmp/verb/donjon/*.sh /opt/verb/donjon/
/usr/bin/chmod 750 /opt/verb/donjon/*.sh
/usr/bin/rm -rf /opt/verb/donjon/repoupdate/*.updaterepo
/usr/bin/cp -f /opt/verb/${vUpdateRepo}/u_tmp/verb/donjon/repoupdate/*.updaterepo /opt/verb/donjon/repoupdate/
/usr/bin/echo "Tools updated."

# Update serfs
/usr/bin/rm -rf /opt/verb/serfs/*
/usr/bin/cp -f /opt/verb/${vUpdateRepo}/u_tmp/verb/serfs/* /opt/verb/serfs/
/usr/bin/chmod 750 /opt/verb/serfs/*
cd /opt/verb || exit 6
/usr/bin/rm -f README.md
/usr/bin/wget https://raw.githubusercontent.com/${ServerUpdateOrg}/verb/master/README.md
/usr/bin/echo "Serfs updated."

# Update ink
/usr/bin/rm -rf /opt/verb/ink/felt/*
/usr/bin/rm -rf /opt/verb/ink/help/*
/usr/bin/cp -f /opt/verb/${vUpdateRepo}/u_tmp/verb/ink/felt/* /opt/verb/ink/felt/
/usr/bin/cp -f /opt/verb/${vUpdateRepo}/u_tmp/verb/ink/help/* /opt/verb/ink/help/
/usr/bin/cp -f /opt/verb/${vUpdateRepo}/u_tmp/verb/ink/PHPcities /opt/verb/ink/
/usr/bin/cp -f /opt/verb/${vUpdateRepo}/u_tmp/verb/ink/actions.pb /opt/verb/ink/
/usr/bin/cp -f /opt/verb/${vUpdateRepo}/u_tmp/verb/ink/ink /opt/verb/ink/
/usr/bin/cp -f /opt/verb/${vUpdateRepo}/u_tmp/verb/ink/ink.functions /opt/verb/ink/
/usr/bin/cp -f /opt/verb/${vUpdateRepo}/u_tmp/verb/ink/ink.run /opt/verb/ink/
/usr/bin/chmod 750 /opt/verb/ink/felt/*
/usr/bin/echo "Ink actions updated."

# Update inklists
. /opt/verb/conf/serverinkget
if [ "${InkGet_List}" = "AUTO_UPDATE" ]; then
  /usr/bin/cp -f /opt/verb/${vUpdateRepo}/u_tmp/verb/conf/inklists/repoverlist /opt/verb/conf/inklists/
  /usr/bin/cp -f /opt/verb/${vUpdateRepo}/u_tmp/verb/conf/inklists/repolinks /opt/verb/conf/inklists/
  /usr/bin/cp -f /opt/verb/${vUpdateRepo}/u_tmp/verb/conf/inklists/inkmirrorlist /opt/verb/conf/inklists/
  if [ -z "$CustomNS" ] || [ "$CustomNS" != "true" ]; then
    /usr/bin/cp -f /opt/verb/${vUpdateRepo}/u_tmp/verb/conf/inklists/inkdnsnameservers /opt/verb/conf/inklists/
  fi
  /usr/bin/echo "Repo version list updated."
else
  /usr/bin/echo "Repo version list unchanged because this is a custom Verber."
fi

# If mirrorlist differs, install latest mirrors & update keyring, but not packages (stay lightweight)
if /usr/bin/diff -q /opt/verb/conf/inklists/inkmirrorlist /etc/pacman.d/mirrorlist | /usr/bin/grep -q "differ"; then
  /usr/bin/cp /opt/verb/conf/inklists/inkmirrorlist /etc/pacman.d/mirrorlist
  /usr/bin/pacman-key --init
  /usr/bin/pacman-key --populate archlinux
  /usr/bin/pacman -Sy archlinux-keyring --noconfirm
fi

# Check if Verb is setup for more updates...
if [ ! -f "/opt/verb/conf/servernameip" ] || [ ! -f "/opt/verb/conf/siteurilist" ] || [ ! -f "/opt/verb/conf/inklists/verberverno" ]; then
  /usr/bin/echo "Verb not installed; all done."
  /usr/bin/rm -rf /opt/verb/${vUpdateRepo}
  exit 0
fi

## Version Check ##
### The minimum version that can use this updater
## Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/inklists/verberverno
## Check minimal updateable version
if [ "$(/usr/bin/echo "${minVerNo}" | /usr/bin/sed -e "s/\.//g" | /usr/bin/sed -e "s/^0*//g")" -gt "$(/usr/bin/echo ${Verno} | /usr/bin/sed -e "s/\.//g" | /usr/bin/sed -e "s/^0*//g")" ] ; then
/usr/bin/echo "Current Verber™ version is ${Verno}, minimum ${minVerNo} to use this updater.
Run updateverberlegacy for older versions."
exit 0
fi

# Update MOTD
/usr/bin/cp -f /opt/verb/${vUpdateRepo}/u_tmp/verb/conf/lib/nib /opt/verb/conf/lib/
## Type-specific
if [ "${VerberType}" = "Verber" ]; then
  /usr/bin/cat /opt/verb/conf/lib/nib > /etc/motd
elif [ "${RinkConfigured}" = "true" ]; then
  /usr/bin/echo "Configured for Rink control." > /etc/motd
else
  /usr/bin/echo "" > /etc/motd
fi
/usr/bin/echo "${ServerIPv4} & ${ServerIPv6} running on ${ServerTimeCity} time." >> /etc/motd

# Update ClamAV
# /usr/bin/cp -f /opt/verb/${vUpdateRepo}/u_tmp/verb/conf/lib/vmail/clamav/clamav /opt/verb/donjon/
# /usr/bin/chmod 640 /opt/verb/donjon/clamav
# /usr/bin/echo "ClamAV definitions ready."
# . /opt/verb/conf/servermailpath
# if [ "${ServerMailStatus}" != "EMAIL_NOT_INSTALLED" ] && [ -d "/var/lib/clamav" ] && [ "${SASTATUS}" = "INSTALLED" ]; then
#   . /opt/verb/donjon/clamav
#   /usr/bin/mv -f /var/lib/clamav/main.cvd /var/lib/clamav/main.cvd.bak 2>/dev/null
#   /usr/bin/mv -f /var/lib/clamav/daily.cvd /var/lib/clamav/daily.cvd.bak 2>/dev/null
#   /usr/bin/mv -f /var/lib/clamav/bytecode.cvd /var/lib/clamav/bytecode.cvd.bak 2>/dev/null
#   /usr/bin/wget https://inkisaverb.com/${CLAMDL}/main.cvd -P /var/lib/clamav/
#   /usr/bin/wget https://inkisaverb.com/${CLAMDL}/daily.cvd -P /var/lib/clamav/
#   /usr/bin/wget https://inkisaverb.com/${CLAMDL}/bytecode.cvd -P /var/lib/clamav/
#   cd /var/lib/clamav/
#   if [ -f "/var/lib/clamav/main.cvd" ] && [ "$(/usr/bin/sha256sum main.cvd)" = "${SHAmain}" ]; then
#     /usr/bin/rm -f /var/lib/clamav/main.cvd.bak
#   else
#     /usr/bin/rm -f /var/lib/clamav/main.cvd
#     /usr/bin/mv -f /var/lib/clamav/main.cvd.bak /var/lib/clamav/main.cvd 2>/dev/null
#   fi
#   if [ -f "/var/lib/clamav/daily.cvd" ] && [ "$(/usr/bin/sha256sum daily.cvd)" = "${SHAdaily}" ]; then
#     /usr/bin/rm -f /var/lib/clamav/daily.cvd.bak
#   else
#     /usr/bin/rm -f /var/lib/clamav/daily.cvd
#     /usr/bin/mv -f /var/lib/clamav/daily.cvd.bak /var/lib/clamav/daily.cvd 2>/dev/null
#   fi
#   if [ -f "/var/lib/clamav/bytecode.cvd" ] && [ "$(/usr/bin/sha256sum bytecode.cvd)" = "${SHAbytecode}" ]; then
#     /usr/bin/rm -f /var/lib/clamav/bytecode.cvd.bak
#   else
#     /usr/bin/rm -f /var/lib/clamav/bytecode.cvd
#     /usr/bin/mv -f /var/lib/clamav/bytecode.cvd.bak /var/lib/clamav/bytecode.cvd 2>/dev/null
#   fi
#   cd $OLDPWD
#   /usr/bin/chown clamav:clamav /var/lib/clamav/main.cvd
#   /usr/bin/chown clamav:clamav /var/lib/clamav/daily.cvd
#   /usr/bin/chown clamav:clamav /var/lib/clamav/bytecode.cvd
#   /usr/bin/chmod 644 /var/lib/clamav/main.cvd
#   /usr/bin/chmod 644 /var/lib/clamav/daily.cvd
#   /usr/bin/chmod 644 /var/lib/clamav/bytecode.cvd
#   /usr/bin/echo "ClamAV definitions updated."
# fi

# Run version-by-version updates


#upgradePatchVerno=0.90.01
#if [ $(/usr/bin/echo ${upgradePatchVerno} | /usr/bin/sed -e "s/\.//g" | /usr/bin/sed -e "s/^0*//g") -gt $(/usr/bin/echo ${Verno} | /usr/bin/sed -e "s/\.//g" | /usr/bin/sed -e "s/^0*//g") ] ; then
#cleanPatchVerno="$(/usr/bin/echo $upgradePatchVerno | /usr/bin/sed -e "s/\.//g")"
#PCLdoc="$(/usr/bin/cat <<UPCL
#Patch ${upgradePatchVerno} Changelog:
### Patch Notes Here...
#UPCL
#)"
#/usr/bin/echo "$PCLdoc"
## So we can call a specific version later if needed
#eval "v$cleanPatchVerno='$(/usr/bin/echo "$PCLdoc")'"
#
## Move to working directory of the patch
#if [ -d "/opt/verb/${vUpdateRepo}/${upgradePatchVerno}/" ]; then
#cd /opt/verb/${vUpdateRepo}/${upgradePatchVerno}/; fi
#
## Run the update scripts for this patch
#
###### SCRIPTS GO HERE #####
## NOTE: PWD is /opt/verb/${vUpdateRepo}/${upgradePatchVerno}/
#
## eg: /usr/bin/echo "I would update the serfs here, but that happens automatically."
#
#
#
###### END SCRIPTS #########
## Set and refresh the current version into inklists
#/usr/bin/sed -i "s/Verno=.*/Verno=\"${upgradePatchVerno}\"/g" /opt/verb/conf/inklists/verberverno
#. /opt/verb/conf/inklists/verberverno
#/usr/bin/echo "Verber upgraded to v${Verno}"
#else
#/usr/bin/echo "${upgradePatchVerno} patch not necessary..."
#fi
###############END#UPGRADE#PATCH#


# Security check
/opt/verb/serfs/setsecure; wait

# Note version in the MOTD
/usr/bin/echo "inkVerb ${VerberType} ${ServerName} // v${Verno}" >> /etc/motd

# Ink is a verb. Ink.
/usr/bin/cat /opt/verb/conf/lib/nib

# Finish
/usr/bin/echo "Verber at v${Verno} framework from ${ServerUpdateRepo}."
/usr/bin/rm -rf /opt/verb/${vUpdateRepo}
