#!/bin/sh
#inkVerbSerf! verb.ink

# This activates the files....verb.vip folder so the web will provide an index
## Prerequisite: installvsftpd

# How to use:
## ./activatefiles [on/off]

# Eg:
## ./activatefiles on
## ./activatefiles off


# Include the config
. /opt/verb/conf/siteurilist

if [ "$1" = "on" ]
then
    rm -rf /srv/www/verb/vip.files
    /bin/ln -sfn /srv/www/vip/files /srv/www/verb/vip.files
    /bin/echo "files on."
exit 0
fi

if [ "$1" = "off" ]
then
    rm -f /srv/www/verb/vip.files
    cp -R /srv/www/html/0ne /srv/www/verb/vip.files
    /bin/echo "files off."
exit 0
fi

