#!/bin/sh
#inkVerbSerf! verb.ink

# This activates a domain to work with either the FTP-accessible domains/ directory or a vapp

# How to use:
## ./activatedomain [domain] [vappname.domain - if activating the vapp]

# Eg:
## ./activatedomain inkisaverb.com				# activate inkisaverb.com for the FTP domains/ directory
## ./activatedomain inkisaverb.com october.inkisaverb.com	# activate inkisaverb.com for the October vapp


DOMAIN=$1
VAPPNM=$2

if [ -n ${2} ]; then
then
    /bin/rm -rf /srv/www/html/${DOMAIN}
    /bin/ln -sfn /srv/www/vapps/${VAPPNM} /srv/www/html/${DOMAIN}
    /bin/echo "${VAPPNM} vapp active at ${DOMAIN}."
exit 0
fi

if [ -z ${2} ]; then
then
    /bin/rm -rf /srv/www/html/${DOMAIN}
    /bin/ln -sfn /srv/www/domains/${DOMAIN} /srv/www/html/
    /bin/echo "${DOMAIN} domain active."
exit 0
fi

