#!/bin/sh
#inkVerbSerf! verb.ink

# This activates the cgi....verb.vip folder so the web will provide an index

# How to use:
## ./activatecgi [on/off]

# Eg:
## ./activatecgi on
## ./activatecgi off


# Include the config
. /opt/verb/conf/siteurilist

if [ "$1" = "on" ]
then
    /bin/rm -rf /srv/www/html/vip.cgi
    /bin/ln -sfn /srv/www/vip/cgi /srv/www/html/vip.cgi
    /bin/echo "cgi on."
exit 0
fi

if [ "$1" = "off" ]
then
    /bin/rm -f /srv/www/html/vip.cgi
    /bin/cp -R /srv/www/html/0ne /srv/www/html/vip.cgi
    /bin/echo "cgi off."
exit 0
fi
