#!/bin/sh
#inkVerbSerf! verb.ink
# This adds a new domain, complete with OpenDKIM profiles and keys and inkCert Letsencrypt cli-ini entries and Apache/Nginx configs and folders in www/domains that link to www/html
## This also creates a folder for the domain in www/domains which an ftpvip can access
## This also creates an inkDNS zone file, complete with mail records

# How to use:
## ./adddomain [ newdomain.tld ]

usagenotes="This adds a new domain, complete with inkDKIM OpenDKIM profiles and keys, inkDNS DNS zone record, inkCert Letsencrypt cli-ini entries, and Apache/Nginx configs and folders in www/domains/ that link to www/html/"
usageformat="adddomain [ newdomain.tld ]"
usageexample="adddomain inkisaverb.com"
hierarchy=( primary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=( newdomainshell ensitenginx ensiteapache )
useconfigs=( inkcertstatus inkdnsconf sitemailpath sitenameip servertype )
if [ -n "infoINKonly" ] && [ "infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/adddomain.replace" ]; then . /opt/verb/mods/adddomain.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/adddomain.before" ]; then . /opt/verb/mods/adddomain.before; return 0; fi # Replaces this script


# Dependencies
if ! /bin/grep -q 'INKCERTINSTALLED="DONE"' /opt/verb/conf/inkcertstatus; then
  /usr/bin/echo "Install inkCert first, I quit."; exit 8
fi
if ! /bin/grep -q 'INKDNSSTAT="INSTALLED"' /opt/verb/conf/inkdnsconf; then
  /usr/bin/echo "Install inkDNS first, I quit."; exit 8
fi
if ! /bin/grep -q 'SITEMAILSTATUS="VMAIL_SERVER"' /opt/verb/conf/sitemailpath; then
  /usr/bin/echo "Install Postfix Vmail first, I quit."; exit 8
fi

# Include settings
. /opt/verb/conf/sitenameip
. /opt/verb/conf/servertype
. /opt/verb/conf/inkcertstatus

NEWDOMAIN=$1

# Check if it already exists
if [ ${SERVERTYPE} = "lemp" ]; then
  if [ -f /opt/verb/conf/webserver/nginx/sites-available/${NEWDOMAIN}.conf ]; then
    /opt/verb/serfs/ensitenginx -r ${NEWDOMAIN}
    /bin/echo "Site already exists, server restarted."
    exit 0
  fi
elif [ ${SERVERTYPE} = "lamp" ]; then
  if [ -f /opt/verb/conf/webserver/httpd/sites-available/${NEWDOMAIN}.conf ]; then
    /opt/verb/serfs/ensiteapache -r ${NEWDOMAIN}
    /bin/echo "Site already exists, server restarted."
    exit 0
  fi
elif [ ${SERVERTYPE} = "laemp" ]; then
  if [ -f /opt/verb/conf/webserver/nginx/sites-available/${NEWDOMAIN}.conf ]; then
    /opt/verb/serfs/ensitenginx -r ${NEWDOMAIN}
    SITEON=true
  fi
  if [ -f /opt/verb/conf/webserver/httpd/sites-available/${NEWDOMAIN}.conf ]; then
    /opt/verb/serfs/ensiteapache -r ${NEWDOMAIN}
    SITEON=true
  fi
  if [ "$SITEON" = "true" ]; then
    /bin/echo "Site already exists, server restarted."
    exit 0
  fi
fi

# Check the domain shell
if [ ! -f "/opt/verb/conf/inkcert/cli-ini/siteinkcert.${NEWDOMAIN}" ] || [ ! -f "/opt/verb/conf/inkcert/cli-ini/cli.${NEWDOMAIN}.ini" ]; then
  /bin/echo "The shell for ${NEWDOMAIN} does not exist yet. Creating it..."
  /opt/verb/serfs/newdomainshell ${NEWDOMAIN}; wait
fi

# Server config files
## Web directory
if [ ! -d /srv/www/domains/${NEWDOMAIN} ]; then
  /usr/bin/cp -rf /opt/verb/conf/site-files/newdomain.tld /srv/www/domains/${NEWDOMAIN}
fi
/bin/ln -sfn /srv/www/domains/${NEWDOMAIN} /srv/www/html/
/bin/chown -R www:www /srv/www/html/${NEWDOMAIN}
/bin/chown -R www:www /srv/www/domains/${NEWDOMAIN}
/bin/chmod -R 750 /srv/www/domains/${NEWDOMAIN}
## Copy
if [ ${SERVERTYPE} = "lemp" ]; then
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxdomain.tld.conf /opt/verb/conf/webserver/nginx/sites-available/${NEWDOMAIN}.conf
  /bin/sed -i "s/newdomain.tld/${NEWDOMAIN}/g" /opt/verb/conf/webserver/nginx/sites-available/${NEWDOMAIN}.conf
  ## Server
  /opt/verb/serfs/ensitenginx -r ${NEWDOMAIN}
elif [ ${SERVERTYPE} = "lamp" ]; then
  /usr/bin/cp /opt/verb/conf/site-files/conf/newdomain.tld.conf /opt/verb/conf/webserver/httpd/sites-available/${NEWDOMAIN}.conf
  /bin/sed -i "s/newdomain.tld/${NEWDOMAIN}/g" /opt/verb/conf/webserver/httpd/sites-available/${NEWDOMAIN}.conf
  ## Server
  /opt/verb/serfs/ensiteapache -r ${NEWDOMAIN}
elif [ ${SERVERTYPE} = "laemp" ]; then
  /usr/bin/cp /opt/verb/conf/site-files/conf/newdomain.tld.conf /opt/verb/conf/webserver/httpd/sites-available/${NEWDOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newrpnginxdomain.tld.conf /opt/verb/conf/webserver/nginx/sites-available/${NEWDOMAIN}.conf
  /bin/sed -i "s/newdomain.tld/${NEWDOMAIN}/g" /opt/verb/conf/webserver/httpd/sites-available/${NEWDOMAIN}.conf
  /bin/sed -i "s/newdomain.tld/${NEWDOMAIN}/g" /opt/verb/conf/webserver/nginx/sites-available/${NEWDOMAIN}.conf
  ## Server
  /opt/verb/serfs/ensiteapache -r ${NEWDOMAIN}
  /opt/verb/serfs/ensitenginx -r ${NEWDOMAIN}
fi

# Finish
/bin/echo "Great! With no error messages, you are ready to run inkCert for ${NEWDOMAIN}, unless you want to add subdomains."




if [ -e "/opt/verb/mods/adddomain.after" ]; then . /opt/verb/mods/adddomain.after; fi # Follows this script
