#!/bin/sh
#inkVerbSerf! verb.ink

# This adds a new domain, complete with OpenDKIM profiles and keys and inkCert and Apache configs
## This also creates a folder for the domain in www/domains which an ftpvip can access
## This also creates an inkDNS zone file, complete with mail records

# How to use:
## ./adddomain [newdomain.tld]


# Include settings
. /opt/verb/conf/sitenameip
. /opt/verb/conf/servertype
. /opt/verb/conf/inkcert/inkcertstatus

NEWDOMAIN=$1

# Check the domain shell
if [ ! -f "/opt/verb/conf/inkcert/cli-ini/siteinkcert.${NEWDOMAIN}" ] || [ ! -f "/opt/verb/conf/inkcert/cli-ini/cli.${NEWDOMAIN}.ini" ]; then
/bin/echo "The shell for ${NEWDOMAIN} does not exist yet. Creating it..."
/opt/verb/serfs/newdomainshell ${NEWDOMAIN}; wait
fi

# Check if it already exists
if [ -f /opt/verb/conf/webserver/httpd/sites-available/${NEWDOMAIN}.conf ]; then
 if [ -f /etc/httpd/sites-enabled/${NEWDOMAIN}.conf ]; then
 /bin/echo "That domain already exists."
 exit 0
 else
 /bin/echo "That site's config exists, but it doesn't seem to be active on Apache. Something's not right."
 exit 0
 fi
fi

# Server config files
## Web directory
if [ ! -d /srv/www/domains/${NEWDOMAIN} ]; then
  /usr/bin/cp -rf /opt/verb/conf/site-files/newdomain.tld /srv/www/domains/${NEWDOMAIN}
fi
/bin/ln -sfn /srv/www/domains/${NEWDOMAIN} /srv/www/html/
/bin/chown -R www:www /srv/www/html/${NEWDOMAIN}
/bin/chown -R www:www /srv/www/domains/${NEWDOMAIN}
/bin/chmod -R 750 /srv/www/domains/${NEWDOMAIN}
## Copy
if [ ${SERVERTYPE} = "lemp" ]; then
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxdomain.tld.conf /opt/verb/conf/webserver/nginx/sites-available/${NEWDOMAIN}.conf
  /bin/sed -i "s/newdomain.tld/${NEWDOMAIN}/g" /opt/verb/conf/webserver/nginx/sites-available/${NEWDOMAIN}.conf
  ## Server
  /opt/verb/serfs/ensitenginx -r ${NEWDOMAIN}
elif [ ${SERVERTYPE} = "lamp" ]; then
  /usr/bin/cp /opt/verb/conf/site-files/conf/newdomain.tld.conf /opt/verb/conf/webserver/httpd/sites-available/${NEWDOMAIN}.conf
  /bin/sed -i "s/newdomain.tld/${NEWDOMAIN}/g" /opt/verb/conf/webserver/httpd/sites-available/${NEWDOMAIN}.conf
  ## Server
  /opt/verb/serfs/ensiteapache -r ${NEWDOMAIN}
elif [ ${SERVERTYPE} = "laemp" ]; then
  /usr/bin/cp /opt/verb/conf/site-files/conf/newdomain.tld.conf /opt/verb/conf/webserver/httpd/sites-available/${NEWDOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newrpnginxdomain.tld.conf /opt/verb/conf/webserver/nginx/sites-available/${NEWDOMAIN}.conf
  /bin/sed -i "s/newdomain.tld/${NEWDOMAIN}/g" /opt/verb/conf/webserver/httpd/sites-available/${NEWDOMAIN}.conf
  /bin/sed -i "s/newdomain.tld/${NEWDOMAIN}/g" /opt/verb/conf/webserver/nginx/sites-available/${NEWDOMAIN}.conf
  ## Server
  /opt/verb/serfs/ensiteapache -r ${NEWDOMAIN}
  /opt/verb/serfs/ensitenginx -r ${NEWDOMAIN}
fi

# Finish
/bin/echo "Great! With no error messages, you are ready to run inkCert for ${NEWDOMAIN}, unless you want to add subdomains."
