#!/bin/sh
#inkVerbSerf! verb.ink

# This adds an existing domain to an existing ftpfiler's home ~/domains folder
## Prerequesite: newftpfiler used to create an ftpfiler

# How to use:
## ./adddomainfiler [olddomain.tld] [filer username]


OLDDOMAIN=$1
FILER=$2

/bin/ln -s /srv/www/domains/${OLDDOMAIN} /srv/vip/filers/${FILER}/_domains/${OLDDOMAIN}
