#!/bin/sh
#inkVerbSerf! verb.ink

# This backs up the entire email server, including folders and database

# How to use:
## ./backupvmail [securename 0-9, a-z, and A-Z only, optional] [-nl for no link, optional dep]

# Eg:
## ./backupvmail VERB-NAMESPACE
## ./backupvmail 583-NAME
## ./backupvmail aF9 -nl

if [ -z "$1" ]; then
SECNAME=$(/usr/bin/pwgen -s -1 12)
else
SECNAME=$1
fi

# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

# Export the database
cd /var/vmail
/opt/verb/serfs/mysqlex mail; wait

# Copy the config
/bin/cp /opt/verb/conf/sitemailpath /var/vmail/sitemailpath-old
/bin/cp /opt/verb/conf/sitemailpass /var/vmail/sitemailpass-old
/bin/cp /opt/verb/conf/sitenameip /var/vmail/sitenameip-old

# Zip the directory
cd /var
/opt/verb/serfs.txzin vmail
/bin/mv vmail.txz verb.vmail.${SECNAME}.vbak

# Move to web-download area
/bin/mv /var/verb.vmail.${SECNAME}.vbak /srv/www/vip/

if [ "$2" = "-nl" ]; then
/bin/echo "The email server data has been backed up to the 'vip' folder.
Note that the email server remains live."
exit 0
fi

/bin/ln -sfn /srv/www/vip/verb.vmail.${SECNAME}.vbak /srv/www/html/${SITESERVE}.serve/${SERVEDIR}/
/bin/chown -R www:www /srv/www/html/${SITESERVE}.serve/${SERVEDIR}/verb.vmail.${SECNAME}.vbak
/bin/echo "The email server data has been backed up to the 'vip' folder and can also be downloaded at

http://${SERVEPATH}/verb.vmail.${SECNAME}.vbak

Note that the email server remains live.
"
