#!/bin/sh
#inkVerbSerf! verb.ink

# This delets all backups from the server and their web-accessible symlinks

# How to use:
## ./backupdel


# Include the configs
. /opt/verb/conf/sitenameip

/bin/rm -f /srv/www/vip/*.vbak
/bin/rm -f /srv/www/html/${SITETLD}/*.vbak -f

