#!/bin/sh
#inkVerbSerf! verb.ink

# This restores a backup .vbak file from an inkVerb app backed-up using backup

# Prereq: Either the app must already be installed (and will be totally replaced)
## or you must create the symlink from the html/tld.app folder to the vapps/APP folder

# Instructions:
## The file can have any name, even if you changed it from the original, as long as it ends in .vbak
## The file MUST be uploaded to the "vip" folder, which can be done with vsftp installed and an ftpvip

# How to use:
## ./backuprestore [app namespace] [filename]

## This uses the same app namespace as installAPPNAME and vapp.APPNAME configs
## This does not work for ghost sites
## For WordPress installed to a domain, the namespace follows the format: wp-DOMAIN.TLD or wp-SUB.DOMAIN.TLD

# Eg:
## ./backuprestore orangehrm verb.orangehrm.sF52.vbak
## ./backuprestore wp.inkisaverb.com verb.wp.inkisaverb.com.ftU8.vbak


APPNAME=$1
FILENAME=$2

# Include the site config
. /opt/verb/conf/sitenameip

# Backup and remove whatever the original status is
if [ -e "/opt/verb/conf/vapp.${APPNAME}" ]; then
. /opt/verb/conf/vapp.${APPNAME}
cd /srv/www/vapps/${APPNAME}/
/opt/verb/serfs/mysqlvappout vapp.${APPNAME}; wait
/bin/mv /opt/verb/conf/vapp.${APPNAME} .
cd /srv/www/vapps/
/opt/verb/serfs/vtxzin ${APPNAME}
/bin/mv ${APPNAME}.vtxz verb.${APPNAME}.restore-originalbackedup.vbak
/bin/mv verb.${APPNAME}.restore-originalbackedup.vbak /srv/www/vip/
/opt/verb/serfs/mysqlkilldb ${APPDBASE}; wait
/opt/verb/serfs/mysqlkilluser ${APPDDBUSR}; wait
/bin/rm -rf ${APPNAME}
fi

# Unpack the file
cd /srv/www/vip
/bin/mv ${FILENAME} ${APPNAME}.vtxz
/opt/verb/serfs/vtxzout ${APPNAME}; wait
/bin/mv ${APPNAME} /srv/www/vapps/

# Set up the vapp symlink
/opt/verb/serfs/setvapplinkon ${APPNAME}

# Restore and include the app config
/bin/mv /srv/www/vapps/${APPNAME}/vapp.${APPNAME} /opt/verb/conf/
. /opt/verb/conf/vapp.${APPNAME}

# Create the SQL database
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
CREATE DATABASE ${APPDBASE} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON ${APPDBASE}.* TO '${APPDDBUSR}'@'localhost' IDENTIFIED BY '${APPDDBPAS}';
FLUSH PRIVILEGES;"

# Restore the database
cd /srv/www/vapps/${APPNAME}
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf ${APPDBASE} < ${APPDBASE}.sql; wait
/bin/rm -f ${APPDBASE}.sql
/bin/rm -f sitenameip*

# Own
/bin/chown -R www:www /srv/www/vapps/${APPNAME}

# Finish
/bin/echo "${APPNAME} has been restored and all its backup files removed from this server.

A backup of the previous ${APPNAME} on this server has been saved in the vip folder just in case.
"
