#!/bin/sh
#inkVerbSerf! verb.ink

# This restores a back up of the entire email server, including folders and database, that was made using backupvmail
## This only restores the users and their mailpfa as created in PostfixAdmin. Any PostfixAdmin setup will be overwritten.

# Prereq: Postfix and PostfixAdmin installed, but PostfixAdmin setup is irrelevant. postinstallpfa can be run before or after this.

# Instructions:
## The file can have any name, even if you changed it from the original, as long as it ends in .vbak
## The file MUST be uploaded to the "vip" folder, which can be done with vsftp installed and an ftpvip
## This can be run before or after running installemail or installpostfix, etc.

# How to use:
## ./backupvmailrestore [filename]

# Eg:
## ./backupvmailrestore verb.vmail.hR21.vbak


FILENAME=$1

# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/sitemailpath
. /opt/verb/conf/sitemailpass

# Set the to-be-replaced SITEMAILPASSAPG
tbrSMPAPG=${SITEMAILPASSAPG}

# Unpack the file
cd /srv/www/vip
/bin/mv ${FILENAME} vmail.vtxz
/opt/verb/serfs/vtxzout vmail

# Restore and include RC settings in the sitemail config
. /srv/www/vip/vmail/sitemailpass-old
/bin/sed -i "s/SITEMAILPASSAPG.*/SITEMAILPASSAPG=\"${SITEMAILPASSAPG}\"/g" /opt/verb/conf/sitemailpass
. /opt/verb/conf/sitemailpass

# Restore the database
/opt/verb/serfs/mysqlkilldb mail; wait
/opt/verb/serfs/mysqlkilluser mail; wait
/opt/verb/serfs/mysqlnewdb mail mail mailpass${SITEMAILPASSAPG}; wait
cd vmail
/opt/verb/serfs/mysqlin mail; wait
/bin/rm -f mail.sql
/bin/rm -f sitemailpass-old
/bin/rm -f sitemailpath-old
/bin/rm -f sitenameip-old
cd ..

# Move the vmail directory into place
/bin/cp -rf vmail /var/
/bin/chmod -R 770 /var/vmail
/bin/chown -R vmail:mail /var/vmail
/bin/rm -rf vmail

# Postfix & Dovecot password
/bin/sed -i "s/mailpass${tbrSMPAPG}/mailpass${SITEMAILPASSAPG}/" /etc/dovecot/dovecot-sql.conf.ext
/bin/sed -i "s/mailpass${tbrSMPAPG}/mailpass${SITEMAILPASSAPG}/" /etc/amavis/conf.d/50-user
/bin/sed -i "s/mailpass${tbrSMPAPG}/mailpass${SITEMAILPASSAPG}/" /etc/postfix/mysql_virtual_alias_domainaliases_maps.cf
/bin/sed -i "s/mailpass${tbrSMPAPG}/mailpass${SITEMAILPASSAPG}/" /etc/postfix/mysql_virtual_alias_maps.cf
/bin/sed -i "s/mailpass${tbrSMPAPG}/mailpass${SITEMAILPASSAPG}/" /etc/postfix/mysql_virtual_domains_maps.cf
/bin/sed -i "s/mailpass${tbrSMPAPG}/mailpass${SITEMAILPASSAPG}/" /etc/postfix/mysql_virtual_mailbox_domainaliases_maps.cf
/bin/sed -i "s/mailpass${tbrSMPAPG}/mailpass${SITEMAILPASSAPG}/" /etc/postfix/mysql_virtual_mailbox_maps.cf
/bin/sed -i "s/mailpass${tbrSMPAPG}/mailpass${SITEMAILPASSAPG}/" /etc/postfix/mysql_virtual_sender_login_maps.cf
## If PFA is already installed
if [ -e "/etc/httpd/sites-enabled/pfa.${emailTLDURI}.conf" ] && [ -f "/srv/www/email/postfixadmin/config.local.php" ] && [ "${SITEPFAPATH}" != "PFA_NOT_INSTALLED" ] && [ ${SITEPFAPATH} != "PFA_NOT_ALLOWED" ]; then
/bin/sed -i "s/mailpass${tbrSMPAPG}/mailpass${SITEMAILPASSAPG}/" /srv/www/email/postfixadmin/config.local.php; fi

# Restart stuff
/bin/systemctl restart postfix
/bin/systemctl restart dovecot
/bin/systemctl restart amavis

# Finish
/bin/echo "
The email server data has been restored from the backup and all its backup files removed from this server.
"

