#!/bin/sh
#inkVerbSerf! verb.ink

# This backs up the RoundCube app, including folders and database, in to one vbak file that can be downloaded
## This may not be important, but is available just in case.

# How to use:
## ./backuprcmail [securename 0-9, a-z, and A-Z only, optional] [-nl for no link, optional dep]

# Eg:
## ./backuprcmail 583
## ./backuprcmail aF9 -nl


if [ -z "$1" ]; then
SECNAME=$(/usr/bin/pwgen -s -1 12)
else
SECNAME=$1
fi

# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

# Export the database
cd /srv/www/email/roundcube
/opt/verb/serfs/mysqlex rcmail; wait

# Copy the config
/bin/cp /opt/verb/conf/sitemailpath /srv/www/email/roundcube/sitemailpath-old
/bin/cp /opt/verb/conf/sitemailpass /srv/www/email/roundcube/sitemailpass-old
/bin/cp /opt/verb/conf/sitenameip /srv/www/email/roundcube/sitenameip-old

# Pack the directory
cd /srv/www/email
/opt/verb/serfs/vtxzin roundcube
/bin/mv roundcube.vtxz verb.roundcube.${SECNAME}.vbak

# Move to web-download area
/bin/mv verb.roundcube.${SECNAME}.vbak /srv/www/vip/
/bin/chown -R www:www /srv/www/html/${nameURI}/verb.roundcube.${SECNAME}.vbak

if [ "$2" = "-nl" ]; then
/bin/echo "The email server data has been backed up to the 'vip' folder.
Note that the email server remains live."
exit 0
fi

/bin/ln -sfn /srv/www/vip/verb.roundcube.${SECNAME}.vbak /srv/www/html/${SITESERVE}.serve/${SERVEDIR}/
/bin/echo "The email server data has been backed up to the 'vip' folder and can also be downloaded at

http://${SERVEPATH}/verb.roundcube.${SECNAME}.vbak

Note that the email server remains live.
"
