#!/bin/bash
#inkVerbSerf! verb.ink

# This enables an httpd site by creating a symlink
## Use flag "-r" to reload automatically

# How to use:
## ./ensiteapache [domain.tld or subdomain.domain.tld] [domain2.tld] [domain3.tld]
## ./ensiteapache [domain.tld or subdomain.domain.tld]
## ./ensiteapache -r [domain.tld or subdomain.domain.tld] [domain2.tld] [domain3.tld]
## ./ensiteapache -r [domain.tld or subdomain.domain.tld]


# Run as a loop so multiple sites can be enabled in one command, just like a2ensite
for DOMAIN in $@; do
  if [ "${DOMAIN}" = "-r" ]; then
    continue
  elif [ -e "/etc/httpd/sites-available/${DOMAIN}.conf" ] && [ -f "/opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf" ]; then
    /usr/bin/ln -sfn /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf /opt/verb/conf/webserver/httpd/sites-enabled/${DOMAIN}.conf
  else
    /usr/bin/echo "${DOMAIN} Apache config does not exist at /etc/httpd/sites-available/${DOMAIN}.conf, cannot enable"
  fi
done

# Restart?
while getopts ":r" Var; do
  case $Var in
    r)
      /usr/bin/systemctl restart httpd; wait
    ;;
  esac
done
