#!/bin/sh
#inkVerbSerf! verb.ink

# This removes the httpsfix and restores the Apache file to it's original http and https state

# How to use:
## ./fixhttp [domain.tld or subdomain.domain.tld]


DOMAIN=$1

. /opt/verb/conf/servertype

if [ ${SERVERTYPE} = "lemp" ] || [ ${SERVERTYPE} = "laemp" ]; then
  # Nginx
	## Verify that it has been fixed
  if /bin/grep -q "##INKHTTPSFIX=fixed" /opt/verb/conf/webserver/nginx/sites-available/${DOMAIN}.conf; then

    # Replace it with the original file
    ## From the original file
    /bin/sed -i "/##inkHTTPremoved/r /opt/verb/conf/webserver/nginx/sites-available/${DOMAIN}.conf.verbhttpsfixed" /opt/verb/conf/webserver/nginx/sites-available/${DOMAIN}.conf

    ## Remove the old marker
    /bin/sed -i '/##inkHTTPremoved/d' /opt/verb/conf/webserver/nginx/sites-available/${DOMAIN}.conf

    ## Remove the old settings
    /bin/sed -i '/^##INKHTTPSFIX=fixed/,/^##verbFIXhttps/{/^##INKHTTPSFIX=fixed/!{/^##verbFIXhttps/!d}}' /opt/verb/conf/webserver/nginx/sites-available/${DOMAIN}.conf
    /bin/sed -i '/##INKHTTPSFIX=fixed/d' /opt/verb/conf/webserver/nginx/sites-available/${DOMAIN}.conf
    /bin/sed -i '/##verbFIXhttps/d' /opt/verb/conf/webserver/nginx/sites-available/${DOMAIN}.conf
    /bin/rm /opt/verb/conf/webserver/nginx/sites-available/${DOMAIN}.conf.verbhttpsfixed
    
    /bin/systemctl restart nginx; wait

  else
    /bin/echo "${DOMAIN} doesn't have the https fix. Doing nothing."
    exit 0
  fi

elif [ ${SERVERTYPE} = "lamp" ]; then
  # Verify that it has been fixed
  if /bin/grep -q "##INKHTTPSFIX=fixed" /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf; then

    # Replace it with the original file
    ## From the original file
    /bin/sed -i "/##inkHTTPremoved/r /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf.verbhttpsfixed" /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf

    ## Remove the old marker
    /bin/sed -i '/##inkHTTPremoved/d' /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf

    ## Remove the old settings
    /bin/sed -i '/^##INKHTTPSFIX=fixed/,/^##verbFIXhttps/{/^##INKHTTPSFIX=fixed/!{/^##verbFIXhttps/!d}}' /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf
    /bin/sed -i '/##INKHTTPSFIX=fixed/d' /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf
    /bin/sed -i '/##verbFIXhttps/d' /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf

    ## Put the original settings back
    /bin/cat /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf.verbhttpsfixed >> /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf
    /bin/rm /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf.verbhttpsfixed

    /bin/systemctl restart httpd; wait
  else
    /bin/echo "${DOMAIN} doesn't have the https fix. Doing nothing."
    exit 0
  fi

fi

# Finish
/bin/echo "${DOMAIN} now accepts http traffic."

# WordPress?
if [ -d "/srv/www/vapps/wp.${DOMAIN}" ]; then
  /bin/sed -i "/WP_SITEURL/d" /srv/www/vapps/wp.${DOMAIN}/wp-config.php
  /bin/sed -i "/WP_HOME/d" /srv/www/vapps/wp.${DOMAIN}/wp-config.php
  /bin/echo "define( 'WP_SITEURL', 'http://${DOMAIN}' );
  define( 'WP_HOME', 'http://${DOMAIN}' );" >> /srv/www/vapps/wp.${DOMAIN}/wp-config.php
fi
