#!/bin/sh
#inkVerbSerf! verb.ink

# This adds the www subdomain prefix to a domain's Apache config.
## This could be set to run automatically at some point, so may not be necessary independently.
## This may eventually be depreciated altogether
## This serf is kept in service because the www fix may not be necessary, especially on secure-based domains or subdomains and an untested possibility remains of breaking other serfs if it is not run deliberately. Besides, needing "www" in front of domains ended in the year 2000. It could also be fixed via a DNS cname.


# How to use:
## ./fixwww [domain.tld or subdomain.domain.tld]


DOMAIN=$1

. /opt/verb/conf/servertype

if [ ${SERVERTYPE} = "lemp" ] || [ ${SERVERTYPE} = "laemp" ]; then
	# Nginx
	## Check to see if "fixwww" has already been added
	if /bin/grep -q "##INKWWWFIX=fixed" /opt/verb/conf/webserver/nginx/sites-available/${DOMAIN}.conf; then
		/bin/systemctl restart nginx; wait
		/bin/echo "${DOMAIN} already has the www subdomain fix. The server was just reloaded so the site should work."
	else

		## Then add the config lines if it doesn't.
		/bin/echo "##INKWWWFIX=fixed
# Fixes www
server {
  server_name www.${DOMAIN};
  return 301 \$scheme://${DOMAIN}\$request_uri;
}
##verbFIXwww" >> /opt/verb/conf/webserver/nginx/sites-available/${DOMAIN}.conf
		/bin/systemctl restart nginx; wait

		/bin/echo "${DOMAIN} now has the www subdomain fix and is ready to go."
	fi

elif [ ${SERVERTYPE} = "lamp" ]; then
	# Check to see if "fixwww" has already been added
	if /bin/grep -q "##INKWWWFIX=fixed" /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf; then
		/usr/bin/systemctl restart httpd
		/bin/echo "${DOMAIN} already has the www subdomain fix. The server was just reloaded so the site should work."
	else

		## Then add the config lines if it doesn't.
		/bin/echo "##INKWWWFIX=fixed
# Fixes www
<VirtualHost *:80>
  ServerName www.${DOMAIN}
  Redirect permanent / http://${DOMAIN}/
</VirtualHost>
<IfModule mod_ssl.c>
  <VirtualHost _default_:443>
    ServerName www.${DOMAIN}
    Redirect permanent / https://${DOMAIN}/
  </VirtualHost>
</IfModule>
##verbFIXwww" >> /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf
		/usr/bin/systemctl restart httpd

		/bin/echo "${DOMAIN} now has the www subdomain fix and is ready to go."
	fi

fi
