#!/bin/sh
#inkVerbSerf! verb.ink

# This adds the necessary minimal .htaccess file to a web folder so none of its files can be read
## The "URI web path" is relative to the www/html/ folder; it must already exist.

# How to use:
## ./fixwebfilesclose [URI web path]

# Eg:
## ./fixwebfilesclose inkisaverb.com/myfiles
## ./fixwebfilesclose newfiles.ink.verb.vip


WEBPATH=$1

# If it doesn't exist
if [ ! -d "/srv/www/html/${WEBPATH}" ]; then
/bin/echo "This web folder does not exist. Doing nothing."
exit 8
fi

# If another .htaccess already exists
if [ -f "/srv/www/html/${WEBPATH}/.htaccess" ]; then
/bin/echo "A .htaccess file already exists for this web path. Over-write it and alter the course of the known universe?
Type \"yes\" to continue, anything else to quit."
read YESANSWER
 if [ "${YESANSWER}" != "yes" ]; then
/bin/echo "Quitting."
exit 3
 fi
fi

# Do it
/bin/echo "deny from all
" > /srv/www/html/${WEBPATH}/.htaccess

/bin/chown -R www:www /srv/www/html/${WEBPATH}

# Finish
/bin/echo "The contents of ${WEBPATH} are now available to the public!"

