#!/bin/sh
#inkVerbSerf! verb.ink

# This removes the www subdomain prefix from a domain's Apache config.
## This could be set to run automatically at some point, so may not be necessary independently.
## This may eventually be depreciated altogether
## This serf is kept in service because the www fix may not be necessary, especially on secure-based domains or subdomains and an untested possibility remains of breaking other serfs if it is not run deliberately. Besides, needing "www" in front of domains ended in the year 2000. It could also be fixed via a DNS cname.


# How to use:
## ./fixaliasrm [domain.tld or subdomain.domain.tld]


DOMAIN=$1

. /opt/verb/conf/servertype

if [ ${SERVERTYPE} = "lemp" ] || [ ${SERVERTYPE} = "laemp" ]; then
	# Nginx
	## Verify that the "fixwww" has been added
	if ! /bin/grep -q "##INKWWWFIX=fixed" /opt/verb/conf/webserver/nginx/sites-available/${DOMAIN}.conf; then
		/bin/echo "${DOMAIN} doesn't have the www subdomain fix. Nothing to do."
	fi

	## Remove the old settings
	/bin/sed -i '/^##INKWWWFIX=fixed/,/^##verbFIXwww/{/^##INKWWWFIX=fixed/!{/^##verbFIXwww/!d}}' /opt/verb/conf/webserver/nginx/sites-available/${DOMAIN}.conf
	/bin/sed -i '/##INKWWWFIX=fixed/d' /opt/verb/conf/webserver/nginx/sites-available/${DOMAIN}.conf
	/bin/sed -i '/##verbFIXwww/d' /opt/verb/conf/webserver/nginx/sites-available/${DOMAIN}.conf
	/bin/systemctl restart nginx; wait

	# Finish
	/bin/echo "${DOMAIN} the www subdomain fix has been removed."


elif [ ${SERVERTYPE} = "lamp" ]; then
	# Verify that the "fixwww" has been added
	if ! /bin/grep -q "##INKWWWFIX=fixed" /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf; then
		/bin/echo "${DOMAIN} doesn't have the www subdomain fix. Nothing to do."
	fi

	## Remove the old settings
	/bin/sed -i '/^##INKWWWFIX=fixed/,/^##verbFIXwww/{/^##INKWWWFIX=fixed/!{/^##verbFIXwww/!d}}' /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf
	/bin/sed -i '/##INKWWWFIX=fixed/d' /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf
	/bin/sed -i '/##verbFIXwww/d' /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf
	/usr/bin/apachectl graceful

	# Finish
	/bin/echo "${DOMAIN} the www subdomain fix has been removed."

fi
