#!/bin/sh
#inkVerbSerf! verb.ink

# This communicates with the inkCert server to send the csr and retrieve the cert package
## This runs a file remotely on the Inker server

# DEV: This is not finished

# How to use:
## ./inkcertgetrevoke-verber [domain]

# Eg:
## ./inkcertgetrevoke-verber poetryiscode.com
## ./inkcertgetrevoke-verber mysub.inkisaverb.com


DOMAIN=$1

# Verify that the domain is installed
if [ ! -f /opt/verb/conf/inkcert/cli-ini/siteinkcert.${DOMAIN} ]; then
/bin/echo "Sorry, Bucko. ${DOMAIN} is not even installed.

Why revoke a cert for a domain that isn't even installed here?
"; exit 0
fi

# Tell the inkCert Server to do its job
# inkNet run on Inker: verber-inkcertreceiverevoke

