#!/bin/bash
#inkVerbSerf! verb.ink

# This installs inkCert-Certbot Apache credentials for a given domain, including inkVerb namespace domains
## Prerequesite: inkcertreqcbwild
## This is intended as a subscript of inkcertdocbwild or to add certs to specific server configs as they are installed after the fact, such as in updates.

# How to use:
## ./inkcertaddcbwild [domain.tld or sub.domain.tld] [DOMAIN OF CERTIFICATE IF DIFFERENT, ie: domain.tld]

# Eg:
## ./inkcertaddcbwild NAME.verb.ink (will apply ONLY to NAME.verb.ink)
## ./inkcertaddcbwild blog.NAME.verb.ink (BAD NEWS: this won't work!! blog.NAME.verb.ink does not have a certificate by itself, use: 'inkcertaddallcbwild NAME.verb.ink')
## ./inkcertaddcbwild blog.NAME.verb.ink NAME.verb.ink
## ./inkcertaddcbwild inkisaverb.com (BAD NEWS: this won't work!! inkisaverb.com does not have a certificate by itself, use: 'inkcertaddallcbwild inkisaverb.com')
## ./inkcertaddcbwild poetryiscode.com inkisaverb.com (if the SSL cert for poetryiscode.com is included in the CN of the certificate for inkisaverb.com)


SITEDOMAIN=$1
CERTDOMAIN=$2

# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servertype
. /opt/verb/conf/inkcert/inkcertstatus

# Check inkCert installed
if [ "${INKCERTINSTALLED}" = "NOT_YET" ]; then
/bin/echo "inkCert not yet installed.

First run inkcertinstall
"
exit 0
fi

# Check variables
if [ -z ${1} ]; then
/bin/echo "You need to specify a domain. Read the instructions."; exit 0
fi

# Set variable for same certificate as domain (most all scenarios)
if [ -z ${2} ]; then
CERTDOMAIN=$1
fi

# Certs should already be in place from inkcertreqle
## This is a test for the inkcert directories:
if [ ! -d "/etc/inkcert/le/live/${CERTDOMAIN}" ]; then
/bin/echo "Something's wrong...

inkCert-Letsencrypt certs were not installed for ${SITEDOMAIN} because the ${CERTDOMAIN} certs don't exist. Common problems can include:
  - DNS records: ${SITEDOMAIN} should point to ${SITEIP}
  - DNS for ${SITEDOMAIN} may need a \"wildcard\" * CNAME record that points to ${SITEDOMAIN} as the \"hostname\"
  - DNS records can take about 4 hours to have effect
  - You need to first run: inkcertreqcbwild
  - Do not run inkcertreqle for individual subdomains with a shared certificate, but only for: ${blueURI}, inkisaverb.com, etc.
  - The verb/conf/inkcert/cli-ini/ file for ${CERTDOMAIN} may not contain the subdomain you are using.
"
exit 8
fi

if [ ${SERVERTYPE} = "lemp" ] || [ ${SERVERTYPE} = "laemp" ]; then
  ## Check Apache config status
  if /bin/grep -Fq "#INKVERB-INKCERT=INK_NO" /opt/verb/conf/webserver/nginx/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "Setting inkCert configs for ${SITEDOMAIN}..."
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_CB" /opt/verb/conf/webserver/nginx/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-CB: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_LE" /opt/verb/conf/webserver/nginx/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-LE: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_IC" /opt/verb/conf/webserver/nginx/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-IC: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=NA" /opt/verb/conf/webserver/nginx/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "inkCert certs do not apply here: ${SITEDOMAIN}. Moving on..."
   exit 0
  else
   /bin/echo "Something's really wrong with ${SITEDOMAIN}. No inkCert, no non-inkCert either. I quit here."
   exit 6
  fi

  ## Stop Nginx
  /bin/systemctl stop nginx; wait

  ## Comment the Snakeoil certs
  /bin/sed -i "s/ssl_certificate/#INKVERB-INKCERT-COMMENT-ssl_certificate/g" /opt/verb/conf/webserver/nginx/sites-available/${SITEDOMAIN}.conf

  ## Insert the inkCert certs
  /bin/sed -i "s/#INKVERB-INKCERT=INK_.*/#INKVERB-INKCERT=DONE_CBWILD\n  ssl_certificate\t\/etc\/inkcert\/le\/live\/${CERTDOMAIN}\/cert\.pem;\n  ssl_certificate_key\t\/etc\/inkcert\/le\/live\/${CERTDOMAIN}\/privkey\.pem;\n  #INKVERB-INKCERT-stop/" /opt/verb/conf/webserver/nginx/sites-available/${SITEDOMAIN}.conf

  ## inkCert status & exit
  if [ "${FIRSTINKCERTADDCBWILD}" = "NOT_YET" ]; then
    ### Config status: first inkCert done
    /bin/sed -i "s/FIRSTINKCERTADDCBWILD=\"NOT_YET\"/FIRSTINKCERTADDCBWILD=\"DONE\"/g" /opt/verb/conf/inkcert/inkcertstatus
    ### Create the cron job
    #### Add CB's auto updater to the cron
    /bin/echo '4 4 * * * root /opt/verb/donjon/inkcertcb-renew-all.sh' > /etc/cron.d/inkcertrenewcbcron
    /bin/chmod 0644 /etc/cron.d/inkcertrenewcbcron
  fi

  ## Create the inkCert log file
  /bin/mkdir -p /var/log/inkcert/
  /usr/bin/touch /var/log/inkcert/inkcertle.log

  ## Start Nginx
  /bin/systemctl start nginx; wait

elif [ ${SERVERTYPE} = "lamp" ]; then
  ## Check Apache config status
  if /bin/grep -Fq "#INKVERB-INKCERT=INK_NO" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "Setting inkCert configs for ${SITEDOMAIN}..."
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_CB" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-CB: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_LE" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-LE: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_IC" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-IC: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=NA" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "inkCert certs do not apply here: ${SITEDOMAIN}. Moving on..."
   exit 0
  else
   /bin/echo "Something's really wrong with ${SITEDOMAIN}. No inkCert, no non-inkCert either. I quit here."
   exit 6
  fi

  ## Stop Apache
  /bin/systemctl stop httpd; wait

  ## Comment the Snakeoil certs
  /bin/sed -i "s/SSLCertificateFile/#INKVERB-INKCERT-COMMENT-SSLCertificateFile/g" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf
  /bin/sed -i "s/SSLCertificateKeyFile/#INKVERB-INKCERT-COMMENT-SSLCertificateKeyFile/g" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf

  ## Insert the inkCert certs
  /bin/sed -i "s/#INKVERB-INKCERT=INK_.*/#INKVERB-INKCERT=DONE_CBWILD\n  SSLCertificateFile\t\/etc\/inkcert\/le\/live\/${CERTDOMAIN}\/cert\.pem\n  SSLCertificateKeyFile\t\/etc\/inkcert\/le\/live\/${CERTDOMAIN}\/privkey\.pem\n  SSLCertificateChainFile\t\/etc\/inkcert\/le\/live\/${CERTDOMAIN}\/chain\.pem\n  #INKVERB-INKCERT-stop/" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf

  ## inkCert status & exit
  if [ "${FIRSTINKCERTADDCBWILD}" = "NOT_YET" ]; then
    ### Config status: first inkCert done
    /bin/sed -i "s/FIRSTINKCERTADDCBWILD=\"NOT_YET\"/FIRSTINKCERTADDCBWILD=\"DONE\"/g" /opt/verb/conf/inkcert/inkcertstatus
    ### Create the cron job
    #### Add CB's auto updater to the cron
    /bin/echo '4 4 * * * root /opt/verb/donjon/inkcertcb-renew-all.sh' > /etc/cron.d/inkcertrenewcbcron
    /bin/chmod 0644 /etc/cron.d/inkcertrenewcbcron
  fi

  ## Create the inkCert log file
  /bin/mkdir -p /var/log/inkcert/
  /usr/bin/touch /var/log/inkcert/inkcertle.log

  ## Start Apache
  /bin/systemctl start httpd; wait

fi

# Finish
/bin/echo "
${SITEDOMAIN} certs installed.
"
