#!/bin/bash
#inkVerbSerf! verb.ink

# This batch runs inkCert-Letsencrypt request and install scripts for a given domain, including inkVerb namespace domains
## It also applies to all subdomains for that domain
## Prereqesite: inkcertinstall

# How to use:
## ./inkcertdole [domain.tld NO SUBDOMAINS]

#Eg:
## ./inkcertdole inkisaverb.com
## ./inkcertdole YOURNAME.verb.blue


DOMAIN=$1

# Check variables
if [ -z ${1} ]; then
/bin/echo "You need to specify a domain. Read the instructions."; exit 0
fi

# Request and get the certs
/opt/verb/serfs/inkcertreqle ${DOMAIN}; wait

# Install the certs
if /bin/grep -q "INKCERTED=NO" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${DOMAIN}; then
  if [ -e /etc/inkcert/le/live/${DOMAIN} ]; then
    /opt/verb/serfs/inkcertaddallle ${DOMAIN}; wait
  fi
fi

# Finish
/bin/echo "
Excellent!
Verify above exits - IMPORTANT NOTES: ... - Congratulations!

If so, then ${DOMAIN} and all subdomains are now live with inkCert Letsencrypt certificates.
"
