#!/bin/bash
#inkVerbSerf! verb.ink

# This installs inkCert Self-Cert Apache credentials for a given domain, including inkVerb namespace domains
## It applies only to one domain/subdomain at a time
## Prerequesite: inkcertreqsc
## This is intended as a subscript of inkcertdosc

# How to use:
## ./inkcertaddsc [domain.tld or sub.domain.tld]

#Eg:
## ./inkcertaddsc inkisaverb.com
## ./inkcertaddsc blog.inkisaverb.com
## ./inkcertaddsc YOURNAME.verb.one
## ./inkcertaddsc owncloud.YOURNAME.verb.blue
## ./inkcertaddsc smtp.YOURNAME.verb.email


SITEDOMAIN=$1
CERTDOMAIN=$2

# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servertype
. /opt/verb/conf/inkcert/inkcertstatus

# Check variables
if [ -z ${1} ]; then
/bin/echo "You need to specify a domain. Read the instructions."; exit 0
fi

# Set variable for same certificate as domain (most all scenarios)
if [ -z ${2} ]; then
CERTDOMAIN=$1
fi

# Certs should already be in place from inkcertreq
## This is a test for the inkcert directories:
if [ ! -d "/etc/inkcert/live/${CERTDOMAIN}" ]; then
/bin/echo "Something's wrong...

inkCert certs are not installed. Common problems can include:
  - DNS records: ${SITEDOMAIN} should point to ${SITEIP}
  - DNS for ${SITEDOMAIN} may need a \"wildcard\" * CNAME record that points to ${SITEDOMAIN} as the \"hostname\"
  - DNS records can take about 4 hours to have effect
  - You need to first run: inkcertreq
  - Do not run for individual subdomains with a shared certificate, but only for: ${blueURI}, ${rocksURI}, inkisaverb.com, etc.
"
exit 8
fi

if [ ${SERVERTYPE} = "lemp" ] || [ ${SERVERTYPE} = "laemp" ]; then
  ## Check Apache config status
  if /bin/grep -Fq "#INKVERB-INKCERT=INK_NO" /opt/verb/conf/webserver/nginx/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "Setting inkCert configs for ${SITEDOMAIN}..."
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_CB" /opt/verb/conf/webserver/nginx/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-CB: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_CBDIGOC" /opt/verb/conf/webserver/nginx/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-CBDIGOC: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_LE" /opt/verb/conf/webserver/nginx/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-LE: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_IC" /opt/verb/conf/webserver/nginx/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-IC: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=NA" /opt/verb/conf/webserver/nginx/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "inkCert certs do not apply here: ${SITEDOMAIN}. Moving on..."
   exit 0
  else
   /bin/echo "Something's really wrong with ${SITEDOMAIN}. No inkCert, no non-inkCert either. I quit here."
   exit 6
  fi

  ## Stop Nginx
  /bin/systemctl stop nginx; wait

  ## Comment the Snakeoil certs
  /bin/sed -i "s/ssl_certificate/#INKVERB-INKCERT-COMMENT-ssl_certificate/g" /opt/verb/conf/webserver/nginx/sites-available/${SITEDOMAIN}.conf

  ## Insert the inkCert certs
  /bin/sed -i "s/#INKVERB-INKCERT=INK_.*/#INKVERB-INKCERT=DONE_SC\n  ssl_certificate\t\/etc\/inkcert\/sc\/live\/${CERTDOMAIN}\/cert\.pem;\n  ssl_certificate_key\t\/etc\/inkcert\/sc\/live\/${CERTDOMAIN}\/key\.pem;\n\n  #INKVERB-INKCERT-stop/" /opt/verb/conf/webserver/nginx/sites-available/${SITEDOMAIN}.conf

  ## Create the inkCert-DOMAIN config file
  /bin/echo "INKCERTED=DONE_SC" > /opt/verb/conf/inkcert/cli-ini/siteinkcert.${SITEDOMAIN}

  ## inkCert status & exit
  if [ "${FIRSTINKCERTADD}" = "NOT_YET" ]; then
    ### Config status: first inkCert done
    /bin/sed -i "s/FIRSTINKCERTADD=\"NOT_YET\"/FIRSTINKCERTADD=\"DONE\"/g" /opt/verb/conf/inkcert/inkcertstatus
    ### Create the cron job
    #### Add inkCertLE's auto updater to the cron
    /bin/echo '3 3 * * * root /opt/verb/donjon/inkcert-renew-allsc.sh' > /etc/cron.d/inkcertrenewcronsc
    /bin/chmod 0644 /etc/cron.d/inkcertrenewcronsc
  fi

  ## Create the inkCert log file
  /bin/mkdir -p /var/log/inkcert/
  /usr/bin/touch /var/log/inkcert/inkcertle.log

  ## Start Nginx
  /bin/systemctl start nginx; wait

elif [ ${SERVERTYPE} = "lamp" ]; then
  ## Check Apache config status
  if /bin/grep -Fq "#INKVERB-INKCERT=INK_NO" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "Setting inkCert configs for ${SITEDOMAIN}..."
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_CB" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-CB: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_CBDIGOC" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-CBDIGOC: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_LE" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-LE: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_IC" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-IC: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=NA" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf ; then
   /bin/echo "inkCert certs do not apply here: ${SITEDOMAIN}. Moving on..."
   exit 0
  else
   /bin/echo "Something's really wrong with ${SITEDOMAIN}. No inkCert, no non-inkCert either. I quit here."
   exit 6
  fi

  ## Stop Apache
  /usr/bin/apachectl graceful-stop; wait
  /bin/systemctl stop httpd; wait

  ## Comment the Snakeoil certs
  /bin/sed -i "s/SSLCertificateFile/#INKVERB-INKCERT-COMMENT-SSLCertificateFile/g" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf
  /bin/sed -i "s/SSLCertificateKeyFile/#INKVERB-INKCERT-COMMENT-SSLCertificateKeyFile/g" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf

  ## Insert the inkCert certs
  /bin/sed -i "s/#INKVERB-INKCERT=INK_.*/#INKVERB-INKCERT=DONE_SC\n  SSLCertificateFile\t\/etc\/inkcert\/sc\/live\/${CERTDOMAIN}\/cert\.pem\n  SSLCertificateKeyFile\t\/etc\/inkcert\/sc\/live\/${CERTDOMAIN}\/key\.pem\n  SSLCertificateChainFile\t\/etc\/inkcert\/sc\/live\/${CERTDOMAIN}\/chain\.cert\.pem\n  #INKVERB-INKCERT-stop/" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf

  ## Create the inkCert-DOMAIN config file
  /bin/echo "INKCERTED=DONE_SC" > /opt/verb/conf/inkcert/cli-ini/siteinkcert.${SITEDOMAIN}

  ## inkCert status & exit
  if [ "${FIRSTINKCERTADD}" = "NOT_YET" ]; then
    ### Config status: first inkCert done
    /bin/sed -i "s/FIRSTINKCERTADD=\"NOT_YET\"/FIRSTINKCERTADD=\"DONE\"/g" /opt/verb/conf/inkcert/inkcertstatus
    ### Create the cron job
    #### Add inkCertLE's auto updater to the cron
    /bin/echo '3 3 * * * root /opt/verb/donjon/inkcert-renew-allsc.sh' > /etc/cron.d/inkcertrenewcronsc
    /bin/chmod 0644 /etc/cron.d/inkcertrenewcronsc
  fi

  ## Create the inkCert log file
  /bin/mkdir -p /var/log/inkcert/
  /usr/bin/touch /var/log/inkcert/inkcertle.log

  ## Start Apache
  /bin/systemctl start httpd; wait

fi

# Finish
/bin/echo "
${SITEDOMAIN} certs installed.
"
