#!/bin/sh
#inkVerbSerf! verb.ink

# This tells the Verber that the cert is ready, should be or has been downloaded, and to install it
## This is run remotely by the Inker server

# Inker remote with special permissions
## Make this file able to work, run as root who owns the file:
# /bin/chown root inkcertgetcertdone-inker
# /bin/chmod u+s inkcertgetcertdone-inker


# How to use:
## ./inkcertgetcertdone-inker [domain]

# Eg:
## ./inkcertgetcertdone-inker poetryiscode.com
## ./inkcertgetcertdone-inker mysub.inkisaverb.com


DOMAIN=$1

# Verify the file


# Run the cert install serf


