#!/bin/sh
#inkVerbSerf! verb.ink

# This runs the auto updater for LE inkCert.
## The script is already written, this merely runs it via Serf

# How to use:
## ./inkcertupdatele-all


/opt/verb/conf/inkcert/inkcertle-renew-all.sh

