#!/bin/bash
#inkVerbSerf! verb.ink

# This runs inkcertaddcb for a domain and all of its subdomains
## Prerequesite: inkcertreqcbdigoc

# NOTE: This is intended to be run by inkcertdocbdigoc, but can be run separately, such as for updates
# NOTE: For the first run, if your domain and subdomains have the same certificate then run this only for the main domain

# How to use:
## ./inkcertaddallcbdigoc [domain.tld or sub.domain.tld] [DOMAIN OF CERTIFICATE IF DIFFERENT, ie: domain.tld]

# Eg:
## ./inkcertaddallcbdigoc NAME.verb.ink (will apply to all subdomains of NAME.verb.ink)
## ./inkcertaddallcbdigoc inkisaverb.com (will apply to all subdomains of inkisaverb.com)
## ./inkcertaddallcbdigoc poetryiscode.com inkisaverb.com (if the SSL cert for poetryiscode.com is included in the CN of the certificate for inkisaverb.com)


SITEDOMAIN=$1
CERTDOMAIN=$2

# Check inkCert installed
if [ "${INKCERTINSTALLED}" = "NOT_YET" ]; then
/bin/echo "inkCert not yet installed.

First run inkcertinstall
"
exit 0
fi

# Check variables
if [ -z ${1} ]; then
/bin/echo "You need to specify a domain. Read the instructions."; exit 0
fi

# Verify that Certbot DigitalOcean secrets are setup
if [ ! -f "/opt/verb/.certbotsecrets/inkcertcbdigoc.ini" ]; then
  /bin/echo "Sorry, DigitalOcean Certbot secrets not installed yet. Doing nothing."
  exit 0
fi

# Set variable for same certificate as domain (most all scenarios)
if [ -z ${2} ]; then
CERTDOMAIN=$1
fi

# For the main domain first
/opt/verb/serfs/inkcertaddcbdigoc ${SITEDOMAIN}
wait

# For any/all sub-domains
cd /opt/verb/conf/webserver/httpd/sites-available
## Get the name of each subdomain .conf file available
find . -name "*.${SITEDOMAIN}.conf"|while read findsitesubdomain; do
## Strip the .conf extension
 sitesubdomain=$(basename ${findsitesubdomain} .conf)
## Run inkCertAddLE per site config
 /opt/verb/serfs/inkcertaddcbdigoc ${sitesubdomain} ${CERTDOMAIN}
wait
done

# Finish
/bin/echo "
Done. ${CERTDOMAIN} certs installed for ${SITEDOMAIN}.
"
