#!/bin/bash
#inkVerbSerf! verb.ink

# This removes all inkCert files entirely for inkCert-LE and inkCert Proper

# How to use:
## ./inkcertkilldomain [domain.tld]


KILLDOMAIN=$1

# Remove inkCert configs
/bin/rm -f /opt/verb/conf/inkcert/cli-ini/cli.${KILLDOMSHELL}.ini
/bin/rm -f /opt/verb/conf/inkcert/cli-ini/siteinkcert.${KILLDOMSHELL}
/bin/rm -f /etc/inkcert/cli.${KILLDOMAIN}.ini
/bin/rm -rf /etc/inkcert/le/live/${KILLDOMAIN}
/bin/rm -rf /etc/inkcert/live/${KILLDOMAIN}

