#!/bin/sh
#inkVerbSerf! verb.ink

# This script revokes the inkCert-Certbot certs for a specified domain
## It also applies to all subdomains for that domain
## Prerequesite: inkcertdocbdigoc (or both subscripts thereof: inkcertreqcbdigoc, inkcertaddcbdigoc)
## This is intended as a subscript of inkcertundocbdigoc

# How to use:
## ./inkcertrevokecbdigoc [domain.tld NO SUBDOMAINS]

#Eg:
## ./inkcertrevokecbdigoc inkisaverb.com
## ./inkcertrevokecbdigoc YOURNAME.verb.blue


DOMAIN=$1

# Include and check the inkCert domain config
## Verify that the domain is installed
if [ ! -f /opt/verb/conf/inkcert/cli-ini/siteinkcert.${DOMAIN} ]; then
/bin/echo "Sorry, Bucko. ${DOMAIN} is not even installed.

Why revoke a cert for a domain that isn't even installed here?
"; exit 0
fi
## Domain cert status
. /opt/verb/conf/inkcert/cli-ini/siteinkcert.${DOMAIN}
if [ "${INKCERTED}" != "DONE_CBDIGOC" ]; then
 if [ "${INKCERTED}" = "DONE_IC" ]; then
/bin/echo "inkCert used inkCert Proper for ${DOMAIN}. This is for inkCert Certbot.

Instead use: inkcertundo (or, individually: inkcertrevoke, inkcertremove)
"; exit 0
elif [ "${INKCERTED}" = "DONE_LE" ]; then
/bin/echo "inkCert used inkCert-Letsencrypt for ${DOMAIN}. This is for inkCert Certbot.

Instead use: inkcertundole (or, individually: inkcertrevokele, inkcertremovele)
"; exit 0
 elif [ "${INKCERTED}" = "DONE_SC" ]; then
/bin/echo "inkCert used inkCert Self-Cert for ${DOMAIN}. This is for inkCert Certbot.

Instead use: inkcertundosc (or, individually: inkcertrevokesc, inkcertremovesc)
"; exit 0
 fi
/bin/echo "inkCert is not setup for ${DOMAIN}, it only has Snakeoil.

There is nothing to revoke until you run inkcertdo or inkcertdole... And then, certs are cool. Why would you want to revoke them? Are you just revoking stuff at random?
"; exit 0
fi

# Run the LE revoke
/usr/local/bin/certbot revoke --cert-path /etc/inkcert/le/live/${DOMAIN}/cert.pem
# Additional options if not doing certonly: --no-redirect --no-hsts --no-uir
# https://certbot.eff.org/docs/using.html#command-line
# https://certbot.eff.org/#ubuntuxenial-apache

# Echo alliswell
/bin/echo "Unless there is an error message above, the certs should have been revoked from the CA, now uninstall them..."
