#!/bin/sh
#inkVerbSerf! verb.ink

# This script runs doinkcert for all native Verber domains... verb.ink, verb.blue, etc.

# DEV NOTE: This should probably be removed because the DNS record for all verb namespaces is not presumed.

# How to use:
## ./inkcertdo-all-verbs


# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/sitetldstatus

if [ $VERBemail=true ]; then
/opt/verb/serfs/inkcertdo ${emailURI}; fi
wait
if [ $VERBone=true ]; then
/opt/verb/serfs/inkcertdo ${oneURI}; fi
wait
if [ $VERBink=true ]; then
/opt/verb/serfs/inkcertdo ${inkURI}; fi
wait
if [ $VERBblue=true ]; then
/opt/verb/serfs/inkcertdo ${blueURI}; fi
wait
if [ $VERBvip=true ]; then
/opt/verb/serfs/inkcertdo ${vipURI}; fi
wait
if [ $VERBkiwi=true ]; then
/opt/verb/serfs/inkcertdo ${kiwiURI}; fi
wait
if [ $VERBred=true ]; then
/opt/verb/serfs/inkcertdo ${redURI}; fi
