#!/bin/bash
#inkVerbSerf! verb.ink

# This runs inkcertaddle for all domains and subdomains
## Prerequesite: Certs must be installed via inkCert or this will do nothing.

# NOTE: This is intended to be run by inkcertundole

# How to use:
## ./inkcertremoveallle [domain.tld or sub.domain.tld]


# For the domain
/opt/verb/serfs/inkcertremovele ${DOMAIN}

# For any/all sub-domains
## Get the name of each subdomain .conf file available
find . -name "*.${DOMAIN}.conf" | while read findsitesubdomain; do
## Strip the .conf extension
 sitesubdomain=$(basename ${findsitesubdomain} .conf)
## Run inkCertAddLE per site config
 /opt/verb/serfs/inkcertremovele ${sitesubdomain}
wait
done
