#!/bin/sh
#inkVerbSerf! verb.ink

# This batch runs a revoke and uninstall of inkCert Certbot certs for a domain and replaces the Snakeoil certificate
## It applies only to one domain/subdomain at a time
## Prerequesite: inkcertdocb (or both subscripts thereof: inkcertreqcb, inkcertaddcb)

# Dev NOTE:
## The portion of this script that calls the CA to revoke the cert has not been written yet.

# How to use:
## ./inkcertundocb [domain.tld or sub.domain.tld]

#Eg:
## ./inkcertundocb inkisaverb.com
## ./inkcertundocb YOURNAME.verb.one
## ./inkcertundocb owncloud.YOURNAME.verb.blue


DOMAIN=$1

# Check variables
if [ -z ${1} ]; then
/bin/echo "You need to specify a domain. Read the instructions."; exit 0
fi

# Request and get the certs
/opt/verb/serfs/inkcertrevokecb ${DOMAIN}

# Install the certs
/opt/verb/serfs/inkcertremovecb ${DOMAIN}

# Remove mail certs
/usr/bin/rm -f /etc/ssl/server/mail/${DOMAIN}.crt
/usr/bin/rm -f /etc/ssl/server/mail/${DOMAIN}.key
