#!/bin/bash
#inkVerbSerf! verb.ink

# This script runs inkcertdocb for all native Verber domains... verb.ink, verb.blue, etc.

# How to use:
## ./inkcertdocb-all-verbs

usagenotes="This script runs inkcertdocb for all native Verber domains... verb.ink, verb.blue, et cetera"
usageformat="inkcertdocb-all-verbs"
usageexample=""
hierarchy=( oversight )	# Choose: primary (works by itself, may use secondaries or tertiaries); secondary (can work by itself, but not normally, may use other secondaries or tertiaries); tertiary (cannot run by itself, must be run by a secondary or primary);oversight (uses primaries)
vsetnames=(  )	# "Pretty" names for each setting, must be in order of settings
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkcertinstall )
prerequesite=( inkcertinstall )
usedby=(  )
useserfs=( inkcertdocb )
useconfigs=( sitenameip siteurilist sitetldstatus )	# List config files of any kind used in this serf, please preserve order of appearance
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkcertdocb-all-verbs.replace" ]; then . /opt/verb/mods/inkcertdocb-all-verbs.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/inkcertdocb-all-verbs.before" ]; then . /opt/verb/mods/inkcertdocb-all-verbs.before; return 0; fi # Replaces this script


# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/sitetldstatus

# Verify that it's not a domain Dod Verber
if /bin/grep -Fq "SITENAME=DOMAIN_MOD-" /opt/verb/conf/sitenameip; then
/bin/echo "Domain.MOD Verber NOTICE:
This is a Domain Mod Verber. Certbot won't run for so many domains in too short of a time.

You must run inkcertdocb one at a time for each uri, once you reach quota, wait a few days to continue.

Eg: ./inkcertdocb ${inkURI}
"
exit 0; fi

# For any/all sub-domains
if [ ${SERVERTYPE} = "lamp" ] || [ ${SERVERTYPE} = "laemp" ]; then
  cd /opt/verb/conf/webserver/httpd/sites-available
elif [ ${SERVERTYPE} = "lemp" ]; then
  cd /opt/verb/conf/webserver/nginx/sites-available
fi

# Let each run wait 1 second to avoid congesting the server
if [ $VERBemail=true ]; then
	## Get the name of each subdomain .conf file available
	find . -name "*.${emailURI}.conf"|while read findsitesubdomain; do
	## Strip the .conf extension
	 sitesubdomain=$(basename ${findsitesubdomain} .conf)
	## Run inkCertAddLE per site config
	 /opt/verb/serfs/inkcertdocb ${sitesubdomain}
	wait
	done
fi

if [ $VERBone=true ]; then
	## Get the name of each subdomain .conf file available
	find . -name "*.${oneURI}.conf"|while read findsitesubdomain; do
	## Strip the .conf extension
	 sitesubdomain=$(basename ${findsitesubdomain} .conf)
	## Run inkCertAddLE per site config
	 /opt/verb/serfs/inkcertdocb ${sitesubdomain}
	wait
	done
fi

if [ $VERBink=true ]; then
	## Get the name of each subdomain .conf file available
	find . -name "*.${inkURI}.conf"|while read findsitesubdomain; do
	## Strip the .conf extension
	 sitesubdomain=$(basename ${findsitesubdomain} .conf)
	## Run inkCertAddLE per site config
	 /opt/verb/serfs/inkcertdocb ${sitesubdomain}
	wait
	done
fi

if [ $VERBblue=true ]; then
	## Get the name of each subdomain .conf file available
	find . -name "*.${blueURI}.conf"|while read findsitesubdomain; do
	## Strip the .conf extension
	 sitesubdomain=$(basename ${findsitesubdomain} .conf)
	## Run inkCertAddLE per site config
	 /opt/verb/serfs/inkcertdocb ${sitesubdomain}
	wait
	done
fi

if [ $VERBvip=true ]; then
	## Get the name of each subdomain .conf file available
	find . -name "*.${vipURI}.conf"|while read findsitesubdomain; do
	## Strip the .conf extension
	 sitesubdomain=$(basename ${findsitesubdomain} .conf)
	## Run inkCertAddLE per site config
	 /opt/verb/serfs/inkcertdocb ${sitesubdomain}
	wait
	done
fi

if [ $VERBkiwi=true ]; then
	## Get the name of each subdomain .conf file available
	find . -name "*.${kiwiURI}.conf"|while read findsitesubdomain; do
	## Strip the .conf extension
	 sitesubdomain=$(basename ${findsitesubdomain} .conf)
	## Run inkCertAddLE per site config
	 /opt/verb/serfs/inkcertdocb ${sitesubdomain}
	wait
	done
fi

if [ $VERBred=true ]; then
	## Get the name of each subdomain .conf file available
	find . -name "*.${redURI}.conf"|while read findsitesubdomain; do
	## Strip the .conf extension
	 sitesubdomain=$(basename ${findsitesubdomain} .conf)
	## Run inkCertAddLE per site config
	 /opt/verb/serfs/inkcertdocb ${sitesubdomain}
	done
fi




if [ -e "/opt/verb/mods/inkcertdocb-all-verbs.after" ]; then . /opt/verb/mods/inkcertdocb-all-verbs.after; fi # Follows this script
