#!/bin/bash
#inkVerbSerf! verb.ink

# This runs inkcertaddcb for a domain and all of its subdomains
## Prerequesite: inkcertreqcbsingle

# NOTE: This is intended to be run by inkcertdocbsingle, but can be run separately, such as for updates
# NOTE: If your domain and subdomains have the same certificate then run this only for the main domain

# How to use:
## ./inkcertaddallcb [ domain.tld for root wildcard domain ]

# Eg:
## ./inkcertaddallcb NAME.verb.ink (will apply to all subdomains of NAME.verb.ink)
## ./inkcertaddallcb inkisaverb.com (will apply to all subdomains of inkisaverb.com)

usagenotes="This runs inkcertaddcb for a domain and all of its subdomains"
usageformat="inkcertaddallcb [ domain.tld or sub.domain.tld ] [ DOMAIN OF CERTIFICATE IF PARENT, ie: domain.tld ]"
usageexample="inkcertaddallcb NAME.verb.ink (will apply to all subdomains of NAME.verb.ink)
inkcertaddallcb inkisaverb.com (will apply to all subdomains of inkisaverb.com)
inkcertaddallcb subdomain.inkisaverb.com inkisaverb.com (if the SSL cert for poetryiscode.com is included in the CN of the certificate for inkisaverb.com)"
hierarchy=( tertiary inkcertdocb )	# Choose: primary (works by itself, may use secondaries or tertiaries); secondary (can work by itself, but not normally, may use other secondaries or tertiaries); tertiary (cannot run by itself, must be run by a secondary or primary);oversight (uses primaries)
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=( "Domain of cert, if different" )
vopttypes=( isDomain )	# Value types for options in # Validity check functions, must be in order of options
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkcertinstall )
prerequesite=( inkcertinstall inkcertreqcbsingle )
usedby=( inkcertdocb )
useserfs=( inkcertaddcb )
useconfigs=(  )	# List config files of any kind used in this serf, please preserve order of appearance
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkcertaddallcb.replace" ]; then . /opt/verb/mods/inkcertaddallcb.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/inkcertaddallcb.before" ]; then . /opt/verb/mods/inkcertaddallcb.before; return 0; fi # Replaces this script


SITEDOMAIN=$1

# Check inkCert installed
if [ "${INKCERTINSTALLED}" = "NOT_YET" ]; then
/bin/echo "inkCert not yet installed.

First run inkcertinstall
"
exit 0
fi

# Check variables
if [ -z ${1} ]; then
/bin/echo "You need to specify a domain. Read the instructions."; exit 0
fi

# For the main domain first
/opt/verb/serfs/inkcertaddcb ${SITEDOMAIN}
wait

# For any/all sub-domains
if [ ${SERVERTYPE} = "lamp" ] || [ ${SERVERTYPE} = "laemp" ]; then
  cd /opt/verb/conf/webserver/httpd/sites-available
elif [ ${SERVERTYPE} = "lemp" ]; then
  cd /opt/verb/conf/webserver/nginx/sites-available
fi
## Get the name of each subdomain .conf file available
find . -name "*.${SITEDOMAIN}.conf"|while read findsitesubdomain; do
## Strip the .conf extension
 sitesubdomain=$(basename ${findsitesubdomain} .conf)
## Run inkCertAddLE per site config
 /opt/verb/serfs/inkcertaddcb ${sitesubdomain} ${SITEDOMAIN}
wait
done

# Finish
/bin/echo "
Done. ${SITEDOMAIN} certs installed for ${SITEDOMAIN}.
"




if [ -e "/opt/verb/mods/inkcertaddallcb.after" ]; then . /opt/verb/mods/inkcertaddallcb.after; fi # Follows this script
