#!/bin/bash
#inkVerbSerf! verb.ink

# This installs inkCert-Certbot Apache credentials for a given domain, including inkVerb namespace domains
## Prerequesite: inkcertreqcbdigoc
## This is intended as a subscript of inkcertdocbdigoc or to add certs to specific Apache configs as they are installed after the fact, such as in updates.

# How to use:
## ./inkcertaddcbdigoc [domain.tld or sub.domain.tld] [DOMAIN OF CERTIFICATE IF DIFFERENT, ie: domain.tld]

# Eg:
## ./inkcertaddcbdigoc NAME.verb.ink (will apply ONLY to NAME.verb.ink)
## ./inkcertaddcbdigoc blog.NAME.verb.ink (BAD NEWS: this won't work!! blog.NAME.verb.ink does not have a certificate by itself, use: 'inkcertaddallcb NAME.verb.ink')
## ./inkcertaddcbdigoc blog.NAME.verb.ink NAME.verb.ink
## ./inkcertaddcbdigoc inkisaverb.com (BAD NEWS: this won't work!! inkisaverb.com does not have a certificate by itself, use: 'inkcertaddallcb inkisaverb.com')
## ./inkcertaddcbdigoc poetryiscode.com inkisaverb.com (if the SSL cert for poetryiscode.com is included in the CN of the certificate for inkisaverb.com)


SITEDOMAIN=$1
CERTDOMAIN=$2

# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/inkcert/inkcertstatus

# Check inkCert installed
if [ "${INKCERTINSTALLED}" = "NOT_YET" ]; then
/bin/echo "inkCert not yet installed.

First run inkcertinstall
"
exit 0
fi

# Check variables
if [ -z ${1} ]; then
/bin/echo "You need to specify a domain. Read the instructions."; exit 0
fi

# Verify that Certbot DigitalOcean secrets are setup
if [ ! -f "/opt/verb/.certbotsecrets/inkcertcbdigoc.ini" ]; then
  /bin/echo "Sorry, DigitalOcean Certbot secrets not installed yet. Doing nothing."
  exit 0
fi

# Set variable for same certificate as domain (most all scenarios)
if [ -z ${2} ]; then
CERTDOMAIN=$1
fi

# Certs should already be in place from inkcertreqle
## This is a test for the inkcert directories:
if [ ! -d "/etc/inkcert/le/live/${CERTDOMAIN}" ]; then
/bin/echo "Something's wrong...

inkCert-Letsencrypt certs were not installed for ${SITEDOMAIN} because the ${CERTDOMAIN} certs don't exist. Common problems can include:
  - DNS records: ${SITEDOMAIN} should point to ${SITEIP}
  - DNS for ${SITEDOMAIN} may need a \"wildcard\" * CNAME record that points to ${SITEDOMAIN} as the \"hostname\"
  - DNS records can take about 4 hours to have effect
  - You need to first run: inkcertreqcbdigoc
  - Do not run inkcertreqle for individual subdomains with a shared certificate, but only for: ${blueURI}, ${rocksURI}, inkisaverb.com, etc.
  - The verb/conf/inkcert/cli-ini/ file for ${CERTDOMAIN} may not contain the subdomain you are using.
"
exit 8
fi

# Check Apache config status
if /bin/grep -Fq "#INKVERB-INKCERT=INK_NO" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf ; then
 /bin/echo "Setting inkCert configs for ${SITEDOMAIN}..."
elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_CB" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf ; then
 /bin/echo "Already certified by inkCert-CB: ${SITEDOMAIN}. Moving on..."
 exit 0
elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_CBDIGOC" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf ; then
 /bin/echo "Already certified by inkCert-CBDIGOC: ${SITEDOMAIN}. Moving on..."
 exit 0
elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_LE" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf ; then
 /bin/echo "Already certified by inkCert-LE: ${SITEDOMAIN}. Moving on..."
 exit 0
elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_IC" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf ; then
 /bin/echo "Already certified by inkCert-IC: ${SITEDOMAIN}. Moving on..."
 exit 0
elif /bin/grep -Fq "#INKVERB-INKCERT=NA" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf ; then
 /bin/echo "inkCert certs do not apply here: ${SITEDOMAIN}. Moving on..."
 exit 0
else
 /bin/echo "Something's really wrong with ${SITEDOMAIN}. No inkCert, no non-inkCert either. I quit here."
 exit 6
fi

# Stop Apache
/usr/bin/apachectl graceful-stop; wait
/bin/systemctl stop httpd; wait

# Comment the Snakeoil certs
/bin/sed -i "s/SSLCertificateFile/#INKVERB-INKCERT-COMMENT-SSLCertificateFile/g" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf
/bin/sed -i "s/SSLCertificateKeyFile/#INKVERB-INKCERT-COMMENT-SSLCertificateKeyFile/g" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf

# Insert the inkCert certs
/bin/sed -i "s/#INKVERB-INKCERT=INK_.*/#INKVERB-INKCERT=DONE_CBDIGOC\n\t\tSSLCertificateFile\t\/etc\/inkcert\/le\/live\/${CERTDOMAIN}\/cert\.pem\n\t\tSSLCertificateKeyFile\t\/etc\/inkcert\/le\/live\/${CERTDOMAIN}\/privkey\.pem\n\t\tSSLCertificateChainFile\t\/etc\/inkcert\/le\/live\/${CERTDOMAIN}\/chain\.pem\n\t\t#INKVERB-INKCERT-stop/" /opt/verb/conf/webserver/httpd/sites-available/${SITEDOMAIN}.conf
/usr/bin/apachectl start

# Create the inkCert-DOMAIN config file
/bin/echo "#!/bin/sh
INKCERTED=DONE_CBDIGOC" > /opt/verb/conf/inkcert/cli-ini/siteinkcert.${SITEDOMAIN}

# inkCert status & exit
if [ "${FIRSTINKCERTADDCB}" = "NOT_YET" ]; then
## Config status: first inkCert done
/bin/sed -i "s/FIRSTINKCERTADDCB=\"NOT_YET\"/FIRSTINKCERTADDCBDIGOC=\"DONE\"/g" /opt/verb/conf/inkcert/inkcertstatus
## Create the cron job
### Add CB's auto updater to the cron
/bin/echo '4 4 * * * root /opt/verb/donjon/inkcertcb-renew-all.sh' > /etc/cron.d/inkcertrenewcbcron
/bin/chmod 0644 /etc/cron.d/inkcertrenewcbcron
fi

# Create the inkCert log file
/bin/mkdir -p /var/log/inkcert/
/usr/bin/touch /var/log/inkcert/inkcertle.log

# Start Apache
/bin/systemctl start httpd; wait

# Finish
/bin/echo "
${SITEDOMAIN} certs installed.
"
