#!/bin/bash
#inkVerbSerf! verb.ink

# This installs the inkCert Self-Cert (SC) SSL certificate service
## This is a Prerequesite of inkcertsc
## DEV: This has not been tested and is useful in theory only, such as for private networks
## DEV: This has not been tested and may still need inkcertdosc to be written

# How to use:
## ./inkcertinstallsc


# Include and check the config
. /opt/verb/conf/inkcertstatus

if [ "${INKCERTSCINSTALLED}" = "DONE" ]; then
/bin/echo "inkCert-SC already installed."
exit 0; fi

# Install
## inkCert proper
/usr/bin/apt-get install -y openssl
/bin/mkdir -p /etc/inkcert
cd /etc/inkcert || exit 0
/bin/mkdir -p client live csr req
/bin/cp /opt/verb/conf/inkcert/verber-openssl.cnf /etc/inkcert/client/openssl.cnf
## inkCertSC
/bin/mkdir -p /etc/inkcert/sc
cd /etc/inkcert/sc || exit 0
/bin/mkdir -p ca intrm cli pub keys rcinst live
/bin/chmod 444 pub
/bin/chmod 400 keys
/bin/chmod 444 rcinst
cd /etc/inkcert/sc/ca || exit 0
/bin/mkdir -p priv newcerts certs crl
/bin/chmod -R 700 /etc/inkcert/sc/ca/priv
/usr/bin/touch /etc/inkcert/sc/ca/index.txt
/bin/echo 1000 > /etc/inkcert/sc/ca/serial
cd /etc/inkcert/sc/intrm/ || exit 0
/bin/mkdir -p priv newcerts certs crl csr
/bin/chmod -R 700 /etc/inkcert/sc/intrm/priv
/usr/bin/touch /etc/inkcert/sc/intrm/index.txt
/bin/echo 1000 > /etc/inkcert/sc/intrm/serial
cd /etc/inkcert/sc/cli || exit 0
/bin/mkdir -p priv certs csr
/bin/chmod -R 700 /etc/inkcert/sc/cli/priv

## Symlinks
/bin/ln -sfn /etc/inkcert/req /opt/verb/
/bin/ln -sfn /etc/inkcert/req /srv/www/vip/

# Set configs
/bin/echo "INKCERTSCINSTALLED=\"DONE\"" >> /opt/verb/conf/inkcertstatus

# Finish
/bin/echo "
inkCert Self-Cert is now installed and ready to make self-signed & root cert sets for SSL.
"




if [ -e "/opt/verb/mods/inkcertinstallsc.after" ]; then . /opt/verb/mods/inkcertinstallsc.after; fi # Follows this script
