#!/bin/sh
#inkVerbSerf! verb.ink

# This installs the inkCert SSL certificate service
## Currently, inkCert uses letsencrypt for main websites with options for "inkCert proper", the non-standard inkVerb CA service.
## To use letsencrypt for websites, run -le variants of inkcert- serfs, such as inkcertdole

# How to use:
## ./inkcertinstall


# Include the configs
. /opt/verb/conf/inkcert/inkcertstatus
. /opt/verb/conf/servertype
. /opt/verb/conf/sitenameip

if [ "${INKCERTINSTALLED}" = "DONE" ]; then
/bin/echo "inkCert already installed."
exit 0; fi

# Install
## Certbot - Currently, inkCert is largely powered by Certbot/Letsencrypt, so it uses links. This may eventually change, but file paths won't.

if [ ${SERVERTYPE} = "lemp" ] || [ ${SERVERTYPE} = "laemp" ]; then
  /usr/bin/pacman -S --noconfirm certbot certbot-nginx
elif [ ${SERVERTYPE} = "lamp" ]; then
  /usr/bin/pacman -S --noconfirm certbot certbot-apache
fi

## inkCert proper
/bin/mkdir -p /etc/inkcert
cd /etc/inkcert
/bin/mkdir -p client live csr req
/bin/cp /opt/verb/conf/inkcert/verber-openssl.cnf /etc/inkcert/client/openssl.cnf
## Symlinks for Letsencrypt
/bin/ln -sfn /etc/letsencrypt /etc/inkcert/le
/bin/ln -sfn /etc/inkcert/req /opt/verb/
/bin/ln -sfn /etc/inkcert/req /srv/www/vip/
## Named Letsencrypt/Certbot DNS challenge key config
inkCertbotKeyOnly="$(grep -F 'key "inkCertbotKey" { algorithm hmac-sha512; secret "' /etc/named.conf | sed 's?key "inkCertbotKey" { algorithm hmac-sha512; secret "??' | sed 's?"; };??')"
/bin/echo "dns_rfc2136_server = ${SITEIPV4}
dns_rfc2136_name = inkCertbotKey
dns_rfc2136_secret = ${inkCertbotKeyOnly}
dns_rfc2136_algorithm = HMAC-SHA512" > /etc/letsencrypt/rfc2136.ini
/usr/bin/chown root:named /etc/letsencrypt/rfc2136.ini
/usr/bin/chmod 640 /etc/letsencrypt/rfc2136.ini

# Set configs
/bin/sed -i "s/INKCERTINSTALLED=\"NOT_YET\"/INKCERTINSTALLED=\"DONE\"/g" /opt/verb/conf/inkcert/inkcertstatus

# Finish
/bin/echo "
inkCert is now installed and ready to make CSRs for SSL domains and SSH keys.

The CA URLs are set to defaults. If you want a different CA on the inkCert list, run setinkcertsslca and setinkcertsshca before making any CSRs.
"
