#!/bin/sh
#inkVerbSerf! verb.ink

# This script removes the Apache credentials and certificates for inkCert-Certbot certs for a domain and replaces the Snakeoil certificate
## It also applies to all subdomains for that domain
## Prerequesite: inkcertrevokecbdigoc
## This is intended as a subscript of inkcertundocbdigoc

# How to use:
## ./inkcertremovecbdigoc [domain.tld OR subdomain.domain.tld]

#Eg:
## ./inkcertremovecbdigoc inkisaverb.com
## ./inkcertremovecbdigoc YOURNAME.verb.blue


DOMAIN=$1

# Check Apache config status
if /bin/grep -Fq "#INKVERB-INKCERT=DONE_CBDIGOC" /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf ; then
/bin/echo "Removing inkCert-CB configs from ${DOMAIN}..."
else
 if /bin/grep -Fq "#INKVERB-INKCERT=DONE_CB" /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf ; then
  /bin/echo "Apache configs use inkCert Proper. Use: inkcertremovecb"
  exit 8
 elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_IC" /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf ; then
  /bin/echo "Apache configs use inkCert Proper. Use: inkcertremove"
  exit 8
 elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_LE" /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf ; then
  /bin/echo "Apache configs use inkCert-Letsencrypt. Use: inkcertremovele"
  exit 8
 elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_SC" /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf ; then
  /bin/echo "Apache configs use inkCert Self-Cert. Use: inkcertremovesc"
  exit 8
 elif /bin/grep -Fq "#INKVERB-INKCERT=NO" /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf ; then
  /bin/echo "inkCert certs aren't setup. Nothing to do."
  exit 0
 else
  /bin/echo "Something's really wrong. No inkCert, no non-inkCert either. I quit."
  exit 6
 fi
fi

# Remove the certs
/opt/verb/serfs/inkcertdeletecble ${DOMAIN}

###### Legacy method ######
### live/
#for i in /etc/inkcert/le/live/${DOMAIN}/*.pem
#do
#/bin/rm  "$(readlink -f $i)"
#/bin/rm "$i"
#done
#/bin/rm -rf /etc/inkcert/le/live/${DOMAIN}
### archive/
#for i in /etc/inkcert/le/archive/${DOMAIN}/*.pem
#do
#/bin/rm  "$(readlink -f $i)"
#/bin/rm "$i"
#done
#/bin/rm -rf /etc/inkcert/le/archive/${DOMAIN}
### renewal/
#/bin/rm -rf /etc/inkcert/le/renewal/${DOMAIN}.conf

# Apache
## Check that the certs are no longer live
if [ ! -d /etc/inkcert/le/live/${DOMAIN} ]; then
## Uncomment the Snakeoil cert configs
/bin/sed -i "s/#INKVERB-INKCERT-COMMENT-SSLCertificateFile/SSLCertificateFile/g" /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf
/bin/sed -i "s/#INKVERB-INKCERT-COMMENT-SSLCertificateKeyFile/SSLCertificateKeyFile/g" /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf
## Remove the inkCert cert liness
/bin/sed -i '/#INKVERB-INKCERT=DONE_CBDIGOC/,/#INKVERB-INKCERT-stop/{/#INKVERB-INKCERT=DONE_CBDIGOC/!{/#INKVERB-INKCERT-stop/!d}}' /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf
/bin/sed -i 's/#INKVERB-INKCERT=DONE_CBDIGOC/#INKVERB-INKCERT=INK_NO_REMOVED/' /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf
/bin/sed -i '/#INKVERB-INKCERT-stop/d' /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf
/usr/bin/apachectl graceful
## Note to the config
/bin/sed -i "s/INKCERTED=DONE_CBDIGOC/INKCERTED=NO_REMOVED_CBDIGOC/" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${DOMAIN}

# Finish
/bin/echo "inkCert has been uninstalled from ${DOMAIN}. Using Snakeoil certs."
exit 0
else

# If they are live
/bin/echo "Something's wrong...

The certs still seem to be live. Did you first run inkcertrevokele or simply run inkcertundole?
"
fi
