#!/bin/sh
#inkVerbSerf! verb.ink

# This script revokes the inkCert LE or CB certs for a specified domain
## It applies to an entire domain
## Prerequesite: inkcertdole or inkcertdocb (or both subscripts thereof: inkcertreq*, inkcertadd*)

## This is meant to be run as a subscript for inkcertremovecb or inkcertremovele

# How to use:
## ./inkcertdeletecble [domain.tld or sub.domain.tld]

#Eg:
## ./inkcertdeletecble inkisaverb.com
## ./inkcertdeletecble YOURNAME.verb.one
## ./inkcertdeletecble owncloud.YOURNAME.verb.blue (if the subdomain is managed like a full domain on the Verber)


DOMAIN=$1

# Include and check the inkCert domain config
## Verify that the domain is installed
if [ ! -f /opt/verb/conf/inkcert/cli-ini/siteinkcert.${DOMAIN} ]; then
/bin/echo "Sorry, Bucko. ${DOMAIN} is not even installed.

Why revoke a cert for a domain that isn't even installed here?
"; exit 0
fi
## Domain cert status
. /opt/verb/conf/inkcert/cli-ini/siteinkcert.${DOMAIN}
if [ "${INKCERTED}" = "DONE_LE" ] || [ "${INKCERTED}" = "DONE_CB" ] || [ "${INKCERTED}" = "DONE_CBDIGOC" ]; then
/bin/echo "Certs present for ${DOMAIN}, removing them..."
else
/bin/echo "This only removes SSL certificates set up using Letsencrypt or Certbot.

Such certs aren't set up using those. You'll need a different tool for this job.
"; exit 0
fi

# Remove archive on this Verber
if [ -d /etc/inkcert/le/archive/${DOMAIN}/ ]; then
/bin/echo "Removing the archive for ${DOMAIN}..."
shred -f -x /etc/inkcert/le/archive/${DOMAIN}/*
/bin/rm -rf /etc/inkcert/le/archive/${DOMAIN}/
else
/bin/echo "Archive for ${DOMAIN} not found. Nothing here to remove. All set."
fi

# Remove live keys on this Verber
if [ -d /etc/inkcert/le/live/${DOMAIN}/ ]; then
/bin/echo "Removing the live keys for ${DOMAIN}..."
/bin/rm -rf /etc/inkcert/le/live/${DOMAIN}/
else
/bin/echo "Live keys for ${DOMAIN} not found. Nothing here to remove. All set."
fi

# Remove renewal config on this Verber
/bin/echo "Removing the renewal config for ${DOMAIN}..."
/bin/rm -f /etc/inkcert/le/renewal/${DOMAIN}.conf

# Echo alliswell
/bin/echo "Unless there is an error message above, the certs should have been revoked from the CA, now uninstall them..."
