#!/bin/sh
#inkVerbSerf! verb.ink

# This batch runs a revoke and uninstall of inkCert Proper certs for a domain and replaces the Snakeoil certificate
## It applies only to one domain/subdomain at a time
## Prerequesite: inkcertdo (or both subscripts thereof: inkcertreq, inkcertadd)

# Dev NOTE:
## The portion of this script that calls the CA to revoke the cert has not been written yet.

# How to use:
## ./inkcertundo [domain.tld or sub.domain.tld]

#Eg:
## ./inkcertundo inkisaverb.com
## ./inkcertundo YOURNAME.verb.one
## ./inkcertundo owncloud.YOURNAME.verb.blue


DOMAIN=$1

# Check variables
if [ -z ${1} ]; then
/bin/echo "You need to specify a domain. Read the instructions."; exit 0
fi

# Request and get the certs
/opt/verb/serfs/inkcertrevoke ${DOMAIN}

# Install the certs
/opt/verb/serfs/inkcertremove ${DOMAIN}

