#!/bin/bash
#inkVerbSerf! verb.ink

# This batch runs inkCert Self-Cert creation and install scripts for a given domain, including inkVerb namespace domains
## It also applies to all subdomains for that domain
## Prereqesite: inkcertinstall

# How to use:
## ./inkcertdosc [domain.tld NO SUBDOMAINS]

#Eg:
## ./inkcertdosc inkisaverb.com
## ./inkcertdosc YOURNAME.verb.blue


DOMAIN=$1

# Check inkCert installed
if [ "${INKCERTINSTALLED}" = "NOT_YET" ]; then
/bin/echo "inkCert not yet installed.

First run inkcertinstall
"
exit 0
fi

# Check variables
if [ -z ${1} ]; then
/bin/echo "You need to specify a domain. Read the instructions."; exit 0
fi

# Request and get the certs
/opt/verb/serfs/inkcertsc ${DOMAIN}; wait
if [ "$certsuccess" != "true" ]; then
  /bin/echo "Cert for ${DOMAIN} aborted."
  exit 4;
fi

# Install the certs
if /bin/grep -q "INKCERTED=NO" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${DOMAIN}; then
  if [ -e /etc/inkcert/le/live/${DOMAIN} ]; then
    /opt/verb/serfs/inkcertaddsc ${DOMAIN}; wait
  fi
fi

# Domain check for mail certs
. /opt/verb/conf/siteurilist
if [ "${DOMAIN}" = "${nameURI}" ] || [ "${DOMAIN}" != "${emailTLD}" ] && [ "${DOMAIN}" != "${hostURI}" ] && [ "${DOMAIN}" != "${serveURI}" ] && [ "${DOMAIN}" != "${emailTLDURI}" ] && [ "${DOMAIN}" != "${emailURI}" ] && [ "${DOMAIN}" != "${oneURI}" ] && [ "${DOMAIN}" != "${inkURI}" ] && [ "${DOMAIN}" != "${blueURI}" ] && [ "${DOMAIN}" != "${vipURI}" ] && [ "${DOMAIN}" != "${kiwiURI}" ] && [ "${DOMAIN}" != "${redURI}" ]; then
  /opt/verb/serfs/setinkcertmailcerts ${DOMAIN}
fi

# Update the inkCert-DOMAIN config file, fail silently (eg. when used on subdomains)
/bin/sed -i "s/INKCERTED=.*/INKCERTED=\"DONE_SC\"/" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${DOMAIN} 2> /dev/null

# Finish
/bin/echo "
Excellent!
Verify above exits - IMPORTANT NOTES: ... - Congratulations!

If so, then ${DOMAIN} and all subdomains are now live with inkCert Letsencrypt certificates.
"
