#!/bin/sh
#inkVerbSerf! verb.ink

# This batch runs a revoke and uninstall of inkCert Certbot for DigitalOcean certs for a domain and replaces the Snakeoil certificate
## It applies only to one domain/subdomain at a time
## Prerequesite: inkcertdocbdigoc (or both subscripts thereof: inkcertreqcbdigoc, inkcertaddcbdigoc)

# Dev NOTE:
## The portion of this script that calls the CA to revoke the cert has not been written yet.

# How to use:
## ./inkcertundocbdigoc [domain.tld or sub.domain.tld]

#Eg:
## ./inkcertundocbdigoc inkisaverb.com
## ./inkcertundocbdigoc YOURNAME.verb.one
## ./inkcertundocbdigoc owncloud.YOURNAME.verb.blue


DOMAIN=$1

# Check variables
if [ -z ${1} ]; then
/bin/echo "You need to specify a domain. Read the instructions."; exit 0
fi

# Request and get the certs
/opt/verb/serfs/inkcertrevokecbdigoc ${DOMAIN}

# Install the certs
/opt/verb/serfs/inkcertremovecbdigoc ${DOMAIN}

# Remove mail certs
/usr/bin/rm -f /etc/inkcert/mail/${DOMAIN}.crt
/usr/bin/rm -f /etc/inkcert/mail/${DOMAIN}.key
