#!/bin/bash
#inkVerbSerf! verb.ink

# This removes all inkCert files entirely for inkCert-LE and inkCert Proper

# How to use:
## ./inkcertkilldomain [domain.tld]


# Dependencies
if ! /bin/grep -q 'INKCERTINSTALLED="DONE"' /opt/verb/conf/inkcert/inkcertstatus; then
  /usr/bin/echo "Install inkCert first, I quit."; exit 8
fi
if ! /bin/grep -q 'INKDNSSTAT="INSTALLED"' /opt/verb/conf/inkdns/inkdnsconf; then
  /usr/bin/echo "Install inkDNS first, I quit."; exit 8
fi
if ! /bin/grep -q 'SITEMAILSTATUS="VMAIL_SERVER"' /opt/verb/conf/sitemailpath; then
  /usr/bin/echo "Install Postfix Vmail first, I quit."; exit 8
fi

KILLDOMAIN=$1

# Remove inkCert configs
/bin/rm -f /opt/verb/conf/inkcert/cli-ini/cli.${KILLDOMSHELL}.ini
/bin/rm -f /opt/verb/conf/inkcert/cli-ini/siteinkcert.${KILLDOMSHELL}
/bin/rm -f /etc/inkcert/cli.${KILLDOMAIN}.ini
/bin/rm -rf /etc/inkcert/le/live/${KILLDOMAIN}
/bin/rm -rf /etc/inkcert/live/${KILLDOMAIN}
/bin/rm -f /etc/ssl/server/mail/${KILLDOMAIN}.crt
/bin/rm -f /etc/ssl/server/mail/${KILLDOMAIN}.key

