#!/bin/sh
#inkVerbSerf! verb.ink

# This script runs inkcertdocbwild for all native Verber domains... verb.ink, verb.blue, etc.

# How to use:
## ./inkcertdocbwild-all-verbs


# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/sitetldstatus

# Verify that it's not a domain Dod Verber
if /bin/grep -Fq "SITENAME=DOMAIN_MOD-" /opt/verb/conf/sitenameip; then
/bin/echo "Domain.MOD Verber NOTICE:
This is a Domain Mod Verber. Certbot won't run for so many domains in too short of a time.

You must run inkcertdocbwild one at a time for each uri, once you reach quota, wait a few days to continue.

Eg: ./inkcertdocbwild ${inkURI}
"
exit 0; fi

# Let each run wait 1 second to avoid congesting the server
if [ $VERBemail=true ]; then
/opt/verb/serfs/inkcertdocbwild ${emailURI}; fi
wait
if [ $VERBone=true ]; then
/opt/verb/serfs/inkcertdocbwild ${oneURI}; fi
wait
if [ $VERBink=true ]; then
/opt/verb/serfs/inkcertdocbwild ${inkURI}; fi
wait
if [ $VERBblue=true ]; then
/opt/verb/serfs/inkcertdocbwild ${blueURI}; fi
wait
if [ $VERBvip=true ]; then
/opt/verb/serfs/inkcertdocbwild ${vipURI}; fi
wait
if [ $VERBkiwi=true ]; then
/opt/verb/serfs/inkcertdocbwild ${kiwiURI}; fi
wait
if [ $VERBred=true ]; then
/opt/verb/serfs/inkcertdocbwild ${redURI}; fi
