#!/bin/sh
#inkVerbSerf! verb.ink

# This sets the Secondary Inker for backup DNS for this Verber
## This has no IP settings because this is used for NS statements in the DNS records only

# How to use:
## ./inkdnssetinker2 [ domain ]

# Eg:
## ./inkdnssetinker2 ns2.inkisaverb.com
## ./inkdnssetinker2 ns.poetryiscode.com


# Defaults
. /opt/verb/conf/inkdns/inkdnsinkers

# Check variables present
## Domain
if [ -z "$1" ] || [ "$1" -d ]; then
  /bin/echo "Inkder domain not specified; using default."
  NSDOMAIN="${DEFAULTns2}"
else
  NSDOMAIN="$1"
fi
## IP4
if [ -z "$2" ] || [ "$2" -d ]; then
  /bin/echo "IP4 not specified; using default."
  NSIP4="${INKER2ip4}"
else
  NSIP4="$2"
fi
## IP6
if [ -z "$3" ] || [ "$3" -d ]; then
  /bin/echo "IP6 not specified; using default."
  NSIP6="${INKDER2ip6}"
else
  NSIP6="$3"
fi

# Set the changes
/bin/sed -i "s/SITE2INKERDNS.*/SITE2INKERDNS=\"${NSDOMAIN}\"/" /opt/verb/conf/sitenameip
/bin/sed -i "s/SITE2INKERIP4.*/SITE2INKERIP4=\"${NSIP4}\"/" /opt/verb/conf/sitenameip
/bin/sed -i "s/SITE2INKERIP6.*/SITE2INKERIP6=\"${NSIP6}\"/" /opt/verb/conf/sitenameip

# Finish
/bin/echo "Secondary DNS Inker set to: ${NSIP4} & ${NSIP6} for ${NSDOMAIN}"
