#!/bin/bash
#inkVerbSerf! verb.ink

# This sets the secondary Inker for backup DNS on this server
## This has no IP settings because this is used for NS statements in the DNS records only

# How to use:
## ./inkdnssetrink2 [ -d OR domain.tld - optional, rare ] [ -i OR IPv4 Address - optional ] [ IPv6 Address - optional ]

# Eg:
## ./inkdnssetrink2
## ./inkdnssetrink2 -d 111.222.333.444 0000:ef89::2001
## ./inkdnssetrink2 -d 111.222.333.444
## ./inkdnssetrink2 -d -i 0000:ef89::2001
## ./inkdnssetrink2 ns2.inkisaverb.com
## ./inkdnssetrink2 ns.poetryiscode.com
## ./inkdnssetrink2 ns2.inkisaverb.com 111.222.333.444
## ./inkdnssetrink2 ns2.inkisaverb.com -i 0000:ef89::2001
## ./inkdnssetrink2 ns.poetryiscode.com 555.555.555.555 8001:0056::489a

usagenotes="This sets the secondary Inker for backup DNS on this server"
usageformat="inkdnssetrink2 [ -d OR domain.tld - optional, rare ] [ -i OR IPv4 Address - optional ] [ IPv6 Address - optional ]"
usageexample="inkdnssetrink2
inkdnssetrink2 -d 111.222.333.444 0000:ef89::2001
inkdnssetrink2 -d 111.222.333.444
inkdnssetrink2 -d -i 0000:ef89::2001
inkdnssetrink2 ns2.inkisaverb.com
inkdnssetrink2 ns.poetryiscode.com
inkdnssetrink2 ns2.inkisaverb.com 111.222.333.444
inkdnssetrink2 ns2.inkisaverb.com -i 0000:ef89::2001
inkdnssetrink2 ns.poetryiscode.com 555.555.555.555 8001:0056::489a"
hierarchy=( secondary )
vsetnames=(  )
vsettypes=(  )
voptnames=( "-d || Domain" "-i || IPv4" "IPv6" )
vopttypes=( "string_match || isDomain" "string_match || isIP4" "isIP6" )
voptflags=( d i )
voptflagpurpose=( "No domain, but other args" "No IP4, but other args" )
dependencyinstall=( inkdnsinstall )
prerequesite=(  )
usedby=( inkdnsinstall rink::addvps )
useserfs=( inkdnsrefreshbind )
useconfigs=( inklists/inkdnsrinks )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkdnssetrink2.replace" ]; then . /opt/verb/mods/inkdnssetrink2.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/inkdnssetrink2.before" ]; then . /opt/verb/mods/inkdnssetrink2.before; return 0; fi # Replaces this script


# Defaults
. /opt/verb/conf/inklists/inkdnsrinks

# Check variables present
## Domain
if [ -z "$1" ] || [ "$1" = "-d" ]; then
  if [ -f "/opt/verb/conf/inkdns/sdns/dnshost" ]; then
    /bin/echo "This is a DNS server, so its nameservers must be set manually."
    return
  else
    /bin/echo "Rink domain not specified; using default."
    NSDOMAIN="${DEFAULTns2}"
  fi
else
  NSDOMAIN="$1"
fi
## IP4
if [ -z "$2" ] || [ "$2" = "-i" ]; then
  if [ -f "/opt/verb/conf/inkdns/sdns/dnshost" ]; then
    /bin/echo "This is a DNS server, so its nameservers must be set manually."
    return
  else
    /bin/echo "IP4 not specified; using default."
    NSIP4="${RINKNS2ip4}"
  fi
else
  NSIP4="$2"
fi
## IP6
if [ -z "$3" ]; then
  if [ -f "/opt/verb/conf/inkdns/sdns/dnshost" ]; then
    /bin/echo "This is a DNS server, so its nameservers must be set manually."
    return
  else
    /bin/echo "IP6 not specified; using default."
    NSIP6="${RINKNS2ip6}"
  fi
else
  NSIP6="$3"
fi

# Set the changes
/bin/sed -i "s/SITE2RINKDNS.*/SITE2RINKDNS=\"${NSDOMAIN}\"/" /opt/verb/conf/sitenameip
/bin/sed -i "s/SITE2RINKIP4.*/SITE2RINKIP4=\"${NSIP4}\"/" /opt/verb/conf/sitenameip
/bin/sed -i "s/SITE2RINKIP6.*/SITE2RINKIP6=\"${NSIP6}\"/" /opt/verb/conf/sitenameip
/bin/sed -i "s/SITE2RINKPORT.*/SITE2RINKPORT=\"${PORT2}\"/" /opt/verb/conf/sitenameip

# Finish
/opt/verb/serfs/inkdnsrefreshbind
/bin/echo "Secondary DNS Inker set to: ${NSIP4} & ${NSIP6} for ${NSDOMAIN}"




if [ -e "/opt/verb/mods/inkdnssetrink2.after" ]; then . /opt/verb/mods/inkdnssetrink2.after; fi # Follows this script
