#!/bin/sh
#inkVerbSerf! verb.ink

# This adds a subdomain A & AAAA records to an existing ONE DNS record in the inkDNS zone file on this Verber

# How to use:
## ./inkdnsaddonesub [subdomain]


DNSSUBDOM="$1"
ZONEDIR="inkzones"

# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

# Check if already added
if /bin/grep -Fq "${DNSSUBDOM}.${oneURI}" /opt/verb/conf/inkdns/${ZONEDIR}/db.${oneURI}; then
/bin/echo "The subdomain ${DNSSUBDOM} has already been added to ${oneURI}. Use inkdnskillsub to remove it."
exit 0; fi

# Echo the record
## db.DOM
/bin/echo "; Subdomain Records Added by inkDNS ${DNSSUBDOM}.${oneURI}" >> /opt/verb/conf/inkdns/${ZONEDIR}/db.${vipURI}
/bin/echo "${DNSSUBDOM}.${oneURI}   IN  A   ${SITEIP}" >> /opt/verb/conf/inkdns/${ZONEDIR}/db.${oneURI}
/bin/echo "${DNSSUBDOM}.${oneURI}   IN  AAAA   ${SITEIPV6}" >> /opt/verb/conf/inkdns/${ZONEDIR}/db.${oneURI}
## nv.DOM
/bin/echo "; PTR Subdomain Records Added by inkDNS ${DNSSUBDOM}.${oneURI}" >> /opt/verb/conf/inkdns/${ZONEDIR}/nv.${vipURI}
/bin/echo "${SITEARPAIP4}		IN  PTR  ${DNSSUBDOM}.${oneURI}" >> /opt/verb/conf/inkdns/${ZONEDIR}/nv.${oneURI}
/bin/echo "${SITEARPAIP6}		IN  PTR  ${DNSSUBDOM}.${oneURI}" >> /opt/verb/conf/inkdns/${ZONEDIR}/nv.${oneURI}

# Set the Serial No
/opt/verb/serfs/inkdnsserial ${oneURI} verber

# Refresh zones
if [ -f "/opt/verb/conf/inkdns/inkdnsconf" ]; then
  . /opt/verb/conf/inkdns/inkdnsconf
  if [ "${INKDNSSTAT}" = "INSTALLED" ]; then
/opt/verb/serfs/inkdnsrefreshbind; fi; fi

# Finish
/bin/echo "The ONE subdomain ${DNSSUBDOM} has been added to the DNS zone file."
