#!/bin/bash
#inkVerbSerf! verb.ink

# This adds the mail subdomain A & AAAA records in the inkDNS zone file on the server

# How to use:
## ./inkdnsaddmail [ domain.tld ]
## ./inkdnsaddmail [ domain.tld ] verber

usagenotes="This adds the mail subdomain A & AAAA records in the inkDNS zone file on the server"
usageformat="inkdnsaddmail [ domain.tld ] verber"
usageexample="inkdnsaddmail inkisaverb.com
inkdnsaddmail myself.verb.blue verber"
hierarchy=( tertiary newdomainshell )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=( "verber" )
vopttypes=( string_match )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkdnsinstall )
prerequesite=(  )
usedby=( newdomainshell )
useserfs=( inkdnsserial inkdnsrefreshbind )
useconfigs=( sitenameip )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkdnsaddmail.replace" ]; then . /opt/verb/mods/inkdnsaddmail.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/inkdnsaddmail.before" ]; then . /opt/verb/mods/inkdnsaddmail.before; return 0; fi # Replaces this script


DNSDOMAIN="$1"
if [ -n $2 ] && [ "$2" = "verber" ]; then
  ZONEDIR="inkzones"
else
  ZONEDIR="zones"
fi

# Include the configs
. /opt/verb/conf/sitenameip

# Check if already added
if /bin/grep -Fq "; Hostname Mail Record Defaults" /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNSDOMAIN}; then
/bin/echo "Mail Record Defaults already added to . Use killinkdnsmail to remove them."
exit 0; fi

# Echo the records
## db.DOM
/bin/echo "; Hostname Mail Record Defaults
email.${DNSDOMAIN}. IN  CNAME	mail.${DNSDOMAIN}.
${DNSDOMAIN}.       IN  MX 50	mail.${DNSDOMAIN}.
mail.${DNSDOMAIN}.  IN  A    	${SITEIPV4}
smtp.${DNSDOMAIN}.  IN  A    	${SITEIPV4}
imap.${DNSDOMAIN}.  IN  A    	${SITEIPV4}
pop3.${DNSDOMAIN}.  IN  A    	${SITEIPV4}
pop2.${DNSDOMAIN}.  IN  A    	${SITEIPV4}
pop.${DNSDOMAIN}.   IN  A    	${SITEIPV4}
mail.${DNSDOMAIN}.  IN  AAAA 	${SITEIPV6}
smtp.${DNSDOMAIN}.  IN  AAAA 	${SITEIPV6}
imap.${DNSDOMAIN}.  IN  AAAA 	${SITEIPV6}
pop3.${DNSDOMAIN}.  IN  AAAA 	${SITEIPV6}
pop2.${DNSDOMAIN}.  IN  AAAA 	${SITEIPV6}
pop.${DNSDOMAIN}.   IN  AAAA 	${SITEIPV6}
;; End Mail Defaults" >> /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNSDOMAIN}
/bin/sed -i "s/; Text Record Defaults/; Text Record Defaults\n${DNSDOMAIN}.	\tIN  TXT	\t\"v=spf1 a mx a:${DNSDOMAIN} ip4:${SITEIPV4} ip6:${SITEIPV6} -all\"\n_dmarc.${DNSDOMAIN}.	\tIN  TXT	\t\"v=DMARC1; p=reject; fo=0; aspf=r; adkim=r; pct=100; ri=86400; rua=mailto:dmark@${DNSDOMAIN};\"/" /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNSDOMAIN}

## nv.DOM
/bin/echo "; PTR Hostname Mail Record Defaults
${SITEARPAIP4}		IN  PTR  mail.${DNSDOMAIN}.
${SITEARPAIP4}		IN  PTR  smtp.${DNSDOMAIN}.
${SITEARPAIP4}		IN  PTR  imap.${DNSDOMAIN}.
${SITEARPAIP4}		IN  PTR  pop3.${DNSDOMAIN}.
${SITEARPAIP4}		IN  PTR  pop2.${DNSDOMAIN}.
${SITEARPAIP4}		IN  PTR   pop.${DNSDOMAIN}.
${SITEARPAIP6}		IN  PTR  mail.${DNSDOMAIN}.
${SITEARPAIP6}		IN  PTR  smtp.${DNSDOMAIN}.
${SITEARPAIP6}		IN  PTR  imap.${DNSDOMAIN}.
${SITEARPAIP6}		IN  PTR  pop3.${DNSDOMAIN}.
${SITEARPAIP6}		IN  PTR  pop2.${DNSDOMAIN}.
${SITEARPAIP6}		IN  PTR   pop.${DNSDOMAIN}.
;; End Mail Defaults" >> /opt/verb/conf/inkdns/${ZONEDIR}/nv.${DNSDOMAIN}

# Set the Serial No
if [ "${ZONEDIR}" = "inkzones" ]; then
  /opt/verb/serfs/inkdnsserial ${DNSDOMAIN} verber
elif [ "${ZONEDIR}" = "zones" ]; then
  /opt/verb/serfs/inkdnsserial ${DNSDOMAIN}
fi

# Refresh zones
if [ -f "/opt/verb/conf/inkdnsconf" ]; then
  . /opt/verb/conf/inkdnsconf
  if [ "${INKDNSSTAT}" = "INSTALLED" ]; then
/opt/verb/serfs/inkdnsrefreshbind; fi; fi

# Finish
/bin/echo "The Mail Record Defaults have been added to the ${DNSDOMAIN} DNS zone file."




if [ -e "/opt/verb/mods/inkdnsaddmail.after" ]; then . /opt/verb/mods/inkdnsaddmail.after; fi # Follows this script
