#!/bin/sh
#inkVerbSerf! verb.ink

# This adds a subdomain A & AAAA records to an existing DNS record in the inkDNS zone file on this Verber

# How to use:
## ./inkdnsaddsub [subdomain] [domain]


DNSSUBDOM="$1"
DNSDOMAIN="$2"

# Include the configs
. /opt/verb/conf/sitenameip

# Check if already added
if /bin/grep -Fq "${DNSSUBDOM}.${DNSDOMAIN}" /opt/verb/conf/inkdns/zones/db.${DNSDOMAIN}; then
/bin/echo "The subdomain ${DNSSUBDOM} has already been added to ${DNSDOMAIN}. Use inkdnskillsub to remove it."
exit 0; fi

# Echo the records
## db.DOM
/bin/echo "; Subdomain Records Added by inkDNS ${DNSSUBDOM}.${DNSDOMAIN}" >> /opt/verb/conf/inkdns/zones/db.${DNSDOMAIN}
/bin/echo "${DNSSUBDOM}.${DNSDOMAIN}   IN  A    ${SITEIP}" >> /opt/verb/conf/inkdns/zones/db.${DNSDOMAIN}
/bin/echo "${DNSSUBDOM}.${DNSDOMAIN}   IN  AAAA   ${SITEIPV6}" >> /opt/verb/conf/inkdns/zones/db.${DNSDOMAIN}
## nv.DOM
/bin/echo "; PTR Subdomain Records Added by inkDNS ${DNSSUBDOM}.${DNSDOMAIN}" >> /opt/verb/conf/inkdns/zones/nv.${DNSDOMAIN}
/bin/echo "${SITEARPAIP4}		IN  PTR  ${DNSSUBDOM}.${DNSDOMAIN}" >> /opt/verb/conf/inkdns/zones/nv.${DNSDOMAIN}
/bin/echo "${SITEARPAIP6}		IN  PTR  ${DNSSUBDOM}.${DNSDOMAIN}" >> /opt/verb/conf/inkdns/zones/nv.${DNSDOMAIN}

# Set the Serial No
/opt/verb/serfs/inkdnsserial ${DNSDOMAIN}

# Refresh zones
if [ -f "/opt/verb/conf/inkdns/inkdnsconf" ]; then
  . /opt/verb/conf/inkdns/inkdnsconf
  if [ "${INKDNSSTAT}" = "INSTALLED" ]; then
/opt/verb/serfs/inkdnsrefreshbind; fi; fi

# Finish
/bin/echo "The subdomain ${DNSSUBDOM} has been added to the ${DNSDOMAIN} DNS zone file."
