#!/bin/sh
#inkVerbSerf! verb.ink

# This adds the inkDKIM key to an existing DNS TXT record in the inkDNS zone file on this Verber

# How to use:
## ./inkdnsaddinkdkim [domain]


DNSDOMAIN="$1"
if [ -n $2 ] && [ "$2" = "verber" ]; then
  ZONEDIR="inkzones"
else
  ZONEDIR="zones"
fi

# Include the configs
. /opt/verb/conf/sitenameip

# Check if already added
if /bin/grep -Fq "; inkDKIM key" /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNSDOMAIN}; then
/bin/echo "The inkDKIM key for ${DNSDOMAIN} has already been added. Use inkdnskillinkdkim to remove it."
exit 0; fi
if /bin/grep -Fq "dkim._domainkey" /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNSDOMAIN}; then
/bin/echo "The ${DNSDOMAIN} zone file seems to have been tampered with. It should say nothing about DKIM keys at this point, but it does. Fix that first."
exit 7; fi

# Echo the key
/bin/echo "; inkDKIM key ${DNSDOMAIN}" >> /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNSDOMAIN}
/bin/echo $(/bin/cat /etc/opendkim/keys/${DNSDOMAIN}/inkdkim.txt) >> /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNSDOMAIN}
/bin/echo ";; End inkDKIM key ${DNSDOMAIN}" >> /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNSDOMAIN}
## Add the domain to the record host name
/bin/sed -i "s/inkdkim\._domainkey/inkdkim\._domainkey\.${DNSDOMAIN}\./" /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNSDOMAIN}

# Set the Serial No
/opt/verb/serfs/inkdnsserial ${DNSDOMAIN} verber

# Refresh zones
if [ -f "/opt/verb/conf/inkdns/inkdnsconf" ]; then
  . /opt/verb/conf/inkdns/inkdnsconf
  if [ "${INKDNSSTAT}" = "INSTALLED" ]; then
/opt/verb/serfs/inkdnsrefreshbind; fi; fi

# Finish
/bin/echo "The inkDKIM key has been added to the ${DNSDOMAIN} DNS zone file."
