#!/bin/sh
#inkVerbSerf! verb.ink

# This removes a subdomain A & AAAA records from an existing DNS record in the inkDNS zone file on this Verber

# How to use:
## ./inkdnskillsub [subdomain] [domain]


DNSSUBDOM="$1"
DNSDOMAIN="$2"

# Include the configs
. /opt/verb/conf/sitenameip

# Check if already added
if ! /bin/grep -Fq "${DNSSUBDOM}.${DNSDOMAIN}" /opt/verb/conf/inkdns/zones/db.${DNSDOMAIN}; then
/bin/echo "The subdomain ${DNSSUBDOM} has not been added to ${DNSDOMAIN}. Use inkdnsaddsub to add it."
exit 0; fi

# Remove the records
/bin/sed -i "/; Subdomain Records Added by inkDNS ${DNSSUBDOM}\.${DNSDOMAIN}/,+2d" /opt/verb/conf/inkdns/zones/db.${DNSDOMAIN}
/bin/sed -i "/; PTR Subdomain Records Added by inkDNS ${DNSSUBDOM}\.${DNSDOMAIN}/,+2d" /opt/verb/conf/inkdns/zones/nv.${DNSDOMAIN}

# Set the Serial No
/opt/verb/serfs/inkdnsserial ${DNSDOMAIN}

# Refresh zones
if [ -f "/opt/verb/conf/inkdns/inkdnsconf" ]; then
  . /opt/verb/conf/inkdns/inkdnsconf
  if [ "${INKDNSSTAT}" = "INSTALLED" ]; then
/opt/verb/serfs/inkdnsrefreshbind; fi; fi

# Finish
/bin/echo "The subdomain ${DNSSUBDOM} has been removed from the ${DNSDOMAIN} DNS zone file."
