#!/bin/bash
#inkVerbKnight! verb.ink

# This adds a slave domain DNS configuration

# How to use:
## ./inkdnsaddslave [ domain.tld ] [ IPv4 ] [ IPv6 ]

# Eg:
## ./inkdnsaddslave inkisaverb.com 1.1.1.1 1::1
## ./inkdnsaddslave sub.inkisaverb.com 1.1.1.1 0001:0000:0000:0000:0000:0000:0000:0001


# Config check
if [ ! -f "/opt/verb/conf/inkdns/sdns/dnshost" ]; then
  /bin/echo "This server is not a DNS, I quit."; exit 0
fi

# Argument check
if [ -z "$3" ]; then
  /bin/echo "Not enough arguments, I quit."; exit 0
fi

# Domain
DOMAIN="$1"

# Already existing check
if [ -f "/opt/verb/conf/inkdns/sdns/s.${DOMAIN}" ]; then
  /bin/echo "SDNS configuration for ${DOMAIN} already exists, I quit."; exit 0
fi

# IP4 ARPA
SIPV4="$2"
SIPV4ARPA=$(/bin/echo ${SIPV4} | sed -r 's/^([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$/\4.\3.\2.\1.in-addr.arpa/')

# IP6
SIPV6="$3"
### helper to convert hex to dec (portable version)
hex2dec(){
    [ "$1" != "" ] && printf "%d" "$(( 0x$1 ))"
}

### expand an IPv6 address
expand_ipv6() {
    ip=$1

    # prepend 0 if we start with :
    /bin/echo $ip | /bin/grep -qs "^:" && ip="0${ip}"

    # expand ::
    if /bin/echo $ip | /bin/grep -qs "::"; then
        colons=$(/bin/echo $ip | sed 's/[^:]//g')
        missing=$(/bin/echo ":::::::::" | sed "s/$colons//")
        expanded=$(/bin/echo $missing | sed 's/:/:0/g')
        ip=$(/bin/echo $ip | sed "s/::/$expanded/")
    fi

    blocks=$(/bin/echo $ip | /bin/grep -o "[0-9a-f]\+")
    set $blocks

    printf "%04x:%04x:%04x:%04x:%04x:%04x:%04x:%04x\n" \
        $(hex2dec $1) \
        $(hex2dec $2) \
        $(hex2dec $3) \
        $(hex2dec $4) \
        $(hex2dec $5) \
        $(hex2dec $6) \
        $(hex2dec $7) \
        $(hex2dec $8)
}

### returns a compressed IPv6 address under the form recommended by RFC5952
compress_ipv6() {
    ip=$1

    blocks=$(/bin/echo $ip | /bin/grep -o "[0-9a-f]\+")
    set $blocks

    # compress leading zeros
    ip=$(printf "%x:%x:%x:%x:%x:%x:%x:%x\n" \
        $(hex2dec $1) \
        $(hex2dec $2) \
        $(hex2dec $3) \
        $(hex2dec $4) \
        $(hex2dec $5) \
        $(hex2dec $6) \
        $(hex2dec $7) \
        $(hex2dec $8)
    )

    # prepend : for easier matching
    ip=:$ip

    # :: must compress the longest chain
    for pattern in :0:0:0:0:0:0:0:0 \
            :0:0:0:0:0:0:0 \
            :0:0:0:0:0:0 \
            :0:0:0:0:0 \
            :0:0:0:0 \
            :0:0; do
        if /bin/echo $ip | /bin/grep -qs $pattern; then
            ip=$(/bin/echo $ip | sed "s/$pattern/::/")
            # if the substitution occured before the end, we have :::
            ip=$(/bin/echo $ip | sed 's/:::/::/')
            break # only one substitution
        fi
    done

    # remove prepending : if necessary
    /bin/echo $ip | /bin/grep -qs "^:[^:]" && ip=$(echo $ip | sed 's/://')

    /bin/echo $ip
}

### reverse expanded IPv6 for ARPA
## THANKS https://stackoverflow.com/a/53674816/10343144
rarpa_ipv6() {
  local idx s=${1//:}
  for (( idx=${#s} - 1; idx>=0; idx-- )); do
    printf '%s.' "${s:$idx:1}"
  done
  printf 'ip6.arpa\n'
}

## Our new variables for the rest
SIPV6EXP=$(expand_ipv6 ${SIPV6})
SIPV6CMP=$(compress_ipv6 ${SIPV6})
SIPV6ARPA=$(rarpa_ipv6 ${SIPV6EXP})

## Create the config
/usr/bin/cat <<EOF > /opt/verb/conf/inkdns/sdns/s.${DOMAIN}
SDOM="${DOMAIN}"
SIP4="${SIPV4}"
SIP4ARPA="${SIPV4ARPA}"
SIP6EXP="${SIPV6EXP}"
SIP6CMP="${SIPV6CMP}"
SIP6ARPA="${SIPV6ARPA}"
EOF

# Finish
/bin/echo "${DOMAIN} added to this DNS server. Run inkdnsrefreshbind to apply changes."
