#!/bin/bash
#inkVerbSerf! verb.ink

# This adds the inkDKIM key to an existing DNS TXT record in the inkDNS zone file on the server

# How to use:
## ./inkdnsaddinkdkim [ domain.tld ]

usagenotes="This adds the inkDKIM key to an existing DNS TXT record in the inkDNS zone file on the server"
usageformat="inkdnsaddinkdkim [ domain.tld ]"
usageexample="inkdnsaddinkdkim inkisaverb.com"
hierarchy=( tertiary adddomain )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkdnsinstall )
prerequesite=( newinkdkim )
usedby=( newdomainshell inkvmailinstall )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkdnsaddinkdkim.replace" ]; then . /opt/verb/mods/inkdnsaddinkdkim.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/inkdnsaddinkdkim.before" ]; then . /opt/verb/mods/inkdnsaddinkdkim.before; return 0; fi # Replaces this script


DNSDOMAIN="$1"
if [ -n $2 ] && [ "$2" = "verber" ]; then
  ZONEDIR="inkzones"
else
  ZONEDIR="zones"
fi

# Include the configs
. /opt/verb/conf/sitenameip

# Check if already added
if /bin/grep -Fq "; inkDKIM key" /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNSDOMAIN}; then
/bin/echo "The inkDKIM key for ${DNSDOMAIN} has already been added. Use killinkdnsinkdkim to remove it."
exit 0; fi
if /bin/grep -Fq "dkim._domainkey" /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNSDOMAIN}; then
/bin/echo "The ${DNSDOMAIN} zone file seems to have been tampered with. It should say nothing about DKIM keys at this point, but it does. Fix that first."
exit 7; fi

# Echo the key
## Remove any existing entries
sed -i "/inkdkim\._domainkey/d" /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNSDOMAIN}
sed -i "/; inkDKIM key ${DNSDOMAIN}/d" /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNSDOMAIN}
sed -i "/;; End inkDKIM key ${DNSDOMAIN}/d" /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNSDOMAIN}
## Add the entry
/bin/echo "; inkDKIM key ${DNSDOMAIN}" >> /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNSDOMAIN}
/bin/echo $(/bin/cat /etc/opendkim/keys/${DNSDOMAIN}/inkdkim.txt) >> /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNSDOMAIN}
/bin/echo ";; End inkDKIM key ${DNSDOMAIN}" >> /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNSDOMAIN}
## Append the domain to the record host name
/bin/sed -i "s/inkdkim\._domainkey/inkdkim\._domainkey\.${DNSDOMAIN}\./" /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNSDOMAIN}

# Set the Serial No
/opt/verb/serfs/inkdnsserial ${DNSDOMAIN} verber

# Refresh zones
if [ -f "/opt/verb/conf/inkdnsconf" ]; then
  . /opt/verb/conf/inkdnsconf
  if [ "${INKDNSSTAT}" = "INSTALLED" ]; then
/opt/verb/serfs/inkdnsrefreshbind; fi; fi

# Finish
/bin/echo "The inkDKIM key has been added to the ${DNSDOMAIN} DNS zone file."




if [ -e "/opt/verb/mods/inkdnsaddinkdkim.after" ]; then . /opt/verb/mods/inkdnsaddinkdkim.after; fi # Follows this script
