#!/bin/bash
#inkVerbKnight! verb.ink

# This displays information for a domain served on this DNS as a slave record

# How to use:
## ./inkdnsshowslavedns [ domain.tld ]

# Eg:
## ./inkdnsshowslavedns inkisaverb.com
## ./inkdnsshowslavedns sub.inkisaverb.com


# Config check
if [ ! -f "/opt/verb/conf/inkdns/sdns/dnshost" ]; then
  /bin/echo "This server is not a DNS, I quit."; exit 0
fi

# Argument check
if [ -z "$1" ]; then
  /bin/echo "You must specify a domain."; exit 0
fi

# Domain
DOMAIN="$1"

# Already existing check
if [ ! -f "/opt/verb/conf/inkdns/sdns/s.${DOMAIN}" ]; then
  /bin/echo "No SDNS configuration for ${DOMAIN}, I quit."; exit 0
fi

# Display the info
. /opt/verb/conf/inkdns/sdns/s.${DOMAIN}

echo "Domain: ${SDOM}
IPv4: ${SIP4}
IPv6: ${SIP6CMP}
IPv4 ARPA: ${SIP4ARPA}
IPv6 ARPA: ${SIP6ARPA}"
