#!/bin/sh
#inkVerbSerf! verb.ink

# This sets the secondary Inker for backup DNS on this server
## This has no IP settings because this is used for NS statements in the DNS records only

# How to use:
## ./inkdnssetinker2 [ -d OR domain.tld - optional, rare ] [ -d OR IPv4 Address - optional ] [ IPv6 Address - optional ]

# Eg:
## ./inkdnssetinker2
## ./inkdnssetinker2 -d 111.222.333.444 0000:ef89::2001
## ./inkdnssetinker2 -d 111.222.333.444
## ./inkdnssetinker2 -d -d 0000:ef89::2001
## ./inkdnssetinker2 ns2.inkisaverb.com
## ./inkdnssetinker2 ns.poetryiscode.com
## ./inkdnssetinker2 ns2.inkisaverb.com 111.222.333.444
## ./inkdnssetinker2 ns2.inkisaverb.com -d 0000:ef89::2001
## ./inkdnssetinker2 ns.poetryiscode.com 555.555.555.555 8001:0056::489a

usagenotes="This sets the secondary Inker for backup DNS on this server"
usageformat="inkdnssetinker2 [ -d OR domain.tld - optional, rare ] [ -d OR IPv4 Address - optional ] [ IPv6 Address - optional ]"
usageexample="inkdnssetinker2
inkdnssetinker2 -d 111.222.333.444 0000:ef89::2001
inkdnssetinker2 -d 111.222.333.444
inkdnssetinker2 -d -d 0000:ef89::2001
inkdnssetinker2 ns2.inkisaverb.com
inkdnssetinker2 ns.poetryiscode.com
inkdnssetinker2 ns2.inkisaverb.com 111.222.333.444
inkdnssetinker2 ns2.inkisaverb.com -d 0000:ef89::2001
inkdnssetinker2 ns.poetryiscode.com 555.555.555.555 8001:0056::489a"
hierarchy=( secondary )
vsetnames=(  )
vsettypes=(  )
voptnames=( "-d || Domain" "-d || IPv4" "-d || IPv6" )
vopttypes=( "string_match || isDomain" "string_match || isIP4" "isIP6" )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkdnsinstall )
prerequesite=(  )
usedby=( inkdnsinstall )
useserfs=( inkdnsrefreshbind )
useconfigs=( inkdnsinkers )
if [ -n "infoINKonly" ] && [ "infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkdnssetinker2.replace" ]; then . /opt/verb/mods/inkdnssetinker2.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/inkdnssetinker2.before" ]; then . /opt/verb/mods/inkdnssetinker2.before; return 0; fi # Replaces this script


# Defaults
. /opt/verb/conf/inkdnsinkers

# Check variables present
## Domain
if [ -z "$1" ] || [ -d "$1" ]; then
  /bin/echo "Inkder domain not specified; using default."
  NSDOMAIN="${DEFAULTns2}"
else
  NSDOMAIN="$1"
fi
## IP4
if [ -z "$2" ] || [ -d "$2" ]; then
  /bin/echo "IP4 not specified; using default."
  NSIP4="${INKER2ip4}"
else
  NSIP4="$2"
fi
## IP6
if [ -z "$3" ] || [ -d "$3" ]; then
  /bin/echo "IP6 not specified; using default."
  NSIP6="${INKDER2ip6}"
else
  NSIP6="$3"
fi

# Set the changes
/bin/sed -i "s/SITE2INKERDNS.*/SITE2INKERDNS=\"${NSDOMAIN}\"/" /opt/verb/conf/sitenameip
/bin/sed -i "s/SITE2INKERIP4.*/SITE2INKERIP4=\"${NSIP4}\"/" /opt/verb/conf/sitenameip
/bin/sed -i "s/SITE2INKERIP6.*/SITE2INKERIP6=\"${NSIP6}\"/" /opt/verb/conf/sitenameip

# Finish
/opt/verb/serfs/inkdnsrefreshbind
/bin/echo "Secondary DNS Inker set to: ${NSIP4} & ${NSIP6} for ${NSDOMAIN}"




if [ -e "/opt/verb/mods/inkdnssetinker2.after" ]; then . /opt/verb/mods/inkdnssetinker2.after; fi # Follows this script
