#!/bin/bash
#inkVerbKnight! verb.ink

# This removes the config for a domain served on this DNS as a slave record

# How to use:
## ./inkdnskillslavedns [ domain.tld ]

# Eg:
## ./inkdnskillslavedns inkisaverb.com
## ./inkdnskillslavedns sub.inkisaverb.com


# Config check
if [ ! -f "/opt/verb/conf/inkdns/sdns/dnshost" ]; then
  /bin/echo "This server is not a DNS, I quit."; exit 0
fi

# Argument check
if [ -z "$1" ]; then
  /bin/echo "You must specify a domain."; exit 0
fi

# Domain
DOMAIN="$1"

# Already existing check
if [ ! -f "/opt/verb/conf/inkdns/sdns/s.${DOMAIN}" ]; then
  /bin/echo "No SDNS configuration for ${DOMAIN}, I quit."; exit 0
fi

# Remove the config
/usr/bin/rm -f /opt/verb/conf/inkdns/sdns/s.${DOMAIN}

# Finish
/bin/echo "${DOMAIN} removed from this DNS server. Run inkdnsrefreshbind to apply changes."
