#!/bin/sh
#inkVerbSerf! verb.ink

# This removes an existing domain inkDNS zone file from this Verber

# How to use:
## ./inkdnskilldomain [domain]


# Dependencies
if ! /bin/grep -q 'INKCERTINSTALLED="DONE"' /opt/verb/conf/inkcert/inkcertstatus; then
  /usr/bin/echo "Install inkCert first, I quit."; exit 8
fi
if ! /bin/grep -q 'INKDNSSTAT="INSTALLED"' /opt/verb/conf/inkdns/inkdnsconf; then
  /usr/bin/echo "Install inkDNS first, I quit."; exit 8
fi
if ! /bin/grep -q 'SITEMAILSTATUS="VMAIL_SERVER"' /opt/verb/conf/sitemailpath; then
  /usr/bin/echo "Install Postfix Vmail first, I quit."; exit 8
fi

DNSDOMAIN="$1"

# Include the configs
. /opt/verb/conf/sitenameip

# Check if added
if [ ! -e "/opt/verb/conf/inkdns/zones/db.${DNSDOMAIN}" ]; then
/bin/echo "The domain ${DNSDOMAIN} zone file has not been created. Use inkdnsadddomain to add it."
exit 0; fi

# Remove the records
/bin/rm -f /opt/verb/conf/inkdns/zones/db.${DNSDOMAIN}
/bin/rm -f /opt/verb/conf/inkdns/zones/nv.${DNSDOMAIN}

# Refresh zones & delete the global rDNS entry
if [ -f "/opt/verb/conf/inkdns/inkdnsconf" ]; then
  . /opt/verb/conf/inkdns/inkdnsconf
  if [ "${INKDNSSTAT}" = "INSTALLED" ]; then
/opt/verb/serfs/inkdnsrefreshbind; fi; fi

# Finish
/bin/echo "${DNSDOMAIN} DNS zone file removed."
