#!/bin/sh
#IVapp installer! verb.ink

# This installs the IVapp submodule with settings to be used by inkNet

# How to use:
## ./inknetinstallivapp


# Run the installer
/opt/verb/donjon/ivapp/installivapp /opt/verb/conf/inknet/ivapp-inknet.conf
wait





if [ -e "/opt/verb/mods/inknetinstallivapp.after" ]; then . /opt/verb/mods/inknetinstallivapp.after; fi # Follows this script
