#!/bin/sh
#inkVerbSerf! verb.ink

# This adds a Vrk Client for this inkNet CA Verber to host
## This can be run to update an existing config
## Prerequisite: inknetinstallca

# How to use:
## ./inknetaddvrkclient [username on machine] [machine name - AKA 'computer name' - or URI if has one] [vrk ip - if known]

# Eg:
## ./inknetaddvrkclient jimmy uWorkStudioJimmy
## ./inknetaddvrkclient jimmy uWorkStudioJimmy 999.99.99.999
## ./inknetaddvrkclient root work.jimmy.verb.ink 999.99.99.999
## ./inknetaddvrkclient root work_jimmy_verb_ink 999.99.99.999
## ./inknetaddvrkclient root work.ink.inkisaverb.com 999.99.99.999
## ./inknetaddvrkclient root work_ink_inkisaverb_com 999.99.99.999


# Prerequesites
if [ -f /opt/verb/conf/inknet/ca.verber.cnf ]; then
. /opt/verb/conf/inknet/ca.verber.cnf
 if [ "${INKNETSTATUS}" != "INSTALLED" ]; then
/bin/echo "inkNet not quite installed. First, run inknetinstallca"
exit 0
 fi
else
/bin/echo "inkNet not installed. First, run inknetinstallca"
exit 0
fi

ADDUSER="$1"
ICMACHINE="$2"
ADDMACHINE="$(/bin/echo ${ICMACHINE} | sed 's/_/\./g')"
SCRMACHINE="$(/bin/echo ${ICMACHINE} | sed 's/\./_/g')"
ADDCLIENTNAME="${ADDUSER}_${SCRMACHINE}"
if [ -z ${3} ]; then
ADDIP="NOT_SET"
else
ADDIP="$3"
fi
ADDAPG=$(/usr/bin/pwgen -1 -0 -A 4)
# New username based on user, random appendage, and computer name
FULLUSERNAME=${ADDUSER}${ADDAPG}${SCRMACHINE}
## Truncate the new username to the 32 character limit
ADDUSERNAME=$(/bin/echo $FULLUSERNAME | cut -c1-32)
ADDPASSWORD=$(/usr/bin/pwgen -1 -s 15)

# Just in case user already exists
if [ -f /opt/verb/conf/inknet/vrk/client.vrk.${ADDCLIENTNAME}.cnf ]; then
/bin/echo "Umm... How do I say this...

A config already exists for that Vrk Station name.

Note: Your name \"${FULLCLIENTNAME}\" is cut to 18 characters at \"${ADDCLIENTNAME}\" because of system filename limits. Even if your full \"computer name\" is different, this could create a conflict, in theory. If that's the case, create a different user on your Vrk Station computer, re-install Vrk again for that user, then try again from that user.

If you really need to continue and replace the existing profile by this name, first delete the profile for ${ADDCLIENTNAME} at inknet/clients/client.vrk.${ADDCLIENTNAME}.cnf in configs on the Verber
...then run this again.
"
exit 0
fi

# Create the config
. /opt/verb/conf/siteport
ADDLOGINPORT=${SITEPORT}
/bin/echo "#!/bin/sh
# inkNet config, verb.ink
## This contains information about a Vrk Client's credentials used in signing SSH keys for inkNet on this CA Verber
## Note that a local Vrk Station only uses the local username as the URI for SSH key and cert purposes

CLIENTUSER=\"${ADDUSER}\"
CLIENTURI=\"${ADDMACHINE}\"
CLIENTNAME=\"${ADDCLIENTNAME}\"
CLIENTIP=\"${ADDIP}\"
CLIENTUSERNAME=\"${ADDUSERNAME}\"
CLIENTPASSWORD=\"${ADDPASSWORD}\"
CLIENTPORT=\"${ADDLOGINPORT}\"
" > /opt/verb/conf/inknet/vrk/client.vrk.${ADDCLIENTNAME}.cnf

# Create the IVapp user
/opt/verb/serfs/inknetivappadduser ${ADDUSERNAME} ${ADDPASSWORD} vrk
wait

# Create the inkNet Client tool links
/bin/ln -sfn /opt/verb/tools/vrker /opt/ivapp/inknet/vrker/${ADDUSERNAME}/tools

# FInish
/bin/echo "All set. Your Vrk Station has been added as a Client to this Verber.

That machine's user account will be known here as: ${ADDCLIENTNAME}"

## Serf message
/bin/echo "
Now, you need to add the client ssh-rsa key via: inknetaddclientkey

Then follow instructions.
"





if [ -e "/opt/verb/mods/inknetaddvrkclient.after" ]; then . /opt/verb/mods/inknetaddvrkclient.after; fi # Follows this script
