#!/bin/sh
#inkVerbSerf! verb.ink

# This adds a Vrk/Verber Client's public SSH key to "authorized_hosts" on the CA Verber
## If the key is not included in the initial command, it will be read interactively.
## Prerequisite: inknetaddvrkclient/inknetaddverberclient

# How to use:
## ./inknetaddclientkey [vrk/verber type] [Client Host/Name] ["FULL KEY" - in quotes! - optional]

# Eg: (for Verber)
## ./inknetaddclientkey verber joeyhost_joeysite_verb_ink
## ./inknetaddclientkey verber joeyhost.joeysite.verb.ink
## ./inknetaddclientkey verber joeyhost_joeysite_verb_ink "ssh-rsa AAAAOmIOMIWhfsdfENFSDFaffJLKfsSDJsdSDKjWdsfsadfOkEjMCAfdSDKFLOIjhWESF.....WWLKqhOIMhgbSDF boss@joey"
## ./inknetaddclientkey verber joeyhost.joeysite.verb.ink "ssh-rsa AAAAOmIOMIWhfsdfENFSDFaffJLKfsSDJsdSDKjWdsfsadfOkEjMCAfdSDKFLOIjhWESF.....WWLKqhOIMhgbSDF boss@joey"

# Eg: (for Vrk Station)
## ./inknetaddclientkey vrk joey_gCodingStationJoey
## ./inknetaddclientkey vrk joey@gCodingStationJoey
## ./inknetaddclientkey vrk joey_gCodingStationJoey "ssh-rsa AAAAOmIOMIWhfsdfENFSDFaffJLKfsSDJsdSDKjWdsfsadfOkEjMCAfdSDKFLOIjhWESF.....WWLKqhOIMhgbSDF joey@gCodingStationJoey"
## ./inknetaddclientkey vrk joey@gCodingStationJoey "ssh-rsa AAAAOmIOMIWhfsdfENFSDFaffJLKfsSDJsdSDKjWdsfsadfOkEjMCAfdSDKFLOIjhWESF.....WWLKqhOIMhgbSDF joey@gCodingStationJoey"


VTYPE=$1
VINAME=$2
VCKEY=$3
# Determine vrk or verber
if [ "${VTYPE}" = "vrk" ]; then
VCNAME="$(/bin/echo ${VINAME} | sed 's/\./_/g' | sed 's/@/_/g' )"
fi
if [ "${VTYPE}" = "verber" ]; then
VCNAME="$(/bin/echo ${VINAME} | sed 's/\./_/g')"
VCHOST="$(/bin/echo ${VINAME} | sed 's/_/\./g')"
VCURI="$(/bin/echo ${VCHOST} | rev | cut -d'.' -f-3 | rev)"
fi

if [ "${VTYPE}" != "vrk" ] && [ "${VTYPE}" != "verber" ] ; then
/bin/echo "You need to specify \"vrk\" or \"verber\". Read the instructions."; exit 8; fi

# Check if the Client has been added
if [ "${VTYPE}" = "vrk" ]; then
 if [ ! -e "/opt/verb/conf/inknet/vrk/client.vrk.${VCNAME}.cnf" ]; then
 /bin/echo "You must add the Client first using: inknetaddvrkclient."; exit 8; fi
fi
if [ "${VTYPE}" = "verber" ]; then
 if [ ! -e "/opt/verb/conf/inknet/verber/client.verber.${VCNAME}.cnf" ]; then
 /bin/echo "You must add the Client first using: inknetaddverberclient."; exit 8; fi
fi

# Include the configs
if [ "${VTYPE}" = "vrk" ]; then
. /opt/verb/conf/inknet/vrk/client.vrk.${VCNAME}.cnf; fi
if [ "${VTYPE}" = "verber" ]; then
. /opt/verb/conf/inknet/verber/client.verber.${VCNAME}.cnf; fi
. /opt/verb/conf/inknet/ca.verber.cnf

# Prompt for the copy-paste
if [ -z "${VCKEY}" ]; then
/bin/echo "
 Activate Client key area...

A key looks something like this, but longer, notice front and end:
ssh-rsa AAAAOmIOMIWhWESF.....WWLKqIMhgbSDF joey@gCodingStationJoey

Please copy and paste the entire contents of the Client public key, then press <Enter>...
"
read CPKEY
VCKEY="${CPKEY}"
fi
if [ -z "${VCKEY}" ]; then
/bin/echo "
 Activate Client key area...

A key looks something like this, but longer, notice front and end:
ssh-rsa AAAAOmIOMIWhWESF.....WWLKqIMhgbSDF joey@gCodingStationJoey

Please copy and paste the entire contents of the Client public key, then press <Enter>...
"
read CPKEY
VCKEY="${CPKEY}"
fi
if [ -z "${VCKEY}" ]; then
/bin/echo "You aren't entering a key. I quit."; exit 5; fi

# Add the key
if [ "${VTYPE}" = "vrk" ]; then
/bin/echo "${VCKEY}" >> /opt/ivapp/inknet/vrker/${CLIENTUSERNAME}/.ssh/authorized_keys
fi
if [ "${VTYPE}" = "verber" ]; then
/bin/echo "${VCKEY}.${VCURI}" >> /opt/ivapp/inknet/verber/${CLIENTUSERNAME}/.ssh/authorized_keys
## Remove any duplication of the URI
/bin/sed -i "s/${VCURI}\.${VCURI}/${VCURI}/" /opt/ivapp/inknet/verber/${CLIENTUSERNAME}/.ssh/authorized_keys
fi

# Finish
/bin/echo "Success! The Client key for ${CLIENTURI} has been added."

## Serf message
/bin/echo "
Now, you need to run inknetpackclientpkg

Follow the instructions."





if [ -e "/opt/verb/mods/inknetaddclientkey.after" ]; then . /opt/verb/mods/inknetaddclientkey.after; fi # Follows this script
