#!/bin/bash
#inkVerbSerf! verb.ink

# This creates a temporary link for downloading the inkVPN client profile file
## This is run automatically by inkvpninstall and inkvpnclientkey, but can be run separately

# How to use:
## ./inkvpnclientdl


# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

# Set the link names
cDIR="$(/usr/bin/pwgen -s -1 128)"
/bin/mkdir -p /srv/www/html/ink.serve/${SERVEDIR}/${cDIR}

# Link it to the Serve folder
/bin/ln -sfn /opt/openvpn/certificates/clients/client.ovpn /srv/www/html/ink.serve/${SERVEDIR}/${cDIR}/${SITENAME}-${SITETLD}-client.ovpn

# Permissions
/bin/chown -R www:www /srv/www/html/ink.serve/${SERVEDIR}

# Finish
/bin/echo "The client OVPN profile is ready for download.
Get it here: https://${serveURI}/${SERVEDIR}/${cDIR}/${SITENAME}-${SITETLD}-client.ovpn
This download link will expire in at least 30 minutes."
