#!/bin/sh
#inkVerbSerf! verb.ink

# This sets an emal alias to 'active' in the inkvmail database

# How to use:
## ./inkvmailonalias [ emal alias ]

usagenotes="This sets an emal alias to 'active' in the inkvmail database"
usageformat="inkvmailonalias [ emal alias ]"
usageexample="inkvmailonalias john@inkisaverb.com"
hierarchy=( primary )
vsetnames=( "Email" )
vsettypes=( isEmail )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkvmailinstall )
prerequesite=( inkvmailalias )
usedby=(  )
useserfs=(  )
useconfigs=( sitemailpath )
if [ -n "infoINKonly" ] && [ "infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkvmailonalias.replace" ]; then . /opt/verb/mods/inkvmailonalias.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/inkvmailonalias.before" ]; then . /opt/verb/mods/inkvmailonalias.before; return 0; fi # Replaces this script


# Check to see if inkvmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed, not adding $domain to PFA"
  exit 0; fi

address="$1"

# Run the update
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.inkvmail.cnf -e "UPDATE alias SET active=1, modified=CURRENT_TIMESTAMP WHERE address='$address';"

# Finish
/bin/echo "Email alias $address set to active"




if [ -e "/opt/verb/mods/inkvmailonalias.after" ]; then . /opt/verb/mods/inkvmailonalias.after; fi # Follows this script
