#!/bin/bash
#inkVerbSerf! verb.ink

# This creates or resets the Nextcloud smtp user for inkvmail, such as is used by php to send emails

# How to use:
## ./inkvmailsysnextcloud

usagenotes="This creates or resets the Nextcloud smtp user for inkvmail, such as is used by php to send emails"
usageformat="inkvmailsysnextcloud"
usageexample="inkvmailsysnextcloud"
hierarchy=( tertiary installnextcloud )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkvmailinstall )
prerequesite=(  )
usedby=( installnextcloud )
useserfs=( setsecure )
useconfigs=( sitemailpath sitenameip siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkvmailsysnextcloud.replace" ]; then . /opt/verb/mods/inkvmailsysnextcloud.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/inkvmailsysnextcloud.before" ]; then . /opt/verb/mods/inkvmailsysnextcloud.before; return 0; fi # Replaces this script


# Check to see if inkvmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed. Do that first."
  exit 0; fi

# Include the config
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

# Cleanup previous entries
if [ -f "/opt/verb/conf/vsysmail.nextcloud" ]; then
  . /opt/verb/conf/vsysmail.nextcloud
  /usr/bin/rm -rf /var/inkvmail/${inkvmaildirectory}
  oldusername="${username}"
fi

# Prep all vairables
PASSWORD=$(/usr/bin/pwgen -s1 24)
randomuser=$(/usr/bin/pwgen -s1A 5)
/usr/bin/cat <<EOF > /opt/verb/conf/vsysmail.nextcloud
PASSWORD="${PASSWORD}"
user="nxc_${randomuser}"
username="nxc_${randomuser}@${nameURI}"
maildomain="${nameURI}"
name="Nextcloud ${blueURI}"
inkvmaildirectory="${nameURI}/nxc_${randomuser}/"
mailboxsize="1048576" # 1MB, 2GB=2097152000, 1GB=1048576000, 5GB=5242880000
EOF

# Security check
/opt/verb/serfs/setsecure; wait

# Disable the old entry in the database
if [ -n "${oldusername}" ]; then
  password="$(/bin/echo $PASSWORD | /usr/bin/openssl passwd -1 -stdin)"
  /usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.inkvmail.cnf -e "UPDATE mailbox
  SET username = 'nxc_${randomuser}@${nameURI}', password = '${password}', name = 'System', maildir = '${nameURI}/nxc_${randomuser}', domain = '${nameURI}', modified = CURRENT_TIMESTAMP, active = 1
  WHERE username = '${oldusername}';
  UPDATE alias
  SET address = 'nxc_${randomuser}@${nameURI}', goto = 'nxc_${randomuser}@${nameURI}', domain = '${nameURI}', modified = CURRENT_TIMESTAMP, active = 1
  WHERE address = '${oldusername}';"
fi

# Run it quick to create the account
/opt/verb/donjon/sysmails.sh nextcloud; wait
if [ "$?" != 0 ]; then
  echo "Error updating new Nextcloud mail user in databse"
  exit 6;
fi

# Set up sysmails cron
## Nextcloud background jobs (manage the crontab files directly)
/bin/echo '44 * * * * root /opt/verb/donjon/sysmails.sh nextcloud' > /etc/cron.d/sysmailnextcloud
## Permissions
/bin/chmod 0644 /etc/cron.d/sysmailnextcloud

# Mail config
/usr/bin/cat <<EOF > /srv/www/vapps/nextcloud/config/email.config.php
<?php
\$CONFIG = [
'mail_domain' => '${nameURI}',
'mail_from_address' => 'nxc_${randomuser}@${nameURI}',
'mail_smtpmode' => 'smtp',
'mail_smtphost' => 'mail.${nameURI}',
'mail_smtpport' => 587,
'mail_smtpsecure' => 'tls',
'mail_smtpauth' => true,
'mail_smtpauthtype' => 'LOGIN',
'mail_smtpname' => 'nxc_${randomuser}@${nameURI}',
'mail_smtppassword' => '${PASSWORD}',
];
EOF




if [ -e "/opt/verb/mods/inkvmailsysnextcloud.after" ]; then . /opt/verb/mods/inkvmailsysnextcloud.after; fi # Follows this script
