#!/bin/bash
#inkVerbSerf! verb.ink

# This sets the inkVPN client and server location infornation
## This can be used by itself
## If the arguments are not correctly set, the default will be used

# How to use:
## ./inkvpnlocation [ country (two-letter) ] [ province (two-letter) ] [ city ] [ organization ] [ organizational unit ]

# Eg:
## ./inkvpnlocation US MI Detroit ABC-Corp IT-Dep
## ./inkvpnlocation US IL Chicago "Rom Corp" "Fake Attack"
## ./inkvpnlocation US NY NewYork "Trumpist and Friends" "Russian Hackers"
## ./inkvpnlocation US AZ Phoenix "ABC Corp" VPN-EthHack


# Set the email variable
if [ -z "$5" ]; then
 /bin/echo "All five options not specified, OK, using defaults..."
 NEWINKVPNCOUNTR="US"
 NEWINKVPNPROVIN="CA"
 NEWINKVPNCITY="SanFrancisco"
 NEWINKVPNORG="inkVerb"
 NEWINKVPNOU="Internal-VPN"
else
 NEWINKVPNCOUNTR="$1"
 NEWINKVPNPROVIN="$2"
 NEWINKVPNCITY="$3"
 NEWINKVPNORG="$4"
 NEWINKVPNOU="$5"
fi

# Do it
/bin/sed -i "s/INKVPNCOUNTR=.*/INKVPNCOUNTR=${NEWINKVPNCOUNTR}/" /opt/verb/conf/inkvpn/inkvpnstatus
/bin/sed -i "s/INKVPNPROVIN=.*/INKVPNPROVIN=${NEWINKVPNPROVIN}/" /opt/verb/conf/inkvpn/inkvpnstatus
/bin/sed -i "s/INKVPNCITY=.*/INKVPNCITY=${NEWINKVPNCITY}/" /opt/verb/conf/inkvpn/inkvpnstatus
/bin/sed -i "s/INKVPNORG=.*/INKVPNORG=${NEWINKVPNORG}/" /opt/verb/conf/inkvpn/inkvpnstatus
/bin/sed -i "s/INKVPNOU=.*/INKVPNOU=${NEWINKVPNOU}/" /opt/verb/conf/inkvpn/inkvpnstatus

#Finish
. /opt/verb/conf/inkvpn/inkvpnstatus
/bin/echo "inkVPN Locale info now set to:
${INKVPNCOUNTR}
${INKVPNPROVIN}
${INKVPNCITY}
${INKVPNORG}
${INKVPNOU}"




if [ -e "/opt/verb/mods/inkvpnlocation.after" ]; then . /opt/verb/mods/inkvpnlocation.after; fi # Follows this script
