#!/bin/bash
#inkVerbSerf! verb.ink

# This sets a domain to 'active' in the inkvmail database

# How to use:
## ./inkvmailondomain [ domain ]

usagenotes="This sets a domain to 'active' in the inkvmail database"
usageformat="inkvmailondomain [ domain ]"
usageexample="inkvmailondomain inkisaverb.com"
hierarchy=( primary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkvmailinstall )
prerequesite=( inkvmaildomain )
usedby=(  )
useserfs=(  )
useconfigs=( sitemailpath )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkvmailondomain.replace" ]; then . /opt/verb/mods/inkvmailondomain.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/inkvmailondomain.before" ]; then . /opt/verb/mods/inkvmailondomain.before; return 0; fi # Replaces this script


# Check to see if inkvmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed, not adding $domain to PFA"
  exit 0; fi

domain="$1"

# Run the update
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.inkvmail.cnf -e "UPDATE domain SET active=1, modified=CURRENT_TIMESTAMP WHERE domain='$domain';"

# Finish
/bin/echo "Domain $domain set to active"




if [ -e "/opt/verb/mods/inkvmailondomain.after" ]; then . /opt/verb/mods/inkvmailondomain.after; fi # Follows this script
