#!/bin/bash
#inkVerbSerf! verb.ink

# This sets the inkVPN server port number
## If the port is not set in the first argument, the default "1194" will be used

# How to use:
## ./inkvpnport [ new email - optional ]


# Include the config
. /opt/verb/conf/siteurilist

# Set the default port
if [ -z "$1" ]; then
 /bin/echo "Option not specified, OK, using default..."
 NEWPORTADDR="1194"
else
 NEWPORTADDR="$1"
fi

# Disable the old port
. /opt/verb/conf/inkvpn/inkvpnstatus
/usr/bin/ufw deny ${INKVPNPORT}

# Implement the new port
/bin/sed -i "s/INKVPNPORT=.*/INKVPNPORT=${NEWPORTADDR}/" /opt/verb/conf/inkvpn/inkvpnstatus
. /opt/verb/conf/inkvpn/inkvpnstatus
/bin/sed -i "s/^port.*/port ${INKVPNPORT}/" /etc/openvpn/server.conf
/usr/bin/ufw allow from any to any port ${INKVPNPORT} proto udp
/usr/bin/ufw allow ${INKVPNPORT}
## If a client file already exists
if [ -f "/opt/openvpn/certificates/clients/client.ovpn" ]; then
/bin/sed -i "s/^remote ${hostURI}.*/remote ${hostURI} ${INKVPNPORT}/" /opt/openvpn/certificates/clients/client.ovpn
fi
## Restart the OpenVPNserver if already installed
if [ "${INKVPNINSTALLED}" = "INSTALLED_OPENVPN" ]; then
  /bin/systemctl restart openvpn@server
## Check status for the record
  if [ "$(/bin/systemctl is-active openvpn@server)" = "active" ]; then
    /bin/echo "Good to go! Systemctl check on inkVPN says \"active\"!"
  else
    /bin/echo "Something's wrong. Systemctl says OpenVPN is not active. I quit."; exit 6
  fi
fi

#Finish
/opt/verb/serfs/inkvpnclientdl
/bin/echo "inkVPN port now set to: ${NEWPORTADDR}"
