#!/bin/sh
#inkVerbSerf! verb.ink

# This creates or resets the system smtp user for inkvmail, such as is used by PHP for php to send emails

# How to use:
## ./inkvmailsysmailbox

usagenotes="This creates or resets the system smtp user for inkvmail, such as is used by PHP for php to send emails"
usageformat="inkvmailsysmailbox"
usageexample="inkvmailsysmailbox"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkvmailinstall )
prerequesite=(  )
usedby=( inkvmailinstall )
useserfs=( setsecure )
useconfigs=( sitemailpath sitenameip siteurilist )
if [ -n "infoINKonly" ] && [ "infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkvmailsysmailbox.replace" ]; then . /opt/verb/mods/inkvmailsysmailbox.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/inkvmailsysmailbox.before" ]; then . /opt/verb/mods/inkvmailsysmailbox.before; return 0; fi # Replaces this script


# Check to see if inkvmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed. Do that first."
  exit 0; fi

# Include the config
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

# Cleanup previous entries
if [ -f "/opt/verb/conf/vsysmail.phpmail" ]; then
  . /opt/verb/conf/vsysmail.phpmail
  /usr/bin/rm -rf /var/inkvmail/${inkvmaildirectory}
  oldusername="${username}"
fi

# Prep all vairables
PASSWORD=$(/usr/bin/pwgen -s1 24)
randomuser=$(/usr/bin/pwgen -s1A 5)
/usr/bin/cat <<EOF > /opt/verb/conf/vsysmail.phpmail
PASSWORD="${PASSWORD}"
user="sys_${randomuser}"
username="sys_${randomuser}@${nameURI}"
maildomain="${nameURI}"
name="System"
inkvmaildirectory="${nameURI}/sys_${randomuser}/"
mailboxsize="1048576" # 1MB, 2GB=2097152000, 1GB=1048576000, 5GB=5242880000
EOF

# Security check
/opt/verb/serfs/setsecure; wait

# Disable the old entry in the database
if [ -n "${oldusername}" ]; then
  password="$(/bin/echo $PASSWORD | /usr/bin/openssl passwd -1 -stdin)"
  /usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.inkvmail.cnf -e "UPDATE mailbox
  SET username = 'sys_${randomuser}@${nameURI}', password = '${password}', name = 'System', maildir = '${nameURI}/sys_${randomuser}', domain = '${nameURI}', modified = CURRENT_TIMESTAMP, active = 1
  WHERE username = '${oldusername}';
  UPDATE alias
  SET address = 'sys_${randomuser}@${nameURI}', goto = 'sys_${randomuser}@${nameURI}', domain = '${nameURI}', modified = CURRENT_TIMESTAMP, active = 1
  WHERE address = '${oldusername}';"
fi

# Run it quick to create the account
/opt/verb/donjon/sysmails.sh phpmail; wait
if [ "$?" != 0 ]; then
  echo "Error updating new System mail user in databse"
  exit 6;
fi

# Set up cron
/bin/echo '22 * * * * root /opt/verb/donjon/sysmails.sh phpmail' > /etc/cron.d/sysmailphp
## Permissions
/bin/chmod 0644 /etc/cron.d/sysmailphp

# Confirm the php.ini entry, comment the alternative
/bin/sed -i 's?^;sendmail_path = "/usr/sbin/sendmail -ti"?sendmail_path = "/usr/sbin/sendmail -ti"?' /opt/verb/conf/php.ini
/bin/sed -i 's?^sendmail_path = "/usr/bin/msmtp -C /etc/msmtprc -t"?;sendmail_path = "/usr/bin/msmtp -C /etc/msmtprc -t"?' /opt/verb/conf/php.ini




if [ -e "/opt/verb/mods/inkvmailsysmailbox.after" ]; then . /opt/verb/mods/inkvmailsysmailbox.after; fi # Follows this script
