#!/bin/bash
#inkVerbSerf! verb.ink

# This delets an email box in the inkvmail database

# How to use:
## ./inkvmaildelbox [ emal address ]

usagenotes="This delets an email  in the inkvmail database"
usageformat="inkvmaildelbox [ emal address ]"
usageexample="inkvmaildelbox james@inkisaverb.com"
hierarchy=( primary )
vsetnames=( "Email" )
vsettypes=( isEmail )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkvmailinstall )
prerequesite=( inkvmailbox )
usedby=(  )
useserfs=(  )
useconfigs=( sitemailpath )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkvmaildelbox.replace" ]; then . /opt/verb/mods/inkvmaildelbox.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/inkvmaildelbox.before" ]; then . /opt/verb/mods/inkvmaildelbox.before; return 0; fi # Replaces this script


# Check to see if inkvmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed, not adding $domain to PFA"
  exit 0; fi

address="$1"

# Run the update
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.inkvmail.cnf -e "DELETE FROM mailbox WHERE username='$address';"

# Finish
/bin/echo "Email address $address deleted...
The original mail should still be on the server, which you can access if you create the same email address again,
To remove any mail still on the server, use inkvmailpurgebox"




if [ -e "/opt/verb/mods/inkvmaildelbox.after" ]; then . /opt/verb/mods/inkvmaildelbox.after; fi # Follows this script
