#!/bin/sh
#inkVerbSerf! verb.ink

# This sets an email box to 'inactive' in the inkvmail database

# How to use:
## ./inkvmailoffbox [ emal address ]

usagenotes="This sets an email box to 'inactive' in the inkvmail database"
usageformat="inkvmailoffbox [ emal address ]"
usageexample="inkvmailoffbox john@inkisaverb.com"
hierarchy=( primary )
vsetnames=( "Email" )
vsettypes=( isEmail )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkvmailinstall )
prerequesite=( inkvmailbox )
usedby=(  )
useserfs=(  )
useconfigs=( sitemailpath )
if [ -n "infoINKonly" ] && [ "infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkvmailoffbox.replace" ]; then . /opt/verb/mods/inkvmailoffbox.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/inkvmailoffbox.before" ]; then . /opt/verb/mods/inkvmailoffbox.before; return 0; fi # Replaces this script


# Check to see if inkvmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed, not adding $domain to PFA"
  exit 0; fi

address="$1"

# Run the update
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.inkvmail.cnf -e "UPDATE mailbox SET active=0, modified=CURRENT_TIMESTAMP WHERE username='$address';"

# Finish
/bin/echo "Email address $address set to inactive"




if [ -e "/opt/verb/mods/inkvmailoffbox.after" ]; then . /opt/verb/mods/inkvmailoffbox.after; fi # Follows this script
