#!/bin/bash
#inkVerbSerf! verb.ink

# This purges (deletes) the inkvmail directory of an email box from the inkvmail server

# How to use:
## ./inkvmailpurgebox [ emailuser (no domain) ] [ domain ]


usagenotes="This purges (deletes) the inkvmail directory of an email box from the inkvmail server"
usageformat="inkvmailpurgebox [ emailuser (no domain) ] [ domain ]"
usageexample="inkvmailpurgebox james inkisaverb.com"
hierarchy=( primary )
vsetnames=( "Email username" "Domain" )
vsettypes=( isaz09lines isDomian )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkvmailinstall )
prerequesite=( inkvmailbox )
usedby=(  )
useserfs=(  )
useconfigs=( sitemailpath )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkvmailpurgebox.replace" ]; then . /opt/verb/mods/inkvmailpurgebox.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/inkvmailpurgebox.before" ]; then . /opt/verb/mods/inkvmailpurgebox.before; return 0; fi # Replaces this script


# Check to see if inkvmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed. Do that first."
  exit 0; fi

# Variables
emailUser="$1"
domain="$2"
inkvmaildirectory="$domain/$emailUser/"
address="$domain@$emailUser"

# Delete
/bin/rm -rf /var/inkvmail/$inkvmaildirectory

# Finish
/bin/echo "Email box $address purged from server"




if [ -e "/opt/verb/mods/inkvmailpurgebox.after" ]; then . /opt/verb/mods/inkvmailpurgebox.after; fi # Follows this script
