#!/bin/sh
#inkVerbSerf! verb.ink

# This installs roundcube
## Prerequisite: verbemail IF using a verb domain other than verb.email

# Auxiliary Prereqs...
## Prerequisite: installpostfix (so that the installer can work)
## Prerequisite: installpfa (to create the email inbox so the installer can work)
## Prerequisite: * installpostfix and installpfa and this script are included in installemail. Run installemail to meet these auxiliary prerequisites

# How to use:
## ./installrc [path folder]

# Eg:
## (To use at rc.NAME.verb.email/mysecretpath do:)
## ./installrc mysecretpath


CVAPPNAME="roundcube"
# Include the config files
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/sitemailpass
. /opt/verb/conf/sitemailpath

# Check dependencies and to see if already installed
if [ ${SITEMAILSTATUS} != "VMAIL_SERVER" ]; then
/bin/echo "
The email server must be installed first. Run: installpostfix
"
exit 8; fi
if [ ${SITERCPATH} = "RC_NOT_ALLOWED" ]; then
/bin/echo "
This is a backup email server and Roundcube is not allowed.
"
exit 0; fi
if [ ${SITERCPATH} != "RC_NOT_INSTALLED" ]; then
/bin/echo "
Roundcube is already installed.
"
exit 0; fi
if [ ${SITEMAILSTATUS} = "EMAIL_NOT_INSTALLED" ]; then
/bin/echo "
This is a backup email server and Roundcube is not allowed.
"
exit 8; fi
if /bin/grep -Fq "Webmail Defaults" /opt/verb/conf/inkdns/inkzones/db.${emailTLDURI}; then
/bin/echo "Proceeding..."; else
/bin/echo "
Webmail Defaults not declared in the DNS zone file. This won't work.
"
exit 8; fi

# Security & path
if [ -n "$1" ]; then
  export RCFOLDER=$1
else
  export RCFOLDER="$(/usr/bin/pwgen -0 5 1)"
fi
RCPASSGEN=$(/usr/bin/pwgen -s -1 5)
DESSALTGEN=$(/usr/bin/pwgen -s -1 24)

# Get inkVerb's latest and install
cd /srv/www/email
/opt/verb/serfs/inkget ${CVAPPNAME} check; wait
### Check
if [ "$?" = 4 ]; then
  /bin/echo "Repo failed to retrieve the file."
  exit 4; fi

# Create the MySQL database and user
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
CREATE DATABASE rcmail DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON rcmail.* TO 'rcmailusr'@'localhost' IDENTIFIED BY 'rcpass${RCPASSGEN}';
FLUSH PRIVILEGES;"
## Initiate the database
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf rcmail < /srv/www/email/roundcube/SQL/mysql.initial.sql

# Webserver
## Web directories
/bin/ln -sfn /srv/www/email/roundcube /srv/www/html/${SITEEMAILTLD}.rc/${RCFOLDER}
/bin/chown -R www:www /srv/www/html/${SITEEMAILTLD}.rc
## DNS
/bin/sed -i "s/; Webmail Defaults/; Webmail Defaults\nrc\.${emailTLDURI}\.\tIN  A\t\t${SITEIP}\nrc\.${emailTLDURI}\.\tIN  AAAA\t${SITEIPV6}/" /opt/verb/conf/inkdns/inkzones/db.${emailTLDURI}

# inkCert
## This adds the declared domain to the end of the "domains =" line
/bin/sed -i "/^domains =/ s/$/, rc.${emailTLDURI}/" /opt/verb/conf/inkcert/cli-ini/cli.${emailTLDURI}.ini

# Settings
/bin/cp /opt/verb/conf/lab/vmail/roundcube/mime.types /srv/www/email/roundcube/
#cp /etc/httpd/conf/mime.types /srv/www/email/roundcube/mime.types # If getting mime types from server
/bin/cp /opt/verb/conf/lab/vmail/roundcube/config/roundcube286-config.inc.php /srv/www/email/roundcube/config/config.inc.php
/bin/cp /opt/verb/conf/lab/vmail/roundcube/config/roundcube286-defaults.inc.php /srv/www/email/roundcube/config/defaults.inc.php
/bin/sed -i "s/emailTLDURI286/${emailTLDURI}/g" /srv/www/email/roundcube/config/config.inc.php
/bin/sed -i "s/emailTLDURI286/${emailTLDURI}/g" /srv/www/email/roundcube/config/defaults.inc.php
/bin/sed -i "s/nameURI286/${nameURI}/g" /srv/www/email/roundcube/config/config.inc.php
/bin/sed -i "s/nameURI286/${nameURI}/g" /srv/www/email/roundcube/config/defaults.inc.php
/bin/sed -i "s/rcpass286/rcpass${RCPASSGEN}/g" /srv/www/email/roundcube/config/config.inc.php
/bin/sed -i "s/rcpass286/rcpass${RCPASSGEN}/g" /srv/www/email/roundcube/config/defaults.inc.php
/bin/sed -i "s/rcemailconfdeskeysalt286/${DESSALTGEN}/g" /srv/www/email/roundcube/config/config.inc.php
# In the event that installpfa was run first
if [ -e "/srv/www/email/postfixadmin/config.inc.php" ]; then
/bin/sed -i "s/rcfolder286/${RCFOLDER}/g" /srv/www/email/postfixadmin/config.inc.php
fi

# Copy the branding files
/bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/verbink_logo.png /srv/www/email/roundcube/
/bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/elastic/images/logo.svg /srv/www/email/roundcube/skins/elastic/images/
/bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/elastic/images/favicon.ico /srv/www/email/roundcube/skins/elastic/images/
/bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/favicon.ico /srv/www/email/roundcube/
/bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/larry/images/verbink_logo.png /srv/www/email/roundcube/skins/larry/images/
/bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/larry/images/watermark.jpg /srv/www/email/roundcube/skins/larry/images/
/bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/larry/images/favicon.ico /srv/www/email/roundcube/skins/larry/images/

# Own
/bin/chown -R www:www /srv/www/email/roundcube

# Set the config for backup
/bin/sed -i "s/SITERCPASSAPG.*/SITERCPASSAPG=\"${RCPASSGEN}\"/g" /opt/verb/conf/sitemailpass
/bin/sed -i "s/SITERCPATH.*/SITERCPATH=\"${RCFOLDER}\"/g" /opt/verb/conf/sitemailpath

# Set up plugins that Composer broke
cd /srv/www/email/roundcube/plugins/
if [ ! -d "/srv/www/email/roundcube/plugins/authres_status" ]; then
/bin/cp /opt/verb/conf/lab/vmail/roundcube/authres_status.vtxz .
/opt/verb/serfs/vtxzout authres_status; wait; fi
if [ ! -d "/srv/www/email/roundcube/plugins/contextmenu" ]; then
/bin/cp /opt/verb/conf/lab/vmail/roundcube/contextmenu.vtxz .
/opt/verb/serfs/vtxzout contextmenu; wait; fi

# Sledgehammertime (Composer plugins)
## Download Composer
cd /srv/www/email/roundcube
/usr/bin/curl -s https://getcomposer.org/installer | php
/bin/cp composer.json-dist composer.json
## Plugins
/bin/sed -i '/\"require\": {/ a\
        \"angrychimp\/php-dkim\": \"dev-master\",' composer.json
/bin/sed -i '/\"require\": {/ a\
        \"roundcube\/authres_status\": \"dev-master",' composer.json
/bin/sed -i '/\"require\": {/ a\
        \"cor\/keyboard_shortcuts\": \"dev-master\",' composer.json
/bin/sed -i '/\"require\": {/ a\
        \"johndoh\/markasjunk2\": \"dev-master\",' composer.json
/bin/sed -i '/\"require\": {/ a\
        \"kitist\/html5_notifier\": \"dev-master\",' composer.json
/bin/sed -i '/\"require\": {/ a\
        \"elm\/identity_smtp\": \"dev-master\",' composer.json
## Run the Composer installation
### Ignore requirements that trip false warnings: --ignore-platform-req=
### Use the www user so changes can be made to the web directory
/usr/bin/su www -c 'php composer.phar install -n --ignore-platform-req=php --ignore-platform-req=ext-gd --ignore-platform-req=ext-ldap'

# Fool RoundCube into accepting current versions of PHP
/bin/sed -i "s/if (PHP_VERSION_ID >= .*/if (PHP_VERSION_ID >= 90000) {/" /srv/www/email/roundcube/program/include/iniset.php

# Remove the installer so it is ready to go
/opt/verb/serfs/postinstallrc

# Finished
/bin/echo "
Roundcube installed and can be accessed at: https://rc.${emailTLDURI}/${RCFOLDER}
"
