#!/bin/bash
#inkVerbSerf! verb.ink

# This installs postfix admin
## PostfixAdmin setup secure option: use "secure" for a password required, otherwise anything else including empty
## If using 'secure', you must set the hash via setpfapass
## Prerequisite: verbemail IF using a verb domain other than verb.email
## Prerequisite: inkvmailinstall, installrc

# How to use:
## ./installpfa [path folder] [setup password option]

# Eg: (To use at pfa.NAME.verb.email/mysecretpath do:)
## ./installpfa mysecretpath
## ./installpfa mysecretpath somepassword


CVAPPNAME="postfixadmin"
# Include the config files
. /opt/verb/conf/servertype
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/sitemailpass
. /opt/verb/conf/sitemailpath

# Check dependencies and to see if already installed
if [ ${SITEMAILSTATUS} != "VMAIL_SERVER" ]; then
/bin/echo "
The email server must be installed first. Run: installpostfix
"
exit 8; fi
if [ ${SITEPFAPATH} = "PFA_NOT_ALLOWED" ]; then
/bin/echo "
This is a backup email server and PostfixAdmin is not allowed.
"
exit 0; fi
if [ ${SITEPFAPATH} != "PFA_NOT_INSTALLED" ]; then
/bin/echo "
PostfixAdmin is already installed.
"
exit 0; fi
if /bin/grep -Fq "Email Control Records" /opt/verb/conf/inkdns/inkzones/db.${emailTLDURI}; then
/bin/echo "Proceeding..."; else
/bin/echo "
Email Control Records not declared in the DNS zone file. This won't work.
"
exit 8; fi

# Options & secure path
if [ -n "$1" ]; then
  export PFAFOLDER=$1 # We need this variable in our Finish echo statement when running via inkvmailinstall
else
  export PFAFOLDER="$(/usr/bin/pwgen -0 5 1)" # We need this variable in our Finish echo statement when running via inkvmailinstall
fi
if [ -n "$2" ]; then
  export PFAPASS=$2 # We need this variable in our Finish echo statement when running via inkvmailinstall
else
  export PFAPASS="$(pwgen -1Bcn 10)" # We need this variable in our Finish echo statement when running via inkvmailinstall
fi

# Download from repo
cd /srv/www/email
/opt/verb/serfs/inkget ${CVAPPNAME} check; wait
if [ "$?" = 4 ]; then
  /bin/echo "Repo failed to retrieve the file."
  exit 4; fi

## Fix a bug
/bin/mkdir -p /srv/www/email/postfixadmin/templates_c

# Copy the branding files
/bin/cp /opt/verb/conf/lab/inkvmail/postfixadmin/pfapics/images/logo-ink.png /srv/www/email/postfixadmin/public/images/

# Settings
/usr/bin/cp /opt/verb/conf/lab/inkvmail/postfixadmin/postfixadmin286-config.local.php /srv/www/email/postfixadmin/config.local.php
/bin/sed -i "s/emailTLDURI286/${emailTLDURI}/g" /srv/www/email/postfixadmin/config.local.php
/bin/sed -i "s/nameURI286/${nameURI}/g" /srv/www/email/postfixadmin/config.local.php
/bin/sed -i "s/mailpassword/mailpass${SITEMAILPASSAPG}/g" /srv/www/email/postfixadmin/config.local.php
/bin/sed -i "s/rcfolder286/${SITERCPATH}/g" /srv/www/email/postfixadmin/config.local.php
/bin/sed -i "s/pfafolder286/${PFAFOLDER}/g" /srv/www/email/postfixadmin/config.local.php
## Whether web-generated (secure) or auto-generated password
/opt/verb/serfs/setpfapass ${PFAPASS}

# Replace
/bin/sed -i "s/emailTLDURI286/${emailTLDURI}/g" /srv/www/email/postfixadmin/config.local.php
/bin/sed -i "s/nameURI286/${nameURI}/g" /srv/www/email/postfixadmin/config.local.php
/bin/sed -i "s/mailpassword/mailpass${SITEMAILPASSAPG}/g" /srv/www/email/postfixadmin/config.local.php
/bin/sed -i "s/rcfolder286/${SITERCPATH}/g" /srv/www/email/postfixadmin/config.local.php
/bin/sed -i "s/pfafolder286/${PFAFOLDER}/g" /srv/www/email/postfixadmin/config.local.php

# Copy the branding files
/bin/cp /opt/verb/conf/lab/inkvmail/postfixadmin/pfapics/images/logo-ink.png /srv/www/email/postfixadmin/public/images/
/bin/cp /opt/verb/conf/lab/inkvmail/postfixadmin/pfapics/images/favicon-ink.ico /srv/www/email/postfixadmin/public/images/

# Webserver
/usr/bin/mkdir -p /srv/www/verb/${SITEEMAILTLD}.pfa
/bin/ln -sfn /srv/www/email/postfixadmin/public /srv/www/verb/${SITEEMAILTLD}.pfa/${PFAFOLDER}; wait
/bin/chown -R www:www /srv/www/verb/${SITEEMAILTLD}.pfa; wait
/bin/chown -R www:www /srv/www/email/postfixadmin; wait
## Hosting conf
if [ ${SERVERTYPE} = "laemp" ]; then
  /bin/cp /opt/verb/conf/site-files/conf/pfa-nginx.conf /opt/verb/conf/webserver/nginx/sites-available/pfa.${emailTLDURI}.conf
  /bin/cp /opt/verb/conf/site-files/conf/pfa-httpd.conf /opt/verb/conf/webserver/httpd/sites-available/pfa.${emailTLDURI}.conf
  /opt/verb/serfs/ensitenginx pfa.${emailTLDURI}
  /opt/verb/serfs/ensiteapache pfa.${emailTLDURI}
  /usr/bin/systemctl restart nginx; wait
  /usr/bin/systemctl restart httpd; wait
elif [ ${SERVERTYPE} = "lemp" ]; then
  /bin/cp /opt/verb/conf/site-files/conf/pfa-nginx.conf /opt/verb/conf/webserver/nginx/sites-available/pfa.${emailTLDURI}.conf
  /opt/verb/serfs/ensitenginx pfa.${emailTLDURI}
  /usr/bin/systemctl restart nginx; wait
elif [ ${SERVERTYPE} = "lamp" ]; then
  /bin/cp /opt/verb/conf/site-files/conf/pfa-httpd.conf /opt/verb/conf/webserver/httpd/sites-available/pfa.${emailTLDURI}.conf
  /opt/verb/serfs/ensiteapache pfa.${emailTLDURI}
  /usr/bin/systemctl restart httpd; wait
fi

# Add inkCert certs to the web server config
/opt/verb/serfs/inkcertaddle pfa.${emailTLDURI} ${emailTLDURI}

# DNS
/bin/sed -i "s/; Email Control Records/; Email Control Records\npfa.${emailTLDURI}. \tIN  A \t${SITEIPV4}\npfa.${emailTLDURI}. \tIN  AAAA \t${SITEIPV6}/" /opt/verb/conf/inkdns/inkzones/db.${emailTLDURI}
/bin/sed -i "s/; Email Control Records/; Email Control Records\n${SITEARPAIP4} \tIN  PTR \tpfa.${emailTLDURI}.\n${SITEARPAIP6} \tIN  PTR \tpfa.${emailTLDURI}./" /opt/verb/conf/inkdns/inkzones/nv.${emailTLDURI}

# Write the config
/bin/sed -i "s/SITEPFAPATH.*/SITEPFAPATH=\"${PFAFOLDER}\"/g" /opt/verb/conf/sitemailpath

# Finish
/bin/echo "
Postfix Admin is installed and ready to be set up.

For setup, note:
- Use the install password '${PFAPASS}'

Set up all this at:
 https://pfa.${emailTLDURI}/${PFAFOLDER}/setup.php
- Then run ./postinstallpfa
"




if [ -e "/opt/verb/mods/installpfa.after" ]; then . /opt/verb/mods/installpfa.after; fi # Follows this script
