#!/bin/bash
#inkVerbSerf! verb.ink

# This installs SpamAssassin with ClamAV and Razor, integrated with Postfix and Dovecot
## This is intended to be used only by installpostfixvmail and not used by itself
## This is in separate development because ClamAV can be quirky

# How to use:
## ./installspamassassin


# SpamAssassin
/usr/bin/mkdir -p /var/lib/dovecot/sieve/global_sieves /etc/mail/sa-update-keys
/usr/bin/chown -R spamd:spamd /etc/mail/sa-update-keys
/usr/bin/sudo -u spamd /usr/bin/vendor_perl/sa-update
/usr/bin/sudo -u spamd /usr/bin/vendor_perl/sa-compile
## Dovecot integration
/usr/bin/cat <<EOF > /var/lib/dovecot/sieve/global_sieves/move_to_spam_folder.sieve
require "spamtestplus";
require "fileinto";
require "relational";
require "comparator-i;ascii-numeric";

if spamtest :value "ge" :comparator "i;ascii-numeric" "5" {
  fileinto "Junk";
}
EOF
/usr/bin/ln -sfn /usr/bin/vendor_perl/spamc /etc/dovecot/sieve-filter/spamc
#DEV why is this EOFdoc here? Delete if everything works
#/usr/bin/cat <<EOF > /etc/dovecot/sieve.before.d/spamassassin.sieve
#  require [ "vnd.dovecot.filter" ];
#  filter "spamc" [ "-d", "127.0.0.1", "--no-safe-fallback" ];
#EOF
## Compile the Dovecot Sieve rules
/usr/bin/sievec /var/lib/dovecot/sieve/global_sieves
## Service
/usr/bin/cat <<EOF > /etc/systemd/system/spamassassin-update.service
[Unit]
Description=spamassassin housekeeping stuff
After=network.target

[Service]
Type=oneshot

ExecStart=sudo -u spamd /usr/bin/vendor_perl/sa-update --allowplugins
SuccessExitStatus=1
ExecStart=sudo -u spamd /usr/bin/vendor_perl/sa-compile
ExecStart=/usr/bin/systemctl -q --no-block try-restart spamassassin.service
EOF
/usr/bin/cat <<EOF > /etc/systemd/system/spamassassin-update.timer
[Unit]
Description=spamassassin house keeping

[Timer]
OnCalendar=daily
Persistent=true

[Install]
WantedBy=timers.target
EOF
/usr/bin/systemctl enable spamassassin.service; wait
/usr/bin/systemctl start spamassassin.service; wait
/usr/bin/systemctl enable spamassassin-update.timer; wait
/usr/bin/systemctl start spamassassin-update.timer; wait

# ClamAV
## Create config files
/bin/cp /opt/verb/conf/lab/vmail/clamav/clamav.cf /etc/mail/spamassassin/
/bin/cp /opt/verb/conf/lab/vmail/clamav/clamav.pm /etc/mail/spamassassin/
## Uses the package perl-cpanplus-dist-arch, which we installed
/usr/bin/chmod 755 /var/lib/clamav
/usr/bin/chown -R clamav:clamav /var/lib/clamav
/usr/bin/touch /run/clamav/clamd.ctl
/usr/bin/chown clamav:clamav /run/clamav/clamd.ctl
/usr/bin/killall freshclam 2>/dev/null
/usr/bin/freshclam
#/usr/bin/vendor_perl/cpanp -i File::Scan::ClamAV; wait
# echo "y" to ignore an error
/usr/bin/echo "y" | /usr/bin/vendor_perl/cpanp -i File::Scan::ClamAV; wait
## Service
/usr/bin/systemctl enable clamav-daemon.service
/usr/bin/systemctl start clamav-daemon.service
/usr/bin/systemctl restart spamassassin.service

# Razor
/usr/bin/mkdir -p /etc/mail/spamassassin/razor
/usr/bin/chown spamd:spamd /etc/mail/spamassassin/razor
cd /etc/mail/spamassassin/razor
/usr/bin/sudo -u spamd razor-admin -home=/etc/mail/spamassassin/razor -register
/usr/bin/sudo -u spamd razor-admin -home=/etc/mail/spamassassin/razor -create
/usr/bin/sudo -u spamd razor-admin -home=/etc/mail/spamassassin/razor -discover
cd $OLDPWD


#### original, for reference, delete when everything works
exit

## SpamAssassin
/usr/bin/mkdir -p /var/lib/dovecot/sieve/global_sieves /etc/mail/sa-update-keys
/usr/bin/chown spamd:spamd /etc/mail/sa-update-keys
/usr/bin/sudo -u spamd /usr/bin/vendor_perl/sa-update
/usr/bin/sudo -u spamd /usr/bin/vendor_perl/sa-compile
/usr/bin/cat <<EOF > /var/lib/dovecot/sieve/global_sieves/move_to_spam_folder.sieve
require "spamtestplus";
require "fileinto";
require "relational";
require "comparator-i;ascii-numeric";

if spamtest :value "ge" :comparator "i;ascii-numeric" "5" {
  fileinto "Junk";
}
EOF
/usr/bin/ln -s /usr/bin/vendor_perl/spamc /etc/dovecot/sieve-filter/spamc
/usr/bin/cat <<EOF > /etc/dovecot/sieve.before.d/spamassassin.sieve
  require [ "vnd.dovecot.filter" ];
  filter "spamc" [ "-d", "127.0.0.1", "--no-safe-fallback" ];
EOF
### Compile the rules
/usr/bin/sievec /etc/dovecot/sieve.before.d/spamassassin.sieve
### SpamAssassin service & timer
/usr/bin/cat <<EOF > /etc/systemd/system/spamassassin-update.service
[Unit]
Description=spamassassin housekeeping stuff
After=network.target

[Service]
Type=oneshot

ExecStart=sudo -u spamd /usr/bin/vendor_perl/sa-update --allowplugins
SuccessExitStatus=1
ExecStart=sudo -u spamd /usr/bin/vendor_perl/sa-compile
ExecStart=/usr/bin/systemctl -q --no-block try-restart spamassassin.service
EOF
/usr/bin/cat <<EOF > /etc/systemd/system/spamassassin-update.timer
[Unit]
Description=spamassassin house keeping

[Timer]
OnCalendar=daily
Persistent=true

[Install]
WantedBy=timers.target
EOF
/usr/bin/systemctl enable spamassassin.service
/usr/bin/systemctl start spamassassin.service
/usr/bin/systemctl enable spamassassin-update.timer
/usr/bin/systemctl start spamassassin-update.timer
### Old
# Spamassassin likes to be finickey. Sometimes it needs this on update or whenever...
#sa-update -v

## ClamAV
### DEV This is broken, figure out a way to fix it
# Install ClamAV (after installing perl-cpanplus-dist-arch, which we did)
/usr/bin/freshclam
/usr/bin/vendor_perl/cpanp -i File::Scan::ClamAV; wait
/bin/cp /opt/verb/conf/lab/vmail/clamav/clamav.cf /etc/mail/spamassassin/
/bin/cp /opt/verb/conf/lab/vmail/clamav/clamav.pm /etc/mail/spamassassin/
/usr/bin/systemctl enable clamav-daemon.service
/usr/bin/systemctl start clamav-daemon.service
### Old
#killall freshclam 2>/dev/null
#freshclam
