#!/bin/bash
#inkVerbSerf! verb.ink

# This installs postfix admin
## PostfixAdmin setup secure option: use "secure" for a password required, otherwise anything else including empty
## If using 'secure', you must set the hash via setpfapass
## Prerequisite: verbemail IF using a verb domain other than verb.email
## Prerequisite: installpostfixvmail, installrc

#DEV This is broken, if deleted, also delete:
#inst/webserver/laemp-conf/pfa-nginx.conf
#inst/webserver/laemp-conf/pfa-httpd.conf
#inst/webserver/lamp-conf/pfa-httpd.conf
#inst/webserver/lemp-conf/pfa-nginx.conf

# How to use:
## ./installpfa [path folder] [setup password option]

# Eg: (To use at pfa.NAME.verb.email/mysecretpath do:)
## ./installpfa mysecretpath
## ./installpfa mysecretpath somepassword


CVAPPNAME=postfixadmin
# Include the config files
. /opt/verb/conf/servertype
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/sitemailpass
. /opt/verb/conf/sitemailpath

# Check dependencies and to see if already installed
if [ ${SITEMAILSTATUS} != "VMAIL_SERVER" ]; then
/bin/echo "
The email server must be installed first. Run: installpostfix
"
exit 8; fi
if [ ${SITEPFAPATH} = "PFA_NOT_ALLOWED" ]; then
/bin/echo "
This is a backup email server and PostfixAdmin is not allowed.
"
exit 0; fi
if [ ${SITEPFAPATH} != "PFA_NOT_INSTALLED" ]; then
/bin/echo "
PostfixAdmin is already installed.
"
exit 0; fi
if /bin/grep -Fq "Webmail Defaults" /opt/verb/conf/inkdns/inkzones/db.${emailTLDURI}; then
/bin/echo "Proceeding..."; else
/bin/echo "
Webmail Defaults not declared in the DNS zone file. This won't work.
"
exit 8; fi

# Options & secure path
if [ -n "$1" ]; then
PFAFOLDER=$1
else
PFAFOLDER="$(/usr/bin/pwgen -0 5 1)"
fi
PFAPASS=$2

# Install package
/usr/bin/pacman -S --noconfirm postfixadmin php-imap

# Directories
## Generate a symlink for the Verber
/usr/bin/ln -sfn /etc/webapps/postfixadmin /srv/www/email/
## Fix a bug?
#/bin/mkdir -p /srv/www/email/postfixadmin/templates_c

# Settings
/usr/bin/cp /opt/verb/conf/lab/vmail/postfixadmin/postfixadmin286-config.inc.php /etc/webapps/postfixadmin/config.local.php
## Whether web-generated (secure) or auto-generated password
if [ "${PFAPASS}" != "secure" ]; then
  export INSTPASS="$(pwgen -1Bcn 10)" # We need this variable in our Finish echo statement when running via installpostfixvmail
  INSTPASS="ePhaeM4kie"
  INSTHASH="$(php -r "echo password_hash('${INSTPASS}', PASSWORD_DEFAULT);")"
  /bin/sed -i "s/\$CONF\['configured'\] = .*/\$CONF\['configured'\] = true;/g" /srv/www/email/postfixadmin/config.local.php
  /bin/sed -i "s/^\$CONF\['setup_password'\] = /#\$CONF\['setup_password'\] = /g" /srv/www/email/postfixadmin/config.local.php
  cat <<EOF >> /srv/www/email/postfixadmin/config.local.php
\$CONF['setup_password'] = '${INSTHASH}';
EOF
fi

# Replace
/bin/sed -i "s/emailTLDURI286/${emailTLDURI}/g" /srv/www/email/postfixadmin/config.local.php
/bin/sed -i "s/nameURI286/${nameURI}/g" /srv/www/email/postfixadmin/config.local.php
/bin/sed -i "s/mailpassword/mailpass${SITEMAILPASSAPG}/g" /srv/www/email/postfixadmin/config.local.php
/bin/sed -i "s/rcfolder286/${SITERCPATH}/g" /srv/www/email/postfixadmin/config.local.php
/bin/sed -i "s/pfafolder286/${PFAFOLDER}/g" /srv/www/email/postfixadmin/config.local.php

# Copy the branding files
/bin/cp /opt/verb/conf/lab/vmail/postfixadmin/pfapics/images/logo-ink.png /usr/share/webapps/postfixadmin/public/images/

# Webserver
## Web directories
/bin/cp -R /srv/www/html/0ne /srv/www/html/${SITEEMAILTLD}.pfa; wait
/bin/chown -R www:www /srv/www/html/${SITEEMAILTLD}.pfa; wait
/bin/ln -sfn /usr/share/webapps/postfixadmin/public /srv/www/html/${SITEEMAILTLD}.pfa/${PFAFOLDER}; wait
## DNS
/bin/sed -i "s/; Webmail Defaults/; Webmail Defaults\npfa\.${emailTLDURI}\.\tIN  A\t\t${SITEIP}\npfa\.${emailTLDURI}\.\tIN  AAAA\t${SITEIPV6}/" /opt/verb/conf/inkdns/inkzones/db.${emailTLDURI}
## PHP-FPM
/usr/bin/cat <<EOF > /etc/php/php-fpm.d/postfixadmin.conf
[postfixadmin]
user = postfixadmin
group = postfixadmin
listen = /run/postfixadmin/postfixadmin.sock
listen.owner = root
listen.group = http
listen.mode = 0660
pm = ondemand
pm.max_children = 4
php_admin_value['date.timezone'] = Europe/Berlin
php_admin_value['session.save_path'] = /tmp
php_admin_value['open_basedir'] = /tmp/:/usr/share/webapps/postfixadmin/:/etc/webapps/postfixadmin/:/usr/bin/doveadm:/var/cache/postfixadmin
EOF
## Server type
if [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lamp" ]; then
  /usr/bin/mv /opt/verb/conf/webserver/httpd/sites-available/pfa.${emailTLDURI}.conf /opt/verb/conf/webserver/httpd/sites-available/pfa.${emailTLDURI}.conf.old
  /usr/bin/cp /opt/verb/conf/site-files/conf/pfa.conf /opt/verb/conf/webserver/httpd/sites-available/pfa.${emailTLDURI}.conf
  /opt/verb/serfs/ensiteapache pfa.${emailTLDURI}
elif [ ${SERVERTYPE} = "lemp" ]; then
  /usr/bin/mv /opt/verb/conf/webserver/nginx/sites-available/pfa.${emailTLDURI}.conf /opt/verb/conf/webserver/nginx/sites-available/pfa.${emailTLDURI}.conf.old
  /usr/bin/cp /opt/verb/conf/site-files/conf/pfa.conf /opt/verb/conf/webserver/nginx/sites-available/pfa.${emailTLDURI}.conf
  /opt/verb/serfs/ensitenginx pfa.${emailTLDURI}
fi

# Write the config
/bin/sed -i "s/SITEPFAPATH.*/SITEPFAPATH=\"${PFAFOLDER}\"/g" /opt/verb/conf/sitemailpath

# Setup for inkCert
. /opt/verb/conf/inkcert/cli-ini/siteinkcert.${emailTLDURI} ${emailTLDURI}
case ${INKCERTED} in
  DONE_SC)
  /opt/verb/serfs/inkcertaddsc pfa.${emailTLDURI} ${emailTLDURI}
  ;;
  DONE_IC)
  /opt/verb/serfs/inkcertadd pfa.${emailTLDURI} ${emailTLDURI}
  ;;
  DONE_LE)
  /opt/verb/serfs/inkcertaddle pfa.${emailTLDURI} ${emailTLDURI}
  ;;
  DONE_CB)
  /opt/verb/serfs/inkcertaddcb pfa.${emailTLDURI} ${emailTLDURI}
  ;;
  NO|NOT_YET)
    /bin/echo "Nextcloud is currently using Snakeoil certs, ready for inkCert"
  ;;
  *)
    if ! /bin/grep -q "INKCERTED=NO" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${DOMAIN}; then
      /bin/echo "Something's wrong with the inkCert siteinkcert configs! Aborting"
      exit 6
    else
      /bin/echo "Nextcloud is currently using Snakeoil certs, ready for inkCert"
    fi
  ;;
esac

# Webserver restart
if [ ${SERVERTYPE} = "laemp" ]; then
  /usr/bin/systemctl restart nginx; wait
  /usr/bin/systemctl restart httpd; wait
elif [ ${SERVERTYPE} = "lemp" ]; then
  /usr/bin/systemctl restart nginx; wait
elif [ ${SERVERTYPE} = "lamp" ]; then
  /usr/bin/systemctl restart httpd; wait
fi
/usr/bin/systemctl restart php-fpm; wait

# Finish
/bin/echo "
Postfix Admin is installed and ready to be set up.

For setup, note:
- Use the install password '${INSTPASS}'

Set up all this at:
 https://pfa.${emailTLDURI}/${PFAFOLDER}/setup.php
- Then run ./postinstallpfa
"
