#!/bin/sh
#inkVerbSerf! verb.ink

# This installs vsftpd and prepares it for use according to newftpvip, delftpvip, newftpfiler, and delftpfiler scripts
# This is a prereqisite for ftpvips and ftpfilers and net2ftp

## THIS HAS EXPIRIMENTAL LINES. Remove commented lines if it works.

# How to use:
## ./installvsftpd


# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

/usr/bin/apt-get install vsftpd

# Allow users to upload
/bin/sed -i "s/#write_enable=YES/write_enable=YES/g" /etc/vsftpd.conf

# Limit users to their respective directories
/bin/sed -i "s/#chroot_local_user=YES/chroot_local_user=YES/g" /etc/vsftpd.conf

/bin/echo "# Added by inkVerb with respect to above chroot_local_user=YES also uncommented" >> /etc/vsftpd.conf
/bin/echo "chroot_list_enable=NO" >> /etc/vsftpd.conf

# Set the umask to the normal 022
/bin/sed -i "s/#local_umask=022/local_umask=022/g" /etc/vsftpd.conf

# Set the listening port to 2121
## Commented, may not be necessary given ufw config
#/bin/echo "listen_port=2121" >> /etc/vsftpd.conf

# Set the branding
/bin/sed -i "s/#ftpd_banner=Welcome to blah FTP service\./ftpd_banner=inkVerb FTP, get inking.../g" /etc/vsftpd.conf

# Enable SSL
## Comment the snakeoil settings
/bin/sed -i "s/rsa_cert_file=\/etc\/ssl\/certs\/ssl-cert-snakeoil\.pem/#rsa_cert_file=\/etc\/ssl\/certs\/ssl-cert-snakeoil\.pem/g" /etc/vsftpd.conf
/bin/sed -i "s/rsa_private_key_file=\/etc\/ssl\/private\/ssl-cert-snakeoil\.key/#rsa_private_key_file=\/etc\/ssl\/private\/ssl-cert-snakeoil\.key/g" /etc/vsftpd.conf
## Allow the inkCert certs
/bin/echo "ssl_enable=Yes" >> /etc/vsftpd.conf
/bin/echo "rsa_cert_file=/etc/inkcert/live/${nameURI}/cert.pem" >> /etc/vsftpd.conf
/bin/echo "rsa_private_key_file=/etc/inkcert/live/${nameURI}/privkey.pem" >> /etc/vsftpd.conf
## The line below is expirimental based on info from http://vsftpd.beasts.org/vsftpd_conf.html
/bin/echo "ca_certs_file=/etc/inkcert/live/${nameURI}/chain.pem" >> /etc/vsftpd.conf

# Put the default ftp user to another directory
/bin/mkdir /srv/vsftpd
/bin/mkdir /srv/vsftpd/ftp
usermod -d /srv/vsftpd/ftp ftp

# Start the service
## This is expirimental
/bin/systemctl start vsftpd

# Restart
## Former is commented, new is expirimental and may be redundant
/bin/systemctl reload vsftpd
#restart vsftpd

# Set the firewall to allow the site port
. /opt/verb/conf/siteport
/usr/bin/ufw allow from any to any port ${SITEPORT}

