#!/bin/sh
#inkVerbSerf! verb.ink

# This installs Odoo 10 as an app to be connected to odoo.your-name.verb.red

# How to use:
## ./installodoo10


CVAPPNAME=odoo.red

# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

# Check for existing Odoo
. /opt/verb/conf/siteinstallstatus
if [ "${REDodoo}" != "NOT_YET" ]; then
/bin/echo "${REDodoo} is already installed at odoo.${redURI}.
It's all been done."
exit 0; fi

# Debian Install
## Based on http://www.odoo.com/documentation/10.0/setup/install.html#setup-install-packaged
/usr/bin/wget -O - https://nightly.odoo.com/odoo.key | /usr/bin/apt-key add -
/bin/echo "deb http://nightly.odoo.com/10.0/nightly/deb/ ./" >> /etc/apt/sources.list.d/odoo.list
/usr/bin/apt-get update -y --fix-missing && /usr/bin/apt-get install -y odoo

# Set UFW to allow the Odoo port
## HTTP
/usr/bin/ufw allow 8069
## TCP
/usr/bin/ufw allow 8072

# Apache
## Remove static-Apache html folder
/bin/rm -rf /srv/www/html/red.odoo
/bin/echo "Odoo 10" > /srv/www/html/red.odoo
## Set the IP address in the Apache config file
/bin/cp -f /opt/verb/conf/site-files/conf/odoo-odoo.${redURI}.conf /opt/verb/conf/webserver/httpd/sites-available/odoo.${redURI}.conf
/bin/sed -i "s/ip286/${SITEIP}/g" /opt/verb/conf/webserver/httpd/sites-available/odoo.${redURI}.conf
/usr/bin/apachectl graceful
## inkCert SSL certs
### Not setup
if /bin/grep -Fq "INKCERTED=NO" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${redURI}; then
/bin/echo "FYI: inkCert is not yet setup for ${redURI}."
fi
### inkCert-LE DONE
if /bin/grep -Fq "INKCERTED=DONE_LE" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${redURI}; then
/bin/echo "inkCert-LE is already setup for ${redURI}. Updating the Apache configs..."
/opt/verb/serfs/inkcertaddle odoo.${redURI}
wait
fi
### inkCert-IC DONE
if /bin/grep -Fq "INKCERTED=DONE_IC" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${redURI}; then
/bin/echo "inkCert-IC is already setup for ${inkURI}. Updating the Apache configs..."
/opt/verb/serfs/inkcertadd odoo.${redURI}
wait
fi

# Set the site-wide app-install config
/bin/sed -i "s/REDodoo=.*/REDodoo=\"Odoo10\"/g" /opt/verb/conf/siteinstallstatus

# Write the config for backup
/bin/echo "#!/bin/sh
Odoo was installed as red.
" > /opt/verb/conf/vapp.${CVAPPNAME}

# Record the port in the Odoo port inklist
/bin/echo "odoo.${redURI} 8069" >> /opt/verb/conf/inklists/odoositeports

# Finish
/bin/echo "Odoo is setup.
Go to http://odoo.${redURI} to install."
