#!/bin/sh
#inkVerbSerf! verb.ink

# This downloads and installs WordPress to bb.NAME.verb.ink
## WordPress actually resides in www/vapps/wp.inkbb

# All options are optional, but must are sequential, omit last options first.

# How to use:
## ./installwpinkbb [dbase] [dbuser] [dbpassword]


CVAPPNAME=wp.inkbb
# "wp" is the normal app, so it must be specified when retrieving from the repo

# Include the config
. /opt/verb/conf/siteurilist

DBASE=$1
DBUSER=$2
DBPASSWORD=$3
CLEANNAME=$(/bin/echo $CVAPPNAME | sed -e 's/\.//g')

# Check for existing inkbb
. /opt/verb/conf/siteinstallstatus
if [ "${INKbb}" != "NOT_YET" ]; then
/bin/echo "Um... How do I say this...
Your blog at bb.${inkURI} already has ${INKblog} installed. This just isn't going to work.
"
exit 0
fi

# Download and establish wordpress in the server to pre-created domain
cd /srv/www/vapps
/opt/verb/serfs/inkget wp check; wait
if [ "$?" = 4 ]; then
/bin/echo "Repo failed to retrieve the file."
exit 4; fi
if [ ! -f wp.vtxz ]; then

# Auto database
if [ -z ${3} ]; then
DBPASSWORD=$(/usr/bin/pwgen -s -1 10); fi
if [ -z ${1} ]; then
DBASE=${CLEANNAME}$(/usr/bin/pwgen -s -1 6); fi
if [ -z ${2} ]; then
DBUSER=${DBASE}; fi

/bin/mv wp ${CVAPPNAME}; wait
/opt/verb/serfs/setvapplinkon ${CVAPPNAME}; wait
/bin/ln -sfn /srv/www/html/ink.bb /srv/vip/_webapps/; wait
/bin/chown -R www:www /srv/www/html/ink.bb; wait
/bin/chown -R www:www /srv/www/vapps/${CVAPPNAME}; wait

# Create the database and credentials
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
CREATE DATABASE  ${DBASE};
GRANT ALL PRIVILEGES ON ${DBASE}.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}';
FLUSH PRIVILEGES;"

# Write the config for backup
/bin/echo "#!/bin/sh
APPDBASE=${DBASE}
APPDDBUSR=${DBUSER}
APPDDBPAS=${DBPASSWORD}" > /opt/verb/conf/vapp.${CVAPPNAME}

# Put the settings in the WordPress config file
cd ${CVAPPNAME}
/bin/cp wp-config-sample.php wp-config.php
/bin/sed -i "s/database_name_here/${DBASE}/g" wp-config.php
/bin/sed -i "s/username_here/${DBUSER}/g" wp-config.php
/bin/sed -i "s/password_here/${DBPASSWORD}/g" wp-config.php

# Add the secure salt and key strings
AUTH_KEY=$(/usr/bin/pwgen -s -1 27)
SECURE_AUTH_KEY=$(/usr/bin/pwgen -s -1 27)
LOGGED_IN_KEY=$(/usr/bin/pwgen -s -1 27)
NONCE_KEY=$(/usr/bin/pwgen -s -1 27)
AUTH_SALT=$(/usr/bin/pwgen -s -1 27)
SECURE_AUTH_SALT=$(/usr/bin/pwgen -s -1 27)
LOGGED_IN_SALT=$(/usr/bin/pwgen -s -1 27)
NONCE_SALT=$(/usr/bin/pwgen -s -1 27)
/bin/sed -i "s/define( 'AUTH_KEY',         .*/define( 'AUTH_KEY',         '${AUTH_KEY}' );/g" wp-config.php
/bin/sed -i "s/define( 'SECURE_AUTH_KEY',  .*/define( 'SECURE_AUTH_KEY',  '${SECURE_AUTH_KEY}' );/g" wp-config.php
/bin/sed -i "s/define( 'LOGGED_IN_KEY',    .*/define( 'LOGGED_IN_KEY',    '${LOGGED_IN_KEY}' );/g" wp-config.php
/bin/sed -i "s/define( 'NONCE_KEY',        .*/define( 'NONCE_KEY',        '${NONCE_KEY}' );/g" wp-config.php
/bin/sed -i "s/define( 'AUTH_SALT',        .*/define( 'AUTH_SALT',        '${AUTH_SALT}' );/g" wp-config.php
/bin/sed -i "s/define( 'SECURE_AUTH_SALT', .*/define( 'SECURE_AUTH_SALT', '${SECURE_AUTH_SALT}' );/g" wp-config.php
/bin/sed -i "s/define( 'LOGGED_IN_SALT',   .*/define( 'LOGGED_IN_SALT',   '${LOGGED_IN_SALT}' );/g" wp-config.php
/bin/sed -i "s/define( 'NONCE_SALT',       .*/define( 'NONCE_SALT',       '${NONCE_SALT}' );/g" wp-config.php

#### fixhttps already done?
if /bin/grep -q '##INKHTTPSFIX=fixed' /opt/verb/conf/webserver/httpd/sites-available/${DOMAIN}.conf; then
/bin/sed -i "/WP_SITEURL/d" /srv/www/vapps/wp.${DOMAIN}/wp-config.php
/bin/sed -i "/WP_HOME/d" /srv/www/vapps/wp.${DOMAIN}/wp-config.php
/bin/echo "define( 'WP_SITEURL', 'https://${DOMAIN}' );
define( 'WP_HOME', 'https://${DOMAIN}' );" >> /srv/www/vapps/wp.${DOMAIN}/wp-config.php
fi

# Reset all permissions
/bin/chmod -R 440 wp-config.php
/bin/chown -R www:www /srv/www/vapps/${CVAPPNAME}

# Set up the Apache config
/bin/cp /opt/verb/conf/site-files/conf/wpbbb-bb.${inkURI}.conf /opt/verb/conf/webserver/httpd/sites-available/bb.${inkURI}.conf
/usr/bin/apachectl graceful
## inkCert SSL certs
### Not setup
if /bin/grep -Fq "INKCERTED=NO" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${inkURI}; then
/bin/echo "FYI: inkCert is not yet setup for ${inkURI}."
fi
### inkCert-LE DONE
if /bin/grep -Fq "INKCERTED=DONE_LE" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${inkURI}; then
/bin/echo "inkCert-LE is already setup for ${inkURI}. Updating the Apache configs..."
/opt/verb/serfs/inkcertaddallle ${inkURI}
wait
fi
### inkCert-IC DONE
if /bin/grep -Fq "INKCERTED=DONE_IC" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${inkURI}; then
/bin/echo "inkCert-IC is already setup for ${inkURI}. Updating the Apache configs..."
/opt/verb/serfs/inkcertadd blog.${inkURI}
wait
fi

# Set the site-wide inkblog config
/bin/sed -i "s/INKblog=.*/INKblog=\"WordPress\"/g" /opt/verb/conf/siteinstallstatus

# Get the themes and plugins form inkisaverb.com
/opt/verb/sefs/wpadd bb ink.bb
wait

# Set the site-wide inkblog config
/bin/sed -i "s/INKbb=.*/INKbb=\"WordPress\"/g" /opt/verb/conf/siteinstallstatus

# Reset all permissions
/bin/chown -R www:www /srv/www/vapps/${CVAPPNAME}

# Finish
/bin/echo "These are setup:

Database: ${DBASE}
Database user: ${DBUSER}
Database password: ${DBPASSWORD}

Go to http://${DOMAIN}/wp-admin/index.php to install.
"
