#!/bin/sh
#inkVerbSerf! verb.ink

# This downloads and installs the current verified version of OWA to owa.your-name.verb.red

# All options are optional, but must are sequential, omit last options first.

# How to use:
## ./installowared [dbase] [dbuser] [dbpassword]


CVAPPNAME=owa

# Include the config
. /opt/verb/conf/siteurilist

DBASE=$1
DBUSER=$2
DBPASSWORD=$3
CLEANNAME=$(/bin/echo $CVAPPNAME | sed -e 's/\.//g')

# Check if already installed
## Config
if [ -f /opt/verb/conf/vapp.${CVAPPNAME} ]; then
/bin/echo "This is already installed."
exit 0; fi
## Directory
if [ -d /srv/www/vapps/${CVAPPNAME} ]; then
/bin/echo "OWA already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
exit 8; fi

# Download and unpack the latest checked version from inkisaverb.com/repo
cd /srv/www/vapps
/opt/verb/serfs/inkget ${CVAPPNAME}; wait
### Check
/opt/verb/serfs/inkget ${CVAPPNAME} check
if [ "$?" = 4 ]; then
/bin/echo "Repo failed to retrieve the file."
exit 4; fi
if [ ! -f ${CVAPPNAME}.vtxz ]; then
/bin/echo "Failed to retrieve from the repo."
exit 4; fi

/bin/rm -rf ${CVAPPNAME}
/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
/opt/verb/serfs/setvapplinkon ${CVAPPNAME}; wait
/bin/chown -R www:www /srv/www/html/red.owa; wait

# Auto database
if [ -z ${3} ]; then
DBPASSWORD=$(/usr/bin/pwgen -s -1 10); fi
if [ -z ${1} ]; then
DBASE=${CLEANNAME}$(/usr/bin/pwgen -s -1 6); fi
if [ -z ${2} ]; then
DBUSER=${DBASE}; fi

# Create the database user and credentials
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
CREATE DATABASE  ${DBASE};
GRANT ALL PRIVILEGES ON *.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}' WITH GRANT OPTION;
FLUSH PRIVILEGES;"

# Write the config for backup
/bin/echo "#!/bin/sh
APPDBASE=${DBASE}
APPDDBUSR=${DBUSER}
APPDDBPAS=${DBPASSWORD}" > /opt/verb/conf/vapp.${CVAPPNAME}

# Put the settings in the OWA config file
cd /srv/www/html/red.owa
/bin/cp owa-config-dist.php owa-config.php
/bin/sed -i "s/yourdbtypegoeshere/mysql/g" owa-config.php
/bin/sed -i "s/yourdbnamegoeshere/${DBASE}/g" owa-config.php
/bin/sed -i "s/yourdbhostgoeshere/localhost/g" owa-config.php
/bin/sed -i "s/yourdbusergoeshere/${DBUSER}/g" owa-config.php
/bin/sed -i "s/yourdbpasswordgoeshere/${DBPASSWORD}/g" owa-config.php
/bin/sed -i "s/define('OWA_PUBLIC_URL',.*/define('OWA_PUBLIC_URL', 'https:\/\/owa\.${redURI}\/');/g" owa-config.php


# Add the secure salt and key strings
OWA_NONCE_KEY="$(/usr/bin/pwgen -s -1 27)"
OWA_NONCE_SALT="$(/usr/bin/pwgen -s -1 27)"
OWA_AUTH_KEY="$(/usr/bin/pwgen -s -1 27)"
OWA_AUTH_SALT="$(/usr/bin/pwgen -s -1 27)"
/bin/sed -i "s/define('OWA_NONCE_KEY',.*/define('OWA_NONCE_KEY', '${OWA_NONCE_KEY}');/g" owa-config.php
/bin/sed -i "s/define('OWA_NONCE_SALT',.*/define('OWA_NONCE_SALT', '${OWA_NONCE_SALT}');/g" owa-config.php
/bin/sed -i "s/define('OWA_AUTH_KEY',.*/define('OWA_AUTH_KEY', '${OWA_AUTH_KEY}');/g" owa-config.php
/bin/sed -i "s/define('OWA_AUTH_SALT',.*/define('OWA_AUTH_SALT', '${OWA_AUTH_SALT}');/g" owa-config.php

# Reset all permissions and reload
/bin/chown -R www:www /srv/www/vapps/${CVAPPNAME}; wait
/usr/bin/apachectl graceful

# Finish
/bin/echo "These are setup:

Database: ${DBASE}
Host Name: localhost (do not use owa....verb.red)
Database user: ${DBUSER}
Database password: ${DBPASSWORD}

Go to the https://owa.${redURI}/install.php site to install.
"
