#!/bin/sh
#inkVerbSerf! verb.ink

# This installs the NVM package manager for Node.js

# How to use:
## ./installnvm

/usr/bin/su slave -c '/usr/bin/yay -S --noconfirm nvm'

echo 'source /usr/share/nvm/init-nvm.sh' >> /etc/bash.bashrc
echo 'source /usr/share/nvm/init-nvm.sh' >> ~/.bashrc




if [ -e "/opt/verb/mods/installnvm.after" ]; then . /opt/verb/mods/installnvm.after; fi # Follows this script
