#!/bin/sh
#inkVerbSerf! verb.ink

# This removes the inkDKIM key from an existing DNS TXT record in the inkDNS zone file on the server

# How to use:
## ./killinkdnsinkdkim [ domain.tld ]
## ./killinkdnsinkdkim [ domain.tld ] verber

usagenotes="This removes the inkDKIM key from an existing DNS TXT record in the inkDNS zone file on the server"
usageformat="killinkdnsdomain [ domain.tld or subdomain.domain.tld etc ] [ verber - only if addressing a verb domain ]"
usageexample="killinkdnsinkdkim inkisaverb.com
killinkdnsinkdkim NAME.verb.email verber"
hierarchy=( tertiary killdomainshell )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=( "verber" )
vopttypes=( string_match )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( inkdnsaddinkdkim )
usedby=( killinkcertmail )
useserfs=( inkdnsserial inkdnsrefreshbind )
useconfigs=( sitenameip inkcertstatus inkdnsconf sitemailpath )
if [ -n "infoINKonly" ] && [ "infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/killinkdnsinkdkim.replace" ]; then . /opt/verb/mods/killinkdnsinkdkim.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/killinkdnsinkdkim.before" ]; then . /opt/verb/mods/killinkdnsinkdkim.before; return 0; fi # Replaces this script


# Dependencies
if ! /bin/grep -q 'INKCERTINSTALLED="DONE"' /opt/verb/conf/inkcertstatus; then
  /usr/bin/echo "Install inkCert first, I quit."; exit 8
fi
if ! /bin/grep -q 'INKDNSSTAT="INSTALLED"' /opt/verb/conf/inkdnsconf; then
  /usr/bin/echo "Install inkDNS first, I quit."; exit 8
fi
if ! /bin/grep -q 'SITEMAILSTATUS="VMAIL_SERVER"' /opt/verb/conf/sitemailpath; then
  /usr/bin/echo "Install Postfix Vmail first, I quit."; exit 8
fi

DNSDOMAIN="$1"
if [ -n $2 ] && [ "$2" = "verber" ]; then
  ZONEDIR="inkzones"
else
  ZONEDIR="zones"
fi

# Include the configs
. /opt/verb/conf/sitenameip

# Check if already added
if /bin/grep -Fq "; inkDKIM key" /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNSDOMAIN}; then
/bin/echo "The inkDKIM key for ${DNSDOMAIN} has not been added. Use inkdnsaddinkdkim to add it."
exit 0; fi

# Remove the key
/bin/sed -i "/; inkDKIM key ${DNSDOMAIN}/,/;; End inkDKIM key ${DNSDOMAIN}/d" /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNSDOMAIN}

# Set the Serial No
if [ "${ZONEDIR}" = "inkzones" ]; then
  /opt/verb/serfs/inkdnsserial ${DNSDOMAIN} verber
elif [ "${ZONEDIR}" = "zones" ]; then
  /opt/verb/serfs/inkdnsserial ${DNSDOMAIN}
fi

# Refresh zones
if [ -f "/opt/verb/conf/inkdnsconf" ]; then
  . /opt/verb/conf/inkdnsconf
  if [ "${INKDNSSTAT}" = "INSTALLED" ]; then
/opt/verb/serfs/inkdnsrefreshbind; fi; fi

# Finish
/bin/echo "The inkDKIM key has been removed from the ${DNSDOMAIN} DNS zone file."




if [ -e "/opt/verb/mods/killinkdnsinkdkim.after" ]; then . /opt/verb/mods/killinkdnsinkdkim.after; fi # Follows this script
