#!/bin/sh
#inkVerbSerf! verb.ink

# This "hard" kills a domain added with adddomain or adddomaincgi
## This removes everything. The server probably wouldn't even know that the domain existed, except for any connected vapp

## This DOES NOT:
### Remove any connected vapp

## This DOES:
### Remove the SSL certificate for the domain and all subdomains thereof.
### Remove files formerly in the domain from the server, which are retained in the domains folder that an ftpvip can access
### Remove files for subdomains in the domains folder, just the same.
### Remove any subdomain folders belonging to the domain.
### Remove opekDKIM/inkDKIM keys.
### Remove the inkDNS zone file

# How to use:
## ./killdomainhard [KILLDOMAIN.tld]


# Dependencies
if ! /bin/grep -q 'INKCERTINSTALLED="DONE"' /opt/verb/conf/inkcert/inkcertstatus; then
  /usr/bin/echo "Install inkCert first, I quit."; exit 8
fi
if ! /bin/grep -q 'INKDNSSTAT="INSTALLED"' /opt/verb/conf/inkdns/inkdnsconf; then
  /usr/bin/echo "Install inkDNS first, I quit."; exit 8
fi
if ! /bin/grep -q 'SITEMAILSTATUS="VMAIL_SERVER"' /opt/verb/conf/sitemailpath; then
  /usr/bin/echo "Install Postfix Vmail first, I quit."; exit 8
fi

KILLDOMAIN=$1

# Remove all config files, symlinks, and directories
if [ ${SERVERTYPE} = "lemp" ]; then
  /bin/rm -f /etc/nginx/sites-enabled/${KILLDOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-available/${KILLDOMAIN}.conf
  /usr/bin/systemctl restart nginx
elif [ ${SERVERTYPE} = "lamp" ]; then
  /bin/rm -f /etc/httpd/sites-enabled/${KILLDOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-available/${KILLDOMAIN}.conf
  /usr/bin/systemctl restart httpd
elif [ ${SERVERTYPE} = "laemp" ]; then
  /bin/rm -f /etc/httpd/sites-enabled/${KILLDOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-available/${KILLDOMAIN}.conf
  /bin/rm -f /etc/nginx/sites-enabled/${KILLDOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-available/${KILLDOMAIN}.conf
  /usr/bin/systemctl restart httpd
  /usr/bin/systemctl restart nginx
fi
/bin/rm -f /srv/www/html/${KILLDOMAIN}
/bin/rm -f /srv/www/html/*${KILLDOMAIN}
/bin/rm -rf /srv/www/domains/${KILLDOMAIN}
/bin/rm -rf /srv/www/domains/*${KILLDOMAIN}

# Other services
/opt/verb/serfs/killdomainshell ${KILLDOMAIN}; wait

# Restart

# Finish
/bin/echo "${KILLDOMAIN} is all gone, bye bye. Some vapps might remain.
"

