#!/bin/sh
#inkVerbSerf! verb.ink

# This removes an existing domain from vip/_domains.vip

# How to use:
## ./killdomainvip [olddomain.tld]


OLDDOMAIN=$1

/bin/rm -f /srv/vip/_domains.vip/${OLDDOMAIN}
