#!/bin/sh
#inkVerbSerf! verb.ink

# This completely removes an inkVerb web app, it's database, and it's config file
## WARNING: This does not backup the app, it just destroys it
## This is useful if you want to reinstall the app afresh or to remove every trace of it.
## This does not remove an actual domain, if a webapp was installed to it, but it will break the domain.

# NOTE: If this is a domain app, such as WordPress or Drupal, etc., installed to a domain, after this, run: killdomain

# How to use:
## ./killvapp [app namespace]


# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/vapp.${APPNAME}

APPNAME=$1

# Kill the database and user
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
DROP DATABASE ${APPDBASE};
DROP USER ${APPDDBUSR}@localhost;
FLUSH PRIVILEGES;"

# Kill the config
/bin/rm -f /opt/verb/conf/vapp.${APPNAME}

# Kill the directories
/bin/rm -rf /srv/www/vapps/${APPNAME}
/bin/rm -rf /srv/vip/_webapps/${APPNAME}
/bin/rm -rf /srv/www/html/*.${APPNAME}
/opt/verb/serfs/updatehtmlverbs

# Finish
/bin/echo "Taps...

${APPNAME} is now dead.
"

