#!/bin/sh
#inkVerbSerf! verb.ink

# This completely removes a domain's inkCert, Letsencrypt, inkDNS, and inkDKIM (OpenDKIM) profiles
## This does NOT:
### Remove any subdomains
### Remove any web or Apache folders or configs

# How to use:
## ./killdomainshell [domain]


KILLDOMSHELL=$1

# Remove inkCert (including Letsencrypt) configs
/opt/verb/serfs/inkcertkilldomain ${KILLDOMAIN}; wait

# Remove inkDNS zone file
/opt/verb/serfs/inkdnskilldomain ${KILLDOMAIN}; wait

# Remove inkDKIM entries
/opt/verb/serfs/killinkdkim ${KILLDOMSHELL}; wait

# Finish
/bin/echo "No more papers...

The inkCert, inkDNS, and inkDKIM profiles for ${KILLDOMSHELL} have been deleted.
"

