#!/bin/sh
#inkVerbSerf! verb.ink

# This "soft" kills a domain added with adddomain or adddomaincgi
## This removes the root Apache file, html/ symlink, root DNS declarations, and the root domain inkCert-LE declaration, but not other entire configs, such as the inkCert-LE config file that may apply to subdomains.
## This basically turns off the root domain without losing files and retains support for mail, subdomains, and other services.

## This DOES NOT:
### Remove the SSL certificate for the domain and all subdomains thereof.
### Remove files formerly in the domain from the server, which are retained in the domains folder that an ftpvip can access
### Remove any connected vapp
### Remove files for subdomains in the domains folder, just the same.
### Remove any subdomain folders belonging to the domain.
### Remove opekDKIM/inkDKIM keys.
### Remove the entire inkDNS zone file

# How to use:
## ./killdomainsoft [KILLDOMAIN.tld]


# Dependencies
if ! /bin/grep -q 'INKCERTINSTALLED="DONE"' /opt/verb/conf/inkcert/inkcertstatus; then
  /usr/bin/echo "Install inkCert first, I quit."; exit 8
fi
if ! /bin/grep -q 'INKDNSSTAT="INSTALLED"' /opt/verb/conf/inkdns/inkdnsconf; then
  /usr/bin/echo "Install inkDNS first, I quit."; exit 8
fi
if ! /bin/grep -q 'SITEMAILSTATUS="VMAIL_SERVER"' /opt/verb/conf/sitemailpath; then
  /usr/bin/echo "Install Postfix Vmail first, I quit."; exit 8
fi

KILLDOMAIN=$1

# Remove webserver config files
if [ ${SERVERTYPE} = "lemp" ]; then
  /bin/rm -f /etc/nginx/sites-enabled/${KILLDOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-available/${KILLDOMAIN}.conf
  /usr/bin/systemctl restart nginx
elif [ ${SERVERTYPE} = "lamp" ]; then
  /bin/rm -f /etc/httpd/sites-enabled/${KILLDOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-available/${KILLDOMAIN}.conf
  /usr/bin/systemctl restart httpd
elif [ ${SERVERTYPE} = "laemp" ]; then
  /bin/rm -f /etc/httpd/sites-enabled/${KILLDOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-available/${KILLDOMAIN}.conf
  /bin/rm -f /etc/nginx/sites-enabled/${KILLDOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-available/${KILLDOMAIN}.conf
  /usr/bin/systemctl restart httpd
  /usr/bin/systemctl restart nginx
fi

# Remove from inkCert
/bin/sed -i "s/${KILLDOMAIN}, //g" /opt/verb/conf/inkcert/cli-ini/cli.${KILLDOMAIN}.ini

# Remove Root Site Defaults from inkDNS
/bin/sed -i "/; Root Site Defaults/,/;; End Root Site Defaults/d" /opt/verb/conf/inkdns/zones/db.${KILLDOMAIN}
/bin/echo ";;; Root Site Defauls removed" >> /opt/verb/conf/inkdns/zones/db.${KILLDOMAIN}

# Remove http folder symlinks
/bin/rm -f /srv/www/html/${KILLDOMAIN}

# Restart
/usr/bin/systemctl restart postfix
/usr/bin/systemctl restart dovecot

