#!/bin/sh
#inkVerbSerf! verb.ink

# This "soft" kills a domain added with adddomain or adddomaincgi
## This removes the root Apache file, html/ symlink, root DNS declarations, and the root domain inkCert-LE declaration, but not other entire configs, such as the inkCert-LE config file that may apply to subdomains.
## This basically turns off the root domain without losing files and retains support for mail, subdomains, and other services.

## This DOES NOT:
### Remove the SSL certificate for the domain and all subdomains thereof.
### Remove files formerly in the domain from the server, which are retained in the domains folder that an ftpvip can access
### Remove any connected vapp
### Remove files for subdomains in the domains folder, just the same.
### Remove any subdomain folders belonging to the domain.
### Remove opekDKIM/inkDKIM keys.
### Remove the entire inkDNS zone file

# How to use:
## ./killdomainsoft [KILLDOMAIN.tld]


KILLDOMAIN=$1

# Remove Apache server config files
/bin/rm -f /etc/httpd/sites-enabled/${KILLDOMAIN}.conf
/bin/rm -f /opt/verb/conf/webserver/httpd/sites-available/${KILLDOMAIN}.conf
/usr/bin/apachectl graceful

# Remove from inkCert
/bin/sed -i "s/${KILLDOMAIN}, //g" /opt/verb/conf/inkcert/cli-ini/cli.${KILLDOMAIN}.ini

# Remove Root Site Defaults from inkDNS
/bin/sed -i "/; Root Site Defaults/,/;; End Root Site Defaults/d" /opt/verb/conf/inkdns/zones/db.${KILLDOMAIN}
/bin/echo ";;; Root Site Defauls removed" >> /opt/verb/conf/inkdns/zones/db.${KILLDOMAIN}

# Remove http folder symlinks
/bin/rm -f /srv/www/html/${KILLDOMAIN}

# Restart
/etc/init.d/postfix reload
/etc/init.d/postfix restart

