#!/bin/bash
#inkVerbSerf! verb.ink

# This "soft" kills a domain added with adddomain
## This removes the root Apache file, html/ symlink, root DNS declarations, and the root domain inkCert declaration, but not other entire configs, such as the inkCert cli-ini config file that may apply to subdomains.
## This basically turns off the root domain without losing files and retains support for mail, subdomains, and other services.

## This DOES NOT:
### Remove the SSL certificate for the domain and all subdomains thereof.
### Remove files formerly in the domain from the server, which are retained in the domains folder that an ftpvip can access
### Remove any connected vapp
### Remove files for subdomains in the domains folder, just the same.
### Remove any subdomain folders belonging to the domain.
### Remove opekDKIM/inkDKIM keys.
### Remove the entire inkDNS zone file

# How to use:
## ./killdomainsoft [ domaintokill.tld ]

usagenotes="This 'soft' kills a domain's web hosting entries added with adddomain, including Apache/Nginx .conf files, DNS entries, Letsencrypt cli-ini entries, and links in www/html/, but it leaves DNS files, subdomains, mail records, and the web files in www/domains/ or www/vapps/"
usageformat="killdomainsoft [ domaintokill.tld ]"
usageexample="killdomainsoft inkisaverb.com"
hierarchy=( primary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( adddomain )
usedby=(  )
useserfs=(  )
useconfigs=( sitemailpath inkdnsconf inkcertstatus )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/killdomainsoft.replace" ]; then . /opt/verb/mods/killdomainsoft.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/killdomainsoft.before" ]; then . /opt/verb/mods/killdomainsoft.before; return 0; fi # Replaces this script


# Dependencies
if ! /bin/grep -q 'INKCERTINSTALLED="DONE"' /opt/verb/conf/inkcertstatus; then
  /usr/bin/echo "Install inkCert first, I quit."; exit 8
fi
if ! /bin/grep -q 'INKDNSSTAT="INSTALLED"' /opt/verb/conf/inkdnsconf; then
  /usr/bin/echo "Install inkDNS first, I quit."; exit 8
fi
if ! /bin/grep -q 'SITEMAILSTATUS="VMAIL_SERVER"' /opt/verb/conf/sitemailpath; then
  /usr/bin/echo "Install Postfix Vmail first, I quit."; exit 8
fi

KILLDOMAIN=$1

# Remove webserver config files
if [ ${SERVERTYPE} = "lemp" ]; then
  /bin/rm -f /etc/nginx/sites-enabled/${KILLDOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-available/${KILLDOMAIN}.conf
  /usr/bin/systemctl restart nginx
elif [ ${SERVERTYPE} = "lamp" ]; then
  /bin/rm -f /etc/httpd/sites-enabled/${KILLDOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-available/${KILLDOMAIN}.conf
  /usr/bin/systemctl restart httpd
elif [ ${SERVERTYPE} = "laemp" ]; then
  /bin/rm -f /etc/httpd/sites-enabled/${KILLDOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-available/${KILLDOMAIN}.conf
  /bin/rm -f /etc/nginx/sites-enabled/${KILLDOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-available/${KILLDOMAIN}.conf
  /usr/bin/systemctl restart httpd
  /usr/bin/systemctl restart nginx
fi

# Remove Root Site Defaults from inkDNS
/bin/sed -i "/; Root Site Defaults/,/;; End Root Site Defaults/d" /opt/verb/conf/inkdns/zones/db.${KILLDOMAIN}
/bin/echo ";;; Root Site Defauls removed" >> /opt/verb/conf/inkdns/zones/db.${KILLDOMAIN}

# Remove http folder symlinks
/bin/rm -f /srv/www/html/${KILLDOMAIN}

# Restart
/usr/bin/systemctl restart postfix
/usr/bin/systemctl restart dovecot




if [ -e "/opt/verb/mods/killdomainsoft.after" ]; then . /opt/verb/mods/killdomainsoft.after; fi # Follows this script
