#!/bin/sh
#inkVerbSerf! verb.ink

# This "hard" kills a domain added with adddomain or adddomaincgi
## This removes everything. The server probably wouldn't even know that the domain existed, except for any connected vapp

## This DOES NOT:
### Remove any connected vapp

## This DOES:
### Remove the SSL certificate for the domain and all subdomains thereof.
### Remove files formerly in the domain from the server, which are retained in the domains folder that an ftpvip can access
### Remove files for subdomains in the domains folder, just the same.
### Remove any subdomain folders belonging to the domain.
### Remove opekDKIM/inkDKIM keys.
### Remove the inkDNS zone file

# How to use:
## ./killdomainhard [KILLDOMAIN.tld]


KILLDOMAIN=$1

# Remove all config files, symlinks, and directories
/bin/rm -f /etc/httpd/sites-enabled/${KILLDOMAIN}.conf
/bin/rm -f /etc/httpd/sites-enabled/*${KILLDOMAIN}.conf
/bin/rm -f /opt/verb/conf/webserver/httpd/sites-available/${KILLDOMAIN}.conf
/bin/rm -f /opt/verb/conf/webserver/httpd/sites-available/*${KILLDOMAIN}.conf
/usr/bin/apachectl graceful
/opt/verb/serfs/killdomainshell ${KILLDOMAIN}; wait
/bin/rm -f /srv/www/html/${KILLDOMAIN}
/bin/rm -f /srv/www/html/*${KILLDOMAIN}
/bin/rm -rf /srv/www/domains/${KILLDOMAIN}
/bin/rm -rf /srv/www/domains/*${KILLDOMAIN}

# Restart
/etc/init.d/postfix reload
/etc/init.d/postfix restart

# Finish
/bin/echo "${KILLDOMAIN} is all gone, bye bye. Some vapps might remain.
"

