#!/bin/sh
#inkVerbSerf! verb.ink

# This deletes an ftp user and his vsftpd folder, home folder, web accessible folder, and all contents

# How to use:
## ./killftpuser [user]


DELFTPUSER=$1

# Delete the user
userdel ${DELFTPUSER}

# Remove directories and web symlink
/bin/rm -rf /srv/vsftpd/${DELFTPUSER}
/bin/rm -rf /home/${DELFTPUSER}
/bin/rm -f /srv/www/vip/files/${NEWFTPUSER}
