#!/bin/bash
#inkVerbSerf! verb.ink

# This removes mail cert links as defined by setinkcertmail from the location used by the mail server
## This is run automatically by killinkcertmail and normally should not be run independently

# How to use:
## ./killinkcertmailcerts [ domain.tld ]

usagenotes="This removes all inkCert files entirely for inkCert-LE, inkCert-CB, and inkCert-CB-Single"
usageformat="killinkcertmailcerts [ domain.tld ]"
usageexample="killinkcertmailcerts inkisaverb.com"
hierarchy=( tertiary killdomainshell )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( newdomainshell )
usedby=( killinkcertmail )
useserfs=(  )
useconfigs=( inkcertstatus inkdnsconf sitemailpath )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/killinkcertmailcerts.replace" ]; then . /opt/verb/mods/killinkcertmailcerts.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/killinkcertmailcerts.before" ]; then . /opt/verb/mods/killinkcertmailcerts.before; return 0; fi # Replaces this script


# Dependencies
if ! /bin/grep -q 'INKCERTINSTALLED="DONE"' /opt/verb/conf/inkcertstatus; then
  /usr/bin/echo "Install inkCert first, I quit."; exit 8
fi
if ! /bin/grep -q 'INKDNSSTAT="INSTALLED"' /opt/verb/conf/inkdnsconf; then
  /usr/bin/echo "Install inkDNS first, I quit."; exit 8
fi
if ! /bin/grep -q 'SITEMAILSTATUS="VMAIL_SERVER"' /opt/verb/conf/sitemailpath; then
  /usr/bin/echo "Install Postfix Vmail first, I quit."; exit 8
fi

# Include the config
. /opt/verb/conf/siteurilist

DOMAIN="$1"

# Make sure we don't kill a verb domain
if /bin/grep -q "${DOMAIN}" /opt/verb/conf/siteurilist; then
  /usr/bin/echo "Can't kill a verber domain, I quit."; exit 9
fi

# Remove the inkCert-LE certs if they exist, otherwise use Snakeoil
/bin/rm -f /etc/ssl/server/mail/${DOMAIN}.crt
/bin/rm -f /etc/ssl/server/mail/${DOMAIN}.key




if [ -e "/opt/verb/mods/killinkcertmailcerts.after" ]; then . /opt/verb/mods/killinkcertmailcerts.after; fi # Follows this script
