#!/bin/sh
#inkVerbSerf! verb.ink

# This deletes an ftp filer and his vsftpd folder and home folder

# How to use:
## ./killftpfiler [user]


DELFTPFILER=$1

# Delete the user
userdel ${DELFTPFILER}

# Remove directories
/bin/rm -rf /srv/vip/filers/${DELFTPFILER}
/bin/rm -rf /home/${DELFTPFILER}
/bin/rm -rf /srv/www/vip/files/${NEWFTPFILER}
