#!/bin/sh
#inkVerbSerf! verb.ink

# This removes basic mail certificates and subdomain dummy sites for inkCert-LE setup by setinkcertmail
## This is run automatically by killdomainshell and normally should not be run independently

# How to use:
## ./killinkcertmail [domain]


# Dependencies
if ! /bin/grep -q 'INKCERTINSTALLED="DONE"' /opt/verb/conf/inkcert/inkcertstatus; then
  /usr/bin/echo "Install inkCert first, I quit."; exit 8
fi
if ! /bin/grep -q 'INKDNSSTAT="INSTALLED"' /opt/verb/conf/inkdns/inkdnsconf; then
  /usr/bin/echo "Install inkDNS first, I quit."; exit 8
fi
if ! /bin/grep -q 'SITEMAILSTATUS="VMAIL_SERVER"' /opt/verb/conf/sitemailpath; then
  /usr/bin/echo "Install Postfix Vmail first, I quit."; exit 8
fi

DOMAIN="$1"

# Include the config
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servertype

# Make sure we don't kill a verb domain
if /bin/grep -q "${DOMAIN}" /opt/verb/conf/siteurilist; then
  /usr/bin/echo "Can't kill a verber domain, I quit."; exit 9
fi

# inkCert
/opt/verb/serfs/killinkcertmailsubdomains ${DOMAIN}

# Mail cert links
/opt/verb/serfs/killinkcertmailcerts ${DOMAIN}

# Mail DNS zone entries
/opt/verb/serfs/inkdnskillmail ${DOMAIN}

# Dovecot
/bin/rm -f /etc/dovecot/crt.d/${DOMAIN}.conf

# Postfix
/bin/sed -i "/^mail.${DOMAIN}/d" /etc/postfix/virtual_ssl.map

/usr/bin/postmap -F hash:/etc/postfix/virtual_ssl.map

# Restart
/usr/bin/systemctl restart postfix
/usr/bin/systemctl restart dovecot

# Webserver files so inkCert-LE checks work
if [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lemp" ]; then

  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-available/mail.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-available/smtp.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-available/imap.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-available/pop3.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-available/pop2.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-available/pop.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-enabled/mail.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-enabled/smtp.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-enabled/imap.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-enabled/pop3.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-enabled/pop2.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-enabled/pop.${DOMAIN}.conf
  /bin/systemctl restart nginx

elif [ ${SERVERTYPE} = "lamp" ]; then

  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-available/mail.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-available/smtp.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-available/imap.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-available/pop3.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-available/pop2.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-available/pop.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-enabled/mail.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-enabled/smtp.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-enabled/imap.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-enabled/pop3.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-enabled/pop2.${DOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-enabled/pop.${DOMAIN}.conf
  /bin/systemctl restart httpd

fi
