#!/bin/sh
#inkVerbSerf! verb.ink

# This kills a subdomain after it has been added with addsubdomain or addsubdomaincgi

## This DOES NOT:
### Removes the SSL certificate for the domain and all subdomains thereof.
### Remove files formerly in the domain from the server, which are retained in the domains folder that an ftpvip can access
### Remove files for subdomains in the domains folder, just the same.
### Remove any subdomain folders belonging to the domain.
### Remove opekDKIM/inkDKIM keys.

# How to use:
## ./killsubdomain [SUBDOMAIN] [KILLDOMAIN.tld]

KILLSUB=$1
KILLDOMAIN=$2
KILLSUBDOMAIN=${KILLSUB}.${KILLDOMAIN}

# Remove server configs and restart
. /opt/verb/conf/servertype
if [ ${SERVERTYPE} = "lemp" ]; then
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-available/${KILLSUBDOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-enabled/${KILLSUBDOMAIN}.conf
  /usr/bin/systemctl restart nginx
elif [ ${SERVERTYPE} = "lamp" ]; then
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-available/${KILLSUBDOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-enabled/${KILLSUBDOMAIN}.conf
  /usr/bin/systemctl restart httpd
elif [ ${SERVERTYPE} = "laemp" ]; then
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-available/${KILLSUBDOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/httpd/sites-enabled/${KILLSUBDOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-available/${KILLSUBDOMAIN}.conf
  /bin/rm -f /opt/verb/conf/webserver/nginx/sites-enabled/${KILLSUBDOMAIN}.conf
  /usr/bin/systemctl restart httpd
  /usr/bin/systemctl restart nginx
fi

# Remove from inkCert
/bin/sed -i "s/, ${KILLSUBDOMAIN}//g" /opt/verb/conf/inkcert/cli-ini/cli.${KILLDOMAIN}.ini

# Remove http folder symlinks
/bin/rm -f /srv/www/html/${KILLSUBDOMAIN}

# Finish
/bin/echo "${KILLSUBDOMAIN} has been removed. But, the folder in www/domains still exists for a VIP to access."

