#!/bin/sh
#inkVerbSerf! verb.ink

# This reinstall MySQL with new bosses and passwords after it has been removed via mysqluninstall

# How to use:
## ./mysqlinstall


MYSQLPASS=$(/usr/bin/pwgen -0 -1 -A -B 11)
MYSQLBOSSPASS=$(/usr/bin/pwgen -s -1 10)

# Record the MySQL root password
/bin/echo "${MYSQLPASS}" > /opt/verb/inst/mysqlrootpassword
/bin/echo "mysql-server mysql-server/root_password password ${MYSQLPASS}" | debconf-set-selections
/bin/echo "mysql-server mysql-server/root_password_again password ${MYSQLPASS}" | debconf-set-selections

# Install MySQL
/usr/bin/apt-get -y install mysql-server mysql-client

# MySQL superuser to auto-create databases
/usr/bin/mysql -uroot -p${MYSQLPASS} -e "
CREATE USER mysqlboss@localhost;
SET PASSWORD FOR mysqlboss@localhost=PASSWORD('${MYSQLBOSSPASS}');
GRANT ALL PRIVILEGES ON *.* TO 'mysqlboss'@'localhost' IDENTIFIED BY '${MYSQLBOSSPASS}' WITH GRANT OPTION;
FLUSH PRIVILEGES;"
## Set the mysqlboss as the mysqlboss config file so the password is not in the line command
/bin/echo "[client]
user = mysqlboss
password = ${MYSQLBOSSPASS}
host = localhost" > /opt/verb/conf/mysqlboss.cnf

