#!/bin/sh
#inkVerbSerf! verb.ink

# This adds a MySQL user (new or existing) to an existing "all" database as a user with limited permissions (client: data & structure) user with password

# How to use:
## ./mysqlnewdbuser [dbase] [new dbuser] [dbpassword - optional]


DBASE="${1}"
DBUSER="${2}"
DBPASSWORD="${3}"

# Auto password
if [ -z ${3} ]; then
DBPASSWORD="$(/usr/bin/pwgen -s -1 32)"; fi

# Create the SQL items
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
CREATE USER '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE, FILE, CREATE, ALTER, INDEX, DROP, CREATE TEMPORARY TABLES, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, CREATE VIEW, EVENT, TRIGGER ON ${DBASE}.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}';
FLUSH PRIVILEGES;"

# Create a Verber record
echo "DBASE=\"${DBASE}\"
DBUSER=\"${DBUSER}\"
DBPASSWORD=\"${DBPASSWORD}\"" > /opt/verb/conf/mysqldbuser.${DBASE}
