#!/bin/sh
#inkVerbSerf! verb.ink

# This exports a MySQL/MariaDB database to a .sql file with the same name
## The .sql file appears in the vip/sql/ directory
## Omit or include the .sql extension on the end of the file name

# How to use:
## ./mysqlex [ database name ]

usagenotes="This exports a MySQL/MariaDB database to a .sql file with the same name"
usageformat="mysqlex [ database name ]"
usageexample="mysqlex myGreat99DB"
hierarchy=( primary )
vsetnames=( "Database name" )
vsettypes=( isSQLDatabasename )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( mysqlinstall )
prerequesite=( mysqlnewdb )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "infoINKonly" ] && [ "infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/mysqlex.replace" ]; then . /opt/verb/mods/mysqlex.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/mysqlex.before" ]; then . /opt/verb/mods/mysqlex.before; return 0; fi # Replaces this script


INPUT=$1
DBASE=${INPUT%.sql}

/usr/bin/mysqldump --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf ${DBASE} > /srv/vip/sql/${DBASE}.sql

if [ $? = "0" ]; then
  echo "Database available at vip/sql/${DBASE}.sql"
fi




if [ -e "/opt/verb/mods/mysqlex.after" ]; then . /opt/verb/mods/mysqlex.after; fi # Follows this script
