#!/bin/sh
#inkVerbSerf! verb.ink

# This creates a new MySQL database and a new global-permissions (all/admin) user with password

# How to use:
## ./mysqlnewdball [dbase] [dbadmin] [dbpassword optional]


DBASE="${1}"
DBUSER="${2}"
DBPASSWORD="${3}"

# Auto password
if [ -z ${3} ]; then
DBPASSWORD="$(/usr/bin/pwgen -s -1 32)"; fi

# Create the SQL items
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
CREATE DATABASE ${DBASE} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON ${DBASE}.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}';
FLUSH PRIVILEGES;"

# Create a Verber record
echo "DBASE=\"${DBASE}\"
DBUSER=\"${DBUSER}\"
DBPASSWORD=\"${DBPASSWORD}\"
UTYPE=\"ALL\"" > /opt/verb/conf/mysqldb.${DBASE}

# Create the MySQL login .cnf
echo "[client]
user = ${DBUSER}
password = ${DBPASSWORD}
database = ${DBASE}
host = localhost
" > /opt/verb/conf/mysqldb.${DBASE}.cnf
