#!/bin/sh
#inkVerbSerf! verb.ink

# This exports a MySQL database to a .sql file with the same name
## The .sql file appears in the vip/sql/ directory

# How to use:
## ./mysqlex [dbase]


DBASE=$1

/usr/bin/mysqldump --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf ${DBASE} > /srv/vip/sql/${DBASE}.sql
echo "Database available at vip/sql/${DBASE}.sql"
