#!/bin/sh
#inkVerbSerf! verb.ink

# This creates and adds a MySQL database using an existing vapp config
## The vapp config file must me located in ~/verb/conf
## The sql database file must be in the PWD in which this serf is run

# How to use:
## ./mysqlvappin [path/to/database/vapp.config.file]


VAPPCONF=$1

# Include the vapp.config.file
. /opt/verb/conf/${VAPPCONF}

# Create a dummy database as a frame
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
CREATE DATABASE ${APPDBASE};
GRANT ALL PRIVILEGES ON ${APPDBASE}.* TO '${APPDDBUSR}'@'localhost' IDENTIFIED BY '${APPDDBPAS}';
FLUSH PRIVILEGES;"

# Import the database
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf ${APPDBASE} < ${APPDBASE}.sql

