#!/bin/sh
#inkVerbSerf! verb.ink

# This drops (deletes) a MySQL user

# How to use:
## ./mysqlkilldb [dbase]


DBASE=$1

/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
DROP DATABASE ${DBASE};"

