#!/bin/sh
#inkVerbSerf! verb.ink

# This drops (deletes) a MySQL user

# How to use:
## ./mysqlkilluser [dbuser]


DBUSER=$1

/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
DROP USER ${DBUSER}@localhost;"

