#!/bin/sh
#inkVerbSerf! verb.ink

# This completely removes MySQL
## WARNING: This WILL cause the Apocalypse!
## WARNING: Only use this if the Apocalypse already began and you are ready for fallout.
## WARNING: Your mail server, if installed, will permanently break and you'll have to install the entire server again.
## WARNING: Use only if you have a good reason. Re-installing the entire server from backups may save time.

# How to use:
## ./mysqluninstall


/bin/systemctl stop mysql
killall -KILL mysql mysqld_safe mysqld
/usr/bin/apt-get --yes purge mysql-server mysql-client
/usr/bin/apt-get --yes autoremove --purge
/usr/bin/apt-get autoclean
/usr/sbin/deluser --remove-home mysql
/usr/sbin/delgroup mysql
/bin/rm -rf /etc/apparmor.d/abstractions/mysql /etc/apparmor.d/cache/usr.sbin.mysqld /etc/mysql /var/lib/mysql /var/log/mysql* /var/log/upstart/mysql.log* /var/run/mysqld
updatedb
exit

