#!/bin/sh
#inkVerbSerf! verb.ink

# This imports a MySQL database from a .sql file with the same name
## The .sql file to import must be in the vip/sql/ directory

# How to use:
## ./mysqlin [dbase]


DBASE=$1

/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf ${DBASE} < /srv/vip/sql/${DBASE}.sql
echo "${DBASE} database restored."
