#!/bin/sh
#inkVerbSerf! verb.ink

# This imports a MySQL database from a .sql file with the same name
## The .sql file to import must be in the vip/sql/ directory
## Omit or include the .sql extension on the end of the file name

# How to use:
## ./mysqlin [dbase]


INPUT=$1
DBASE=${INPUT%.sql}

/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf ${DBASE} < /srv/vip/sql/${DBASE}.sql

if [ $? = "0" ]; then
  echo "${DBASE} database restored."
fi
