#!/bin/sh
#inkVerbSerf! verb.ink

# This exports a MySQL database to a .sql file with the same name
## The .sql file appears in the vip/sql/ directory
## Omit or include the .sql extension on the end of the file name

# How to use:
## ./mysqlex [dbase]


INPUT=$1
DBASE=${INPUT%.sql}

/usr/bin/mysqldump --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf ${DBASE} > /srv/vip/sql/${DBASE}.sql

if [ $? = "0" ]; then
  echo "Database available at vip/sql/${DBASE}.sql"
fi
