#!/bin/sh
#inkVerbSerf! verb.ink

# This script creates a new boss user that is a sudoer who can can boss serfs

# How to use:
## ./newboss [new boss user] [boss password]


# Include the config file
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteport

NEWBOSS=$1
NEWBOSSPASS=$2

# Add the new user
/usr/sbin/adduser ${NEWBOSS} --gecos ",,," --disabled-password
/bin/echo "${NEWBOSS}:${NEWBOSSPASS}" | chpasswd
usermod -a -G sudo ${NEWBOSS}
usermod -a -G www-data ${NEWBOSS}
/bin/ln -s /opt/verb/boss /home/${NEWBOSS}/
## User privilege specification
setfacl -R -m user:${NEWBOSS}:rwx /home/${NEWBOSS}
/bin/echo '# Added by newboss inkVerb serf' >> /etc/sudoers
/bin/echo '${NEWBOSS}  ALL=(ALL:ALL) ALL' >> /etc/sudoers

# Finished
/bin/echo "The boss user ${NEWBOSS} has been created.
Log in using 'ssh ${NEWBOSS}@${SITEIP} -p ${SITEPORT}'
"
