#!/bin/bash
#inkVerbSerf! verb.ink

# This script creates a new boss user that is a sudoer who can can run serfs

# How to use:
## ./newboss [ new boss user ] [ boss password ]

usagenotes="This script creates a new boss user that is a sudoer who can can run serfs"
usageformat="newboss [ new boss user ] [ boss password ]"
usageexample="newboss managerjohn NotSecure125"
hierarchy=( primary )
vsetnames=( "Username" "Password" )
vsettypes=( isUsername string_quote )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( newftpvip 'or' newftpfiler )
usedby=(  )
useserfs=( ensiteapache ensitenginx inkdnsaddvipsub inkcertaddcb )
useconfigs=( sitenameip siteport )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/newboss.replace" ]; then . /opt/verb/mods/newboss.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/newboss.before" ]; then . /opt/verb/mods/newboss.before; return 0; fi # Replaces this script


# Include the config file
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteport

NEWBOSS=$1
NEWBOSSPASS=$2

# Old create new boss user
# /usr/sbin/adduser ${NEWBOSS} --gecos ",,," --disabled-password
# /bin/echo "${NEWBOSS}:${NEWBOSSPASS}" | chpasswd
# usermod -a -G sudo ${NEWBOSS}
# usermod -a -G www-data ${NEWBOSS}
# /bin/ln -s /opt/verb/boss /home/${NEWBOSS}/

# Create the new boss user
/usr/bin/groupadd ${NEWBOSS}
/usr/bin/useradd -g ${NEWBOSS} ${NEWBOSS}
/bin/echo "${NEWBOSS}:${NEWBOSSPASS}" | chpasswd
/usr/bin/usermod -a -G sudo ${NEWBOSS}
/usr/bin/usermod -a -G www ${NEWBOSS}
/usr/bin/mkdir -p /home/${NEWBOSS}
/bin/ln -sfn /opt/verb/boss /home/${NEWBOSS}/
## User privilege specification
/usr/bin/setfacl -R -m user:${NEWBOSS}:rwx /home/${NEWBOSS}  # DEV see if this line works
/bin/echo '# Added by newboss inkVerb serf' >> /etc/sudoers.d/${NEWBOSS}
/bin/echo "${NEWBOSS}  ALL=(ALL:ALL) ALL" >> /etc/sudoers.d/${NEWBOSS}
## Vim preferences
echo 'nnoremap <C-c> "+y
vnoremap <C-c> "+y
nnoremap <C-p> "+p
vnoremap <C-p> "+p' > /home/${NEWBOSS}/.vimrc
## BASH settings
/opt/verb/serfs/setbashrc ${NEWBOSS}
## Own
/usr/bin/chown -R ${NEWBOSS}:${NEWBOSS} /home/${NEWBOSS}

# Finished
/bin/echo "The boss user ${NEWBOSS} has been created.
Log in using 'ssh ${NEWBOSS}@${SITEIP} -p ${SITEPORT}'
"




if [ -e "/opt/verb/mods/newboss.after" ]; then . /opt/verb/mods/newboss.after; fi # Follows this script
