#!/bin/sh
#inkVerbSerf! verb.ink

# This prepares core Verber config files for a domain, with OpenDKIM profiles and keys and inkCert and inkDNS configs, WITHOUT including the actual domain itself or its Apache configs and html folder.
## This is intended as a subscript to be used by adddomain or adddomaincgi
## This does NOT:
### Add the domain to inkCert for SSL requests
### Create Apache folders or configs for the domain
## For inkCert and Apache configs, use adddomain or adddomaincgi
## This can be run BEFORE AND AGAIN AFTER installvmail, it has soft tests to see what hasn't been done yet

# How to use:
## ./newdomainshell [newdomain.tld]


# Include settings
. /opt/verb/conf/sitenameip
. /opt/verb/conf/sitemailpath
. /opt/verb/conf/inkcert/inkcertstatus

NEWDOMAIN=$1

# inkCert
if [ ! -f "/opt/verb/conf/inkcert/cli-ini/siteinkcert.${NEWDOMAIN}" ]; then
  /bin/cp /opt/verb/conf/inkcert/cli-ini/cli.new.ini /opt/verb/conf/inkcert/cli-ini/cli.${NEWDOMAIN}.ini
  /bin/sed -i "s/inkcertemail589/${INKCERTEMAIL}/g" /opt/verb/conf/inkcert/cli-ini/cli.${NEWDOMAIN}.ini
  /bin/sed -i "s/newdomain589/${NEWDOMAIN}/g" /opt/verb/conf/inkcert/cli-ini/cli.${NEWDOMAIN}.ini
  /bin/echo "INKCERTED=NOT_YET" > /opt/verb/conf/inkcert/cli-ini/siteinkcert.${NEWDOMAIN}
  /opt/verb/serfs/setinkcertmail ${NEWDOMAIN}
fi

# inkDNS
if [ ! -f "/opt/verb/conf/inkdns/zones/db.${NEWDOMAIN}" ]; then
  /opt/verb/serfs/inkdnsadddomain ${NEWDOMAIN}; wait
fi

# inkDKIM & vmail (if installed)
if [ "${SITEMAILSTATUS}" != "EMAIL_NOT_INSTALLED" ]; then
  /opt/verb/serfs/addinkdkim ${NEWDOMAIN}; wait
  /opt/verb/serfs/vmaildomain ${NEWDOMAIN}; wait

  # inkDNS for vmail
  if [ -f "/opt/verb/conf/inkdns/zones/db.${NEWDOMAIN}" ]; then
  /opt/verb/serfs/inkdnsaddmail ${NEWDOMAIN}; wait
  /opt/verb/serfs/inkdnsaddinkdkim ${NEWDOMAIN}; wait
  fi

fi

# Finish
/bin/echo "Great! With no error messages, ${NEWDOMAIN} is ready on the Verber."
