#!/bin/sh
#inkVerbSerf! verb.ink

# This changes the password for an existing fossil user

# How to use:
## ./newfossilpass [existing-fossil-name] [username] [userpassword]

# Example:
## ./newfossilpass dinosaur adam AdamNuup4$$w0RD


# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

OLDFOSSIL=$1
OLDUSER=$2
NEWPASS=$3

cd /srv/www/vip/fossil

# Change the password
fossil user password ${OLDUSER} ${NEWPASS} --repository ${OLDFOSSIL}.fossil

/bin/echo "New ${OLDFOSSIL}.fossil password set for ${OLDUSER}.
Available on web at fossil.${vipURI}/${OLDFOSSIL}.cgi"
