#!/bin/sh
#inkVerbSerf! verb.ink

# This creates a normal ftp user, owning a unique ftp folder accessible at files....verb.vip/FTPUSERNAME/
## Requires installvsftpd and activatefiles on

# How to use:
## ./newftpuser [new user] [new user password]


NEWFTPUSER=$1
NEWUSERPASS=$2

# Create the user with password
/usr/sbin/adduser ${NEWFTPUSER} --gecos ",,," --disabled-password
/bin/echo "${NEWFTPUSER}:${NEWUSERPASS}" | chpasswd

# Change the user's directory to the vsftpd vips directory
/bin/mkdir /srv/vsftpd/${NEWFTPUSER}
usermod -d /srv/vsftpd/${NEWFTPUSER} ${NEWFTPUSER}
restart vsftpd

# Create the link to access the folder via web
/bin/ln -s /srv/vsftpd/${NEWFTPUSER} /srv/www/vip/files/

# Own the user's web accessible symlink folder
/bin/chown -R www:www /srv/www/vip/files/${NEWFTPUSER}
