#!/bin/sh
#inkVerbSerf! verb.ink

# This creates a new fossil available at fossil.your-name.verb.vip/FOSSIL-NAME.cgi
## Prereq: fossil

# How to use:
## ./newfossil [new-fossil-name] [username] [user-email] [userpassword]

# Example:
## ./newfossil dinosaur adam adam@verb.ink Adamp4$$w0RD


# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

NEWFOSSIL=$1
NEWUSER=$2
NEWEMAIL=$3
NEWPASS=$4

# Create the fossil with user
cd /srv/www/vip/fossil
fossil new ${NEWFOSSIL}.fossil --admin-user ${NEWUSER}

# Change the user's password
fossil user password ${NEWUSER} ${NEWPASS} --repository ${NEWFOSSIL}.fossil

# Write the .cgi file
/bin/echo "#!/usr/bin/fossil
repository: /fossil/${NEWFOSSIL}.fossil" > ${NEWFOSSIL}.cgi
/bin/chmod 750 ${NEWFOSSIL}.cgi

# Final chown to allow database to be writable
/bin/chown -R www:www /srv/www/vip/fossil

/bin/echo "${NEWFOSSIL}.fossil created.
Available on web at fossil.${vipURI}/${NEWFOSSIL}.cgi"

