#!/bin/sh
#inkVerbSerf! verb.ink

# This adds a new subdomain to become newsub.NAME.verb.one

# How to use:
## ./newonesub [ subdomain ]

usagenotes="This adds a new subdomain to become newsub.NAME.verb.one"
usageformat="newonesub [ subdomain ]"
usageexample="newonesub inkisaverb.com"
hierarchy=( primary )
vsetnames=( "Subdomain" )
vsettypes=( isDomainPart )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=( ensiteapache ensitenginx inkdnsaddonesub inkcertaddcb )
useconfigs=( sitenameip siteurilist servertype )
if [ -n "infoINKonly" ] && [ "infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/newonesub.replace" ]; then . /opt/verb/mods/newonesub.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/newonesub.before" ]; then . /opt/verb/mods/newonesub.before; return 0; fi # Replaces this script


# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servertype

NEWONESUB=$1

# Web directory
/bin/cp -R /opt/verb/conf/site-files/newonesubdir /srv/www/one/${NEWONESUB}
/bin/chown -R www:www /srv/www/one/${NEWONESUB}

# Server
if [ ${SERVERTYPE} = "lemp" ]; then
  /bin/cp /opt/verb/conf/site-files/conf/newnginxonesub.conf /opt/verb/conf/webserver/nginx/sites-available/${NEWONESUB}.${oneURI}.conf
  /bin/sed -i "s/newonesub/${NEWONESUB}/g" /opt/verb/conf/webserver/nginx/sites-available/${NEWONESUB}.${oneURI}.conf
  /bin/sed -i "s/oneURI286/${oneURI}/g" /opt/verb/conf/webserver/nginx/sites-available/${NEWONESUB}.${oneURI}.conf
  /opt/verb/serfs/ensitenginx -r ${NEWONESUB}.${oneURI}
elif [ ${SERVERTYPE} = "lamp" ]; then
  /bin/cp /opt/verb/conf/site-files/conf/newonesub.conf /opt/verb/conf/webserver/httpd/sites-available/${NEWONESUB}.${oneURI}.conf
  /bin/sed -i "s/newonesub/${NEWONESUB}/g" /opt/verb/conf/webserver/httpd/sites-available/${NEWONESUB}.${oneURI}.conf
  /bin/sed -i "s/oneURI286/${oneURI}/g" /opt/verb/conf/webserver/httpd/sites-available/${NEWONESUB}.${oneURI}.conf
  /opt/verb/serfs/ensiteapache -r ${NEWONESUB}.${oneURI}
elif [ ${SERVERTYPE} = "laemp" ]; then
  /bin/cp /opt/verb/conf/site-files/conf/newonesub.conf /opt/verb/conf/webserver/httpd/sites-available/${NEWONESUB}.${oneURI}.conf
  /bin/sed -i "s/newonesub/${NEWONESUB}/g" /opt/verb/conf/webserver/httpd/sites-available/${NEWONESUB}.${oneURI}.conf
  /bin/sed -i "s/oneURI286/${oneURI}/g" /opt/verb/conf/webserver/httpd/sites-available/${NEWONESUB}.${oneURI}.conf
  /bin/cp /opt/verb/conf/site-files/conf/newrpnginxonesub.conf /opt/verb/conf/webserver/nginx/sites-available/${NEWONESUB}.${oneURI}.conf
  /bin/sed -i "s/newonesub/${NEWONESUB}/g" /opt/verb/conf/webserver/nginx/sites-available/${NEWONESUB}.${oneURI}.conf
  /bin/sed -i "s/oneURI286/${oneURI}/g" /opt/verb/conf/webserver/nginx/sites-available/${NEWONESUB}.${oneURI}.conf
  /opt/verb/serfs/ensiteapache -r ${NEWONESUB}.${oneURI}
  /opt/verb/serfs/ensitenginx -r ${NEWONESUB}.${oneURI}
fi

# inkDNS Zone entry
/opt/verb/serfs/inkdnsaddonesub ${NEWONESUB} verber
wait

# inkCert, at end of the "domains =" line
/bin/sed -i "/^domains =/ s/$/, ${NEWONESUB}.${oneURI}/" /opt/verb/conf/inkcert/cli-ini/cli.${oneURI}.ini

# inkCert status
## inkCert-CBSINGLE DONE for parent domain
if /bin/grep -Fq "INKCERTED=DONE_CBSINGLE" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${oneURI}; then
/bin/echo "FYI: inkCert has already been setup for this subdomain's parent domain with Certbot single-cert. But, that certificate cannot be used with this subdomain.

In summary: ${NEWONESUB}.${oneURI} will not have SSL certs until you run:
  inkcertdocbsingle ${NEWONESUB}.${oneURI}
"

## inkCert-CBSINGLE DONE for this subdomain
if /bin/grep -Fq "INKCERTED=DONE_CBSINGLE" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${NEWONESUB}.${oneURI}; then
/bin/echo "FYI: inkCert has already been setup for this domain with Certbot single-cert, which should technically be impossible since that would normally require running this first.

Try to completely purge this domain with:
  killdomain ${NEWONESUB}.${oneURI}
Or try a gentler way that may not work:
  inkcertremovecbsingle ${NEWONESUB}.${oneURI}
   ...then...
  inkcertdocbsingle ${NEWONESUB}.${oneURI}
"

## Not setup
elif /bin/grep -Fq "INKCERTED=NO" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${oneURI}; then
  /bin/echo "FYI: inkCert has NOT YET been setup for this domain, which is probably what you want.
Once all set up, you are ready to run inkCert for ${oneURI}, if you haven't already or unless you want to add more subdomains first."

## inkCert-LE DONE
elif /bin/grep -Fq "INKCERTED=DONE_LE" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${oneURI}; then
  /bin/echo "FYI: inkCert has already been setup for this domain with Letsencrypt. So, your other certs will need inkCert-LE certs also.
The Letsencrypt certs will include this subdomain next time your Letsencrypt certs renew. But, that hasn't happened yet.
To refresh and thus get certs for this subdomain, run inkcertreqle for ${oneURI} with the \"r\" option, unless you want to add more subdomains first.
Note: Don't get Letsencrypt certs for the same core domain.tld too often or Letsencrypt will make you wait to get more.

In summary: ${NEWONESUB}.${oneURI} will not have SSL certs until you run:
  inkcertremovele ${oneURI}
   ...then...
  inkcertdole ${oneURI}
"

## inkCert-CB DONE
elif /bin/grep -Fq "INKCERTED=DONE_CB" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${oneURI}; then
  /bin/echo "FYI: inkCert has already been setup for this domain with a Certbot wildcard cert.
Adding that cert now...
"
/opt/verb/serfs/inkcertaddcb ${NEWONESUB}.${oneURI} ${oneURI}; wait

## inkCert-IC DONE
elif /bin/grep -Fq "INKCERTED=DONE_SC" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${oneURI}; then
  /bin/echo "FYI: inkCert has already been setup for this domain from inkCert self-cert. So, your other certs will need inkCert self certs also.
To refresh and thus get certs for this subdomain, run inkcertreq for ${oneURI} with the \"r\" option, unless you want to add more subdomains first.
Note: Don't get inkCert certs for the same core domain.tld too often or inkCert will make you wait to get more.

In summary: ${NEWONESUB}.${oneURI} will not have SSL certs under the domain until you run:
either...
 inkcertreqsc ${oneURI} r
or...
 inkcertreqsc ${NEWONESUB}.${oneURI}
"
fi




if [ -e "/opt/verb/mods/newonesub.after" ]; then . /opt/verb/mods/newonesub.after; fi # Follows this script
