#!/bin/sh
#inkVerbSerf! verb.ink

# This adds a new subdomain to become newsub.your-name.verb.one.

# How to use:
## ./newonesub [newsub only]


# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

NEWONESUB=$1

# Web directory
/bin/cp -R /opt/verb/conf/site-files/newonesubdir /srv/www/one/${NEWONESUB}
/bin/chown -R www:www /srv/www/one/${NEWONESUB}

# Server
. /opt/verb/conf/servertype
if [ ${SERVERTYPE} = "lemp" ]; then
  /bin/cp /opt/verb/conf/site-files/conf/newnginxonesub.conf /opt/verb/conf/webserver/nginx/sites-available/${NEWONESUB}.${oneURI}.conf 
  /bin/sed -i "s/newonesub/${NEWONESUB}/g" /opt/verb/conf/webserver/nginx/sites-available/${NEWONESUB}.${oneURI}.conf
  /bin/sed -i "s/oneURI286/${oneURI}/g" /opt/verb/conf/webserver/nginx/sites-available/${NEWONESUB}.${oneURI}.conf
  /opt/verb/serfs/ensitenginx -r ${NEWONESUB}.${oneURI}
elif [ ${SERVERTYPE} = "lamp" ]; then
  /bin/cp /opt/verb/conf/site-files/conf/newonesub.conf /opt/verb/conf/webserver/httpd/sites-available/${NEWONESUB}.${oneURI}.conf 
  /bin/sed -i "s/newonesub/${NEWONESUB}/g" /opt/verb/conf/webserver/httpd/sites-available/${NEWONESUB}.${oneURI}.conf
  /bin/sed -i "s/oneURI286/${oneURI}/g" /opt/verb/conf/webserver/httpd/sites-available/${NEWONESUB}.${oneURI}.conf
  /opt/verb/serfs/ensiteapache -r ${NEWONESUB}.${oneURI}
elif [ ${SERVERTYPE} = "laemp" ]; then
  /bin/cp /opt/verb/conf/site-files/conf/newonesub.conf /opt/verb/conf/webserver/httpd/sites-available/${NEWONESUB}.${oneURI}.conf 
  /bin/sed -i "s/newonesub/${NEWONESUB}/g" /opt/verb/conf/webserver/httpd/sites-available/${NEWONESUB}.${oneURI}.conf
  /bin/sed -i "s/oneURI286/${oneURI}/g" /opt/verb/conf/webserver/httpd/sites-available/${NEWONESUB}.${oneURI}.conf
  /bin/cp /opt/verb/conf/site-files/conf/newrpnginxonesub.conf /opt/verb/conf/webserver/nginx/sites-available/${NEWONESUB}.${oneURI}.conf 
  /bin/sed -i "s/newonesub/${NEWONESUB}/g" /opt/verb/conf/webserver/nginx/sites-available/${NEWONESUB}.${oneURI}.conf
  /bin/sed -i "s/oneURI286/${oneURI}/g" /opt/verb/conf/webserver/nginx/sites-available/${NEWONESUB}.${oneURI}.conf
  /opt/verb/serfs/ensiteapache -r ${NEWONESUB}.${oneURI}
  /opt/verb/serfs/ensitenginx -r ${NEWONESUB}.${oneURI}
fi

# inkCert, at end of the "domains =" line
/bin/sed -i "/^domains =/ s/$/, ${NEWONESUB}.${oneURI}/" /opt/verb/conf/inkcert/cli-ini/cli.${oneURI}.ini

