#!/bin/sh
#inkVerbSerf! verb.ink

# This creates a user who can read everything on the server and has a vip symlink in the home folder

# How to use:
## ./newservervip [new user] [new user password]


NEWFILEGURU=$1
NEWUSERPASS=$2

# Create the user with password
/usr/sbin/adduser ${NEWFILEGURU} --gecos ",,," --disabled-password
/bin/echo "${NEWFILEGURU}:${NEWUSERPASS}" | chpasswd

## This was created with the following base script
# sudo /usr/sbin/adduser myuser --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --disabled-password
# /bin/echo "myuser:password" | sudo chpasswd

# Create the www symlink
/bin/ln -s /srv/www/vip /home/${NEWFILEGURU}/vip

