#!/bin/sh
#inkVerbSerf! verb.ink

# This adds a new subdomain to become newsub.your-name.verb.vip, accessible in the _subs.vip folder.
# Dependencies: vsftpd and ftpvip or ftpfiler, run: installvsftpd, and newftpvip and/or newftpfiler

# How to use:
## ./newvipsub [newsub only]


# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

NEWVIPSUB=$1

# Web directory
/bin/cp -r /opt/verb/conf/site-files/newvipsubdir /srv/www/vip/_subs.vip/${NEWVIPSUB}
/bin/chown -R www:www /srv/www/vip/_subs.vip/${NEWVIPSUB}

# Server
. /opt/verb/conf/servertype
if [ ${SERVERTYPE} = "lemp" ]; then
  /bin/cp /opt/verb/conf/site-files/conf/newnginxvipsub.conf /opt/verb/conf/webserver/nginx/sites-available/${NEWVIPSUB}.${vipURI}.conf 
  /bin/sed -i "s/newvipsub/${NEWVIPSUB}/g" /opt/verb/conf/webserver/nginx/sites-available/${NEWVIPSUB}.${vipURI}.conf
  /bin/sed -i "s/vipURI286/${vipURI}/g" /opt/verb/conf/webserver/nginx/sites-available/${NEWVIPSUB}.${vipURI}.conf
  /opt/verb/serfs/ensitenginx -r ${NEWVIPSUB}.${vipURI}
elif [ ${SERVERTYPE} = "lamp" ]; then
  /bin/cp /opt/verb/conf/site-files/conf/newvipsub.conf /opt/verb/conf/webserver/httpd/sites-available/${NEWVIPSUB}.${vipURI}.conf 
  /bin/sed -i "s/newvipsub/${NEWVIPSUB}/g" /opt/verb/conf/webserver/httpd/sites-available/${NEWVIPSUB}.${vipURI}.conf
  /bin/sed -i "s/vipURI286/${vipURI}/g" /opt/verb/conf/webserver/httpd/sites-available/${NEWVIPSUB}.${vipURI}.conf
  /opt/verb/serfs/ensiteapache -r ${NEWVIPSUB}.${vipURI}
elif [ ${SERVERTYPE} = "laemp" ]; then
  /bin/cp /opt/verb/conf/site-files/conf/newvipsub.conf /opt/verb/conf/webserver/httpd/sites-available/${NEWVIPSUB}.${vipURI}.conf 
  /bin/sed -i "s/newvipsub/${NEWVIPSUB}/g" /opt/verb/conf/webserver/httpd/sites-available/${NEWVIPSUB}.${vipURI}.conf
  /bin/sed -i "s/vipURI286/${vipURI}/g" /opt/verb/conf/webserver/httpd/sites-available/${NEWVIPSUB}.${vipURI}.conf
  /bin/cp /opt/verb/conf/site-files/conf/newrpnginxvipsub.conf /opt/verb/conf/webserver/nginx/sites-available/${NEWVIPSUB}.${vipURI}.conf 
  /bin/sed -i "s/newvipsub/${NEWVIPSUB}/g" /opt/verb/conf/webserver/nginx/sites-available/${NEWVIPSUB}.${vipURI}.conf
  /bin/sed -i "s/vipURI286/${vipURI}/g" /opt/verb/conf/webserver/nginx/sites-available/${NEWVIPSUB}.${vipURI}.conf
  /opt/verb/serfs/ensiteapache -r ${NEWVIPSUB}.${vipURI}
  /opt/verb/serfs/ensitenginx -r ${NEWVIPSUB}.${vipURI}
fi

# inkCert, at end of the "domains =" line
/bin/sed -i "/^domains =/ s/$/, ${NEWVIPSUB}.${vipURI}/" /opt/verb/conf/inkcert/cli-ini/cli.${vipURI}.ini
