#!/bin/sh
#inkVerbSerf! verb.ink

# This should be run after roundcube has been setup through the web interface at rc.your-name.verb.email/rcpath

# How to use:
## ./postinstallrc


# Set installer to false
/bin/sed -i "s/\$config\['enable_installer'\].*/\$config\['enable_installer'\] = false;/g" /srv/www/email/roundcube/config/config.inc.php

/bin/echo "Finished. Roudcube installer disabled."
