#!/bin/sh
#inkVerbSerf! verb.ink

# This turns off and deletes the www/cgi folder and links it to cgi....verb.vip

# How to use:
## ./removecgi


# Include the configs
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servertype

if [ ${SERVERTYPE} = "lamp" ] || [ ${SERVERTYPE} = "laemp" ]; then
  # Prepare the directories
  /bin/rm -rf /srv/vip/cgi
  /bin/rm -rf /srv/www/html/vip.v/cgi

  # Turn it on in server settings
  /opt/verb/serfs/fixcgioff v.${vipURI}
  # Finish
  /bin/echo "
CGI disabled for:

http://v.${vipURI}/
"

elif [ ${SERVERTYPE} = "lemp" ]; then
  /bin/echo "CGI not allowed on LEMP servers anyway. Nothing to do."

fi

