#!/bin/bash
#inkVerbSerf! verb.ink

# This remote runs rinkadddomain for all verbs on both NS rink slave servers
## This will also run rinkkilldomain for all verbs first

# How to use:
## ./rinkupdateallverbs [ -k optional flag for only kill and don't update ]

usagenotes="This remote runs rinkkilldomain, then rinkadddomain for all verbs on both NS rink slave servers"
usageformat="rinkupdateallverbs [ -k optional flag for only kill and don't update ]"
usageexample="rinkupdateallverbs
rinkupdateallverbs -k"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=( k )
voptflagpurpose=( "Kill only, do not update" )
dependencyinstall=( "Controlled by Rink" )
prerequesite=(  )
usedby=( rink::addvps )
useserfs=(  )
useconfigs=( sitenameip sitenameip siteurilist sitetldstatus )

if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/rinkupdateallverbs.replace" ]; then . /opt/verb/mods/rinkupdateallverbs.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/rinkupdateallverbs.before" ]; then . /opt/verb/mods/rinkupdateallverbs.before; return 0; fi # Replaces this script


# Configs
. /opt/verb/conf/siteport
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/sitetldstatus

# Already configured?
if [ "$RINKCONFIGURED" != "true" ]; then
	/usr/bin/echo "Rink NS server keys not configured, this won't work"
	exit 0
fi

# Remove all, wait so we don't congest the server
/opt/verb/serfs/rinkkilldomain ${emailURI}; wait
/opt/verb/serfs/rinkkilldomain ${oneURI}; wait
/opt/verb/serfs/rinkkilldomain ${inkURI}; wait
/opt/verb/serfs/rinkkilldomain ${blueURI}; wait
/opt/verb/serfs/rinkkilldomain ${vipURI}; wait
/opt/verb/serfs/rinkkilldomain ${kiwiURI}; wait
/opt/verb/serfs/rinkkilldomain ${redURI}; wait

# Kill-only option?
if [ "${1}" = "-k" ]; then
	/usr/bin/echo "Kill-only option, NS records removed"
	exit 0
fi

# Add the active verb domains, wait so we don't congest the server
if [ $VERBemail=true ]; then
/opt/verb/serfs/rinkadddomain ${emailURI}
fi
wait
if [ $VERBone=true ]; then
/opt/verb/serfs/rinkadddomain ${oneURI}
fi
wait
if [ $VERBink=true ]; then
/opt/verb/serfs/rinkadddomain ${inkURI}
fi
wait
if [ $VERBblue=true ]; then
/opt/verb/serfs/rinkadddomain ${blueURI}
fi
wait
if [ $VERBvip=true ]; then
/opt/verb/serfs/rinkadddomain ${vipURI}
fi
wait
if [ $VERBkiwi=true ]; then
/opt/verb/serfs/rinkadddomain ${kiwiURI}
fi
wait
if [ $VERBred=true ]; then
/opt/verb/serfs/rinkadddomain ${redURI}
fi


if [ -e "/opt/verb/mods/rinkupdateallverbs.after" ]; then . /opt/verb/mods/rinkupdateallverbs.after; fi # Follows this script
