#!/bin/bash
#inkVerbSerf! verb.ink

# This remote runs inkdnsaddslave on both NS rink slave servers
## This is run automatically by newdomainshell and normally should not be run independently

# How to use:
## ./rinkadddomain [ domain.tld ]

usagenotes="This remote runs inkdnsaddslave on both NS rink slave servers"
usageformat="rinkadddomain [ domain.tld ]"
usageexample="rinkadddomain inkisaverb.com"
hierarchy=( tertiary newdomainshell )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( "Controlled by Rink" )
prerequesite=(  )
usedby=( newdomainshell )
useserfs=(  )
useconfigs=( siteport sitenameip )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/rinkadddomain.replace" ]; then . /opt/verb/mods/rinkadddomain.replace; return 0; fi # Precedes this script
if [ -e "/opt/verb/mods/rinkadddomain.before" ]; then . /opt/verb/mods/rinkadddomain.before; return 0; fi # Replaces this script


SLAVEDOMAIN=$1

# Configs
. /opt/verb/conf/siteport
. /opt/verb/conf/sitenameip

# Already configured?
if [ "$RINKCONFIGURED" != "true" ]; then
	echo "Rink NS server keys not configured, DNS nameserver zone files will need to be updated manually"
	exit 0
fi

# Run the command
/usr/bin/ssh -t ns1 /opt/verb/serfs/inkdnsaddslave ${SLAVEDOMAIN} ${SITEIPV4} ${SITEIPV6}
/usr/bin/ssh -t ns2 /opt/verb/serfs/inkdnsaddslave ${SLAVEDOMAIN} ${SITEIPV4} ${SITEIPV6}

if [ -e "/opt/verb/mods/rinkadddomain.after" ]; then . /opt/verb/mods/rinkadddomain.after; fi # Follows this script
