#!/bin/sh
#inkVerbSerf! verb.ink

# This sets up basic mail DNS and inkCert entries
## This is run automatically by setupverb and newdomainshell and normally should not be run independently

# How to use:
## ./setinkcertmail somedomain.tld


DOMAIN="$1"

# Include the config
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servertype

# inkCert
## Ensure that you don't get double entries
/bin/sed -i "s/, mail.${DOMAIN}//g" /opt/verb/conf/inkcert/cli-ini/cli.${DOMAIN}.ini
/bin/sed -i "s/, smtp.${DOMAIN}//g" /opt/verb/conf/inkcert/cli-ini/cli.${DOMAIN}.ini
/bin/sed -i "s/, imap.${DOMAIN}//g" /opt/verb/conf/inkcert/cli-ini/cli.${DOMAIN}.ini
/bin/sed -i "s/, pop3.${DOMAIN}//g" /opt/verb/conf/inkcert/cli-ini/cli.${DOMAIN}.ini
/bin/sed -i "s/, pop2.${DOMAIN}//g" /opt/verb/conf/inkcert/cli-ini/cli.${DOMAIN}.ini
/bin/sed -i "s/, pop.${DOMAIN}//g" /opt/verb/conf/inkcert/cli-ini/cli.${DOMAIN}.ini
## Add it to the cli-ini
/bin/sed -i "/^domains =/ s/$/, mail.${DOMAIN}, smtp.${DOMAIN}, imap.${DOMAIN}, pop3.${DOMAIN}, pop2.${DOMAIN}, pop.${DOMAIN}/" /opt/verb/conf/inkcert/cli-ini/cli.${DOMAIN}.ini

# Webserver directory (make it anyway)
/usr/bin/mkdir -p /srv/www/mailcatch
/usr/bin/cat <<'EOF' > /srv/www/mailcatch/index.htm
<!DOCTYPE html>
<html>
<head><title>Hey, Boo!</title></head>
<body><h1 style="text-align:center">Hey, Boo!</h1><hr></body>
</html>
EOF
/usr/bin/chown -R www:www /srv/www/mailcatch

# Webserver files so Letsencrypt checks work
if [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lemp" ]; then

  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxmailcatch.conf /opt/verb/conf/webserver/nginx/sites-available/mail.${DOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxmailcatch.conf /opt/verb/conf/webserver/nginx/sites-available/smtp.${DOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxmailcatch.conf /opt/verb/conf/webserver/nginx/sites-available/imap.${DOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxmailcatch.conf /opt/verb/conf/webserver/nginx/sites-available/pop3.${DOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxmailcatch.conf /opt/verb/conf/webserver/nginx/sites-available/pop2.${DOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxmailcatch.conf /opt/verb/conf/webserver/nginx/sites-available/pop.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/mail.${DOMAIN}/g" /opt/verb/conf/webserver/nginx/sites-available/mail.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/smtp.${DOMAIN}/g" /opt/verb/conf/webserver/nginx/sites-available/smtp.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/imap.${DOMAIN}/g" /opt/verb/conf/webserver/nginx/sites-available/imap.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/pop3.${DOMAIN}/g" /opt/verb/conf/webserver/nginx/sites-available/pop3.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/pop2.${DOMAIN}/g" /opt/verb/conf/webserver/nginx/sites-available/pop2.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/pop.${DOMAIN}/g" /opt/verb/conf/webserver/nginx/sites-available/pop.${DOMAIN}.conf
  /opt/verb/serfs/ensitenginx mail.${DOMAIN} smtp.${DOMAIN} imap.${DOMAIN} pop3.${DOMAIN} pop2.${DOMAIN} pop.${DOMAIN}

elif [ ${SERVERTYPE} = "lamp" ]; then

  /usr/bin/cp /opt/verb/conf/site-files/conf/newnapachemailcatch.conf /opt/verb/conf/webserver/httpd/sites-available/mail.${DOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnapachemailcatch.conf /opt/verb/conf/webserver/httpd/sites-available/smtp.${DOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnapachemailcatch.conf /opt/verb/conf/webserver/httpd/sites-available/imap.${DOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnapachemailcatch.conf /opt/verb/conf/webserver/httpd/sites-available/pop3.${DOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnapachemailcatch.conf /opt/verb/conf/webserver/httpd/sites-available/pop2.${DOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnapachemailcatch.conf /opt/verb/conf/webserver/httpd/sites-available/pop.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/mail.${DOMAIN}/g" /opt/verb/conf/webserver/httpd/sites-available/mail.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/smtp.${DOMAIN}/g" /opt/verb/conf/webserver/httpd/sites-available/smtp.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/imap.${DOMAIN}/g" /opt/verb/conf/webserver/httpd/sites-available/imap.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/pop3.${DOMAIN}/g" /opt/verb/conf/webserver/httpd/sites-available/pop3.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/pop2.${DOMAIN}/g" /opt/verb/conf/webserver/httpd/sites-available/pop2.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/pop.${DOMAIN}/g" /opt/verb/conf/webserver/httpd/sites-available/pop.${DOMAIN}.conf
  /opt/verb/serfs/ensiteapache mail.${DOMAIN} smtp.${DOMAIN} imap.${DOMAIN} pop3.${DOMAIN} pop2.${DOMAIN} pop.${DOMAIN}

fi
