#!/bin/sh
#inkVerbSerf! verb.ink

# This sets new site-wide SSL CA for inkNet
## Theoretically, this should not be necessary unless inkVerb makes changes to their own domain.

# How to use:
## ./setinknetsslca [inkNet SSL CA]

# Eg:
## ./setinknetsslca sslca.inkisaverb.com


INKSSLCA=$1

/bin/sed -i "s/INKNETSSLCA=.*/INKNETSSLCA=\"${INKSSLCA}\"/g" /opt/verb/conf/inknet/inknetinfo

