#!/bin/sh
#inkVerbSerf! verb.ink

# This sets up basic mail certificates and subdomain dummy sites for inkCert-LE
## This is run automatically by setupverb, installpostfixvmail, and newdomainshell, and normally should not be run independently

# How to use:
## ./setinkcertmail somedomain.tld
## ./setinkcertmail name.verb.ink verber (skip inkCert cli.ini, used by installpostfixvmail)

DOMAIN="$1"

# Include the config
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servertype

# inkCert
if [ "$2" != "verber" ]; then
  /opt/verb/serfs/setinkcertmailsubdomains ${nameURI}
fi

# Webserver directory (remake it everytime)
/usr/bin/mkdir -p /srv/www/mailcatch
/usr/bin/cat <<'EOF' > /srv/www/mailcatch/index.htm
<!DOCTYPE html>
<html>
<head><title>Hey, Boo!</title></head>
<body><h1 style="text-align:center">Hey, Boo!</h1><hr></body>
</html>
EOF
/usr/bin/chown -R www:www /srv/www/mailcatch

# Link the inkCert-LE certs if they exist, otherwise use Snakeoil
if [ -f "/etc/inkcert/le/live/${nameURI}/fullchain.pem" ]; then
  /usr/bin/ln -sfn /etc/inkcert/le/live/${DOMAIN}/fullchain.pem /etc/inkcert/mail/${DOMAIN}.crt
else
  /usr/bin/ln -sfn /etc/ssl/server/server.crt /etc/inkcert/mail/${DOMAIN}.crt
fi
if [ -f "/etc/inkcert/le/live/${nameURI}/privkey.pem" ]; then
  /usr/bin/ln -sfn /etc/inkcert/le/live/${DOMAIN}/privkey.pem /etc/inkcert/mail/${DOMAIN}.key
else
  /usr/bin/ln -sfn /etc/ssl/server/server.key /etc/inkcert/mail/${DOMAIN}.key
fi
## Permissions
/usr/bin/chmod 0444 /etc/inkcert/mail/${DOMAIN}.crt
/usr/bin/chmod 0400 /etc/inkcert/mail/${DOMAIN}.key

# Dovecot
/usr/bin/cat <<EOF > /etc/dovecot/crt.d/${DOMAIN}.conf
local_name imap.${DOMAIN} {
  ssl_cert = </etc/inkcert/mail/${DOMAIN}.crt
  ssl_key = </etc/inkcert/mail/${DOMAIN}.key
}
EOF
## Own
/bin/chown vmail:dovecot /etc/dovecot/crt.d/name.verb.ink.conf
/bin/chmod o-rwx /etc/dovecot/crt.d/name.verb.ink.conf

# Postfix
/usr/bin/cat <<EOF >> /etc/postfix/virtual_ssl.map
mail.${DOMAIN} /etc/inkcert/mail/${DOMAIN}.key /etc/inkcert/mail/${DOMAIN}.crt
EOF
/usr/bin/postmap -F hash:/etc/postfix/virtual_ssl.map

# Webserver files so inkCert-LE checks work
if [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lemp" ]; then

  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxmailcatch.conf /opt/verb/conf/webserver/nginx/sites-available/mail.${DOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxmailcatch.conf /opt/verb/conf/webserver/nginx/sites-available/smtp.${DOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxmailcatch.conf /opt/verb/conf/webserver/nginx/sites-available/imap.${DOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxmailcatch.conf /opt/verb/conf/webserver/nginx/sites-available/pop3.${DOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxmailcatch.conf /opt/verb/conf/webserver/nginx/sites-available/pop2.${DOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxmailcatch.conf /opt/verb/conf/webserver/nginx/sites-available/pop.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/mail.${DOMAIN}/g" /opt/verb/conf/webserver/nginx/sites-available/mail.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/smtp.${DOMAIN}/g" /opt/verb/conf/webserver/nginx/sites-available/smtp.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/imap.${DOMAIN}/g" /opt/verb/conf/webserver/nginx/sites-available/imap.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/pop3.${DOMAIN}/g" /opt/verb/conf/webserver/nginx/sites-available/pop3.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/pop2.${DOMAIN}/g" /opt/verb/conf/webserver/nginx/sites-available/pop2.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/pop.${DOMAIN}/g" /opt/verb/conf/webserver/nginx/sites-available/pop.${DOMAIN}.conf
  /opt/verb/serfs/ensitenginx mail.${DOMAIN} smtp.${DOMAIN} imap.${DOMAIN} pop3.${DOMAIN} pop2.${DOMAIN} pop.${DOMAIN}

elif [ ${SERVERTYPE} = "lamp" ]; then

  /usr/bin/cp /opt/verb/conf/site-files/conf/newnapachemailcatch.conf /opt/verb/conf/webserver/httpd/sites-available/mail.${DOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnapachemailcatch.conf /opt/verb/conf/webserver/httpd/sites-available/smtp.${DOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnapachemailcatch.conf /opt/verb/conf/webserver/httpd/sites-available/imap.${DOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnapachemailcatch.conf /opt/verb/conf/webserver/httpd/sites-available/pop3.${DOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnapachemailcatch.conf /opt/verb/conf/webserver/httpd/sites-available/pop2.${DOMAIN}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnapachemailcatch.conf /opt/verb/conf/webserver/httpd/sites-available/pop.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/mail.${DOMAIN}/g" /opt/verb/conf/webserver/httpd/sites-available/mail.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/smtp.${DOMAIN}/g" /opt/verb/conf/webserver/httpd/sites-available/smtp.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/imap.${DOMAIN}/g" /opt/verb/conf/webserver/httpd/sites-available/imap.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/pop3.${DOMAIN}/g" /opt/verb/conf/webserver/httpd/sites-available/pop3.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/pop2.${DOMAIN}/g" /opt/verb/conf/webserver/httpd/sites-available/pop2.${DOMAIN}.conf
  /bin/sed -i "s/mailcatchdomain/pop.${DOMAIN}/g" /opt/verb/conf/webserver/httpd/sites-available/pop.${DOMAIN}.conf
  /opt/verb/serfs/ensiteapache mail.${DOMAIN} smtp.${DOMAIN} imap.${DOMAIN} pop3.${DOMAIN} pop2.${DOMAIN} pop.${DOMAIN}

fi
