#!/bin/sh
#inkVerbSerf! verb.ink

# This sets new site-wide SSL CA
## Theoretically, this should not be necessary unless inkVerb makes changes to their own domain.

# How to use:
## ./setinkcertsslca [inkCert SSL CA]

# Eg:
## ./setinkcertsslca sslca.inkisaverb.com


INKSSLCA=$1

/bin/sed -i "s/INKCERTSSLCA=.*/INKCERTSSLCA=\"${INKSSLCA}\"/g" /opt/verb/conf/inkcert/inkcertstatus

