#!/bin/sh
#inkVerbSerf! verb.ink

# This sets up basic mail DNS and inkCert entries
## This is run automatically by setupverb and setinkcertmail (used in installpostfixvmail and newdomainshell) and normally should not be run independently

# How to use:
## ./setinkcertmailsubdomains somedomain.tld

DOMAIN="$1"

# Include the config
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servertype

# inkCert
## Ensure that you don't get double entries
/bin/sed -i "s/, mail.${DOMAIN}//g" /opt/verb/conf/inkcert/cli-ini/cli.${DOMAIN}.ini
/bin/sed -i "s/, smtp.${DOMAIN}//g" /opt/verb/conf/inkcert/cli-ini/cli.${DOMAIN}.ini
/bin/sed -i "s/, imap.${DOMAIN}//g" /opt/verb/conf/inkcert/cli-ini/cli.${DOMAIN}.ini
/bin/sed -i "s/, pop3.${DOMAIN}//g" /opt/verb/conf/inkcert/cli-ini/cli.${DOMAIN}.ini
## Add it to the cli-ini
/bin/sed -i "/^domains =/ s/$/, mail.${DOMAIN}, smtp.${DOMAIN}, imap.${DOMAIN}, pop3.${DOMAIN}/" /opt/verb/conf/inkcert/cli-ini/cli.${DOMAIN}.ini
