#!/bin/sh
#inkVerbSerf! verb.ink

# This sets new site-wide repo for Verber app installs, used primarily or solely by the inkget serf
## This should generally not be necessary unless new repos have been added and the current repo is distant or has high traffic.

# How to use:
## ./setinkgetrepo [inkget repo]

# Eg:
## ./setinkgetrepo toronto.verb.ink


NEWINKREPO=$1

/bin/sed -i "s/INKGET_REPO=.*/INKGET_REPO=\"${NEWINKREPO}\"/g" /opt/verb/conf/siteinkget

