#!/bin/bash
#inkVerbSerf! verb.ink

# This updates settings from setupverb to a new IPv4 address on the server

# How to use:
## ./setip4update [IPv4 number]


# Include the config file
. /opt/verb/conf/sitenameip

NEWIP4="$1"

# Normal IP
/bin/sed -i "s:SITEIP=.*:SITEIP=\"${NEWIP4}\":" /opt/verb/conf/sitenameip
/bin/sed -i "s:SITEIPV4=.*:SITEIPV4=\"${NEWIP4}\":" /opt/verb/conf/sitenameip
/bin/sed -i "s:${SITEIPV4}:${NEWIP4}:" /etc/hosts

# ARPA & inverse IP
## THANKS https://unix.stackexchange.com/a/132806/315069
NEWARPAIP4=$(/bin/echo ${NEWIP4} | sed -r 's/^([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$/\4.\3.\2.\1.in-addr.arpa/')
/bin/sed -i "s:SITEARPAIP4.*:SITEARPAIP4=\"${NEWARPAIP4}\":" /opt/verb/conf/sitenameip

# Update other files
if [ -f /etc/httpd/conf/rpaf.conf ]; then
  /bin/sed -i "s:${SITEIPV4}:${NEWIP4}:" /etc/httpd/conf/rpaf.conf; fi
/bin/sed -i "s:${SITEIPV4}:${NEWIP4}:" /opt/verb/conf/inkdns/inkzones/db.*
/bin/sed -i "s:${SITEIPV4}:${NEWIP4}:" /opt/verb/conf/inkdns/db.dnsdomain
/bin/sed -i "s:${SITEARPAIP4}:${NEWARPAIP4}:" /opt/verb/conf/inkdns/inkzones/nv.*
/bin/sed -i "s:${SITEARPAIP4}:${NEWARPAIP4}:" /opt/verb/conf/inkdns/nv.dnsdomain
## Any hosted zones
if [ -e /opt/verb/conf/inkdns/zones/db.* ]; then
  /bin/sed -i "s:${SITEIPV4}:${NEWIP4}:" /opt/verb/conf/inkdns/zones/db.*; fi
if [ -e /opt/verb/conf/inkdns/zones/nv.* ]; then
  /bin/sed -i "s:${SITEARPAIP4}:${NEWARPAIP4}:" /opt/verb/conf/inkdns/zones/nv.*; fi

# Finish
/opt/verb/serfs/inkdnsrefreshbind
/bin/echo "IPv4 now set to: ${NEWIP4}"




if [ -e "/opt/verb/mods/setip4update.after" ]; then . /opt/verb/mods/setip4update.after; fi # Follows this script
