#!/bin/sh
#inkVerbSerf! verb.ink

# This links the mail certs defined by setinkcertmail to the location used by the mail server
## This is run automatically by installpostfixvmail, setinkcertmail, and inkcertdo* and normally should not be run independently

# How to use:
## ./setinkcertmailcerts [ domain.tld ] [ dev switch 'vmail', optional and for dev only ]


# Dependencies
if ! /bin/grep -q 'INKCERTINSTALLED="DONE"' /opt/verb/conf/inkcert/inkcertstatus; then
  /usr/bin/echo "Install inkCert first, I quit."; exit 8
fi
if ! /bin/grep -q 'INKDNSSTAT="INSTALLED"' /opt/verb/conf/inkdns/inkdnsconf; then
  /usr/bin/echo "Install inkDNS first, I quit."; exit 8
fi
if ! /bin/grep -q 'SITEMAILSTATUS="VMAIL_SERVER"' /opt/verb/conf/sitemailpath; then
  /usr/bin/echo "Install Postfix Vmail first, I quit."; exit 8
fi

# Include the config
. /opt/verb/conf/siteurilist

DOMAIN="$1"

if [ -n "$2" ] && [ "$2" = "vmail" ]; then
  DEST="vmail"
else
  DEST="$1"
fi

# Link the inkCert-LE certs if they exist, otherwise use Snakeoil
if [ -f "/etc/inkcert/le/live/${DOMAIN}/fullchain.pem" ] && [ -f "/etc/inkcert/le/live/${DOMAIN}/privkey.pem" ]; then
  /usr/bin/ln -sfn /etc/inkcert/le/live/${DOMAIN}/fullchain.pem /etc/ssl/server/mail/${DEST}.crt
  /usr/bin/chmod 0444 /etc/ssl/server/mail/${DEST}.crt
  /usr/bin/sed -i "s?^#smtpd_tls_cert_file=/etc/ssl/server/mail/vmail.crt?smtpd_tls_cert_file=/etc/ssl/server/mail/vmail.crt?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^#smtp_tls_cert_file=/etc/ssl/server/mail/vmail.crt?smtp_tls_cert_file=/etc/ssl/server/mail/vmail.crt?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^#ssl_cert = </etc/ssl/server/mail/vmail.crt?ssl_cert = </etc/ssl/server/mail/vmail.crt?" /etc/dovecot/conf.d/10-ssl.conf
  /usr/bin/sed -i "s?^#ssl_dh = </etc/dovecot/dh.pem?ssl_dh = </etc/dovecot/dh.pem?" /etc/dovecot/conf.d/10-ssl.conf
  /usr/bin/sed -i "s?^smtpd_tls_cert_file=/etc/ssl/server/server.crt?#smtpd_tls_cert_file=/etc/ssl/server/server.crt?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^smtp_tls_cert_file=/etc/ssl/server/server.crt?#smtp_tls_cert_file=/etc/ssl/server/server.crt?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^ssl_cert = </etc/ssl/server/server.crt?#ssl_cert = </etc/ssl/server/server.crt?" /etc/dovecot/conf.d/10-ssl.conf
  /usr/bin/ln -sfn /etc/inkcert/le/live/${DOMAIN}/privkey.pem /etc/ssl/server/mail/${DEST}.key
  /usr/bin/chmod 0400 /etc/ssl/server/mail/${DEST}.key
  /usr/bin/sed -i "s?^#smtpd_tls_key_file=/etc/ssl/server/mail/vmail.key?smtpd_tls_key_file=/etc/ssl/server/mail/vmail.key?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^#smtp_tls_key_file=/etc/ssl/server/mail/vmail.key?smtp_tls_key_file=/etc/ssl/server/mail/vmail.key?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^#ssl_key = </etc/ssl/server/mail/vmail.key?ssl_key = </etc/ssl/server/mail/vmail.key?" /etc/dovecot/conf.d/10-ssl.conf
  /usr/bin/sed -i "s?^smtpd_tls_key_file=/etc/ssl/server/server.key?#smtpd_tls_key_file=/etc/ssl/server/server.key?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^ssl_key = </etc/ssl/server/server.key?#ssl_key = </etc/ssl/server/server.key?" /etc/dovecot/conf.d/10-ssl.conf
else
  /usr/bin/rm -f /etc/ssl/server/mail/${DEST}.crt
  /usr/bin/sed -i "s?^#smtpd_tls_cert_file=/etc/ssl/server/server.crt?smtpd_tls_cert_file=/etc/ssl/server/server.crt?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^#ssl_cert = </etc/ssl/server/server.crt?ssl_cert = </etc/ssl/server/server.crt?" /etc/dovecot/conf.d/10-ssl.conf
  /usr/bin/sed -i "s?^smtpd_tls_cert_file=/etc/ssl/server/mail/vmail.crt?#smtpd_tls_cert_file=/etc/ssl/server/mail/vmail.crt?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^smtp_tls_cert_file=/etc/ssl/server/mail/vmail.crt?#smtp_tls_cert_file=/etc/ssl/server/mail/vmail.crt?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^ssl_cert = </etc/ssl/server/mail/vmail.crt?#ssl_cert = </etc/ssl/server/mail/vmail.crt?" /etc/dovecot/conf.d/10-ssl.conf
  /usr/bin/sed -i "s?^ssl_dh = </etc/dovecot/dh.pem?#ssl_dh = </etc/dovecot/dh.pem?" /etc/dovecot/conf.d/10-ssl.conf
  /usr/bin/rm -f /etc/ssl/server/mail/${DEST}.key
  /usr/bin/sed -i "s?^#smtpd_tls_key_file=/etc/ssl/server/server.key?smtpd_tls_key_file=/etc/ssl/server/server.key?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^#ssl_key = </etc/ssl/server/server.key?ssl_key = </etc/ssl/server/server.key?" /etc/dovecot/conf.d/10-ssl.conf
  /usr/bin/sed -i "s?^smtpd_tls_key_file=/etc/ssl/server/mail/vmail.key?#smtpd_tls_key_file=/etc/ssl/server/mail/vmail.key?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^smtp_tls_key_file=/etc/ssl/server/mail/vmail.key?#smtp_tls_key_file=/etc/ssl/server/mail/vmail.key?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^ssl_key = </etc/ssl/server/mail/vmail.key?#ssl_key = </etc/ssl/server/mail/vmail.key?" /etc/dovecot/conf.d/10-ssl.conf
fi

# Restart Postfix
/usr/bin/systemctl restart postfix
/usr/bin/systemctl restart dovecot
