#!/bin/sh
#inkVerbSerf! verb.ink

# This sets new site-wide inkNet repo for Verber app installs, used primarily or solely by the inkget serf
## This should generally not be necessary unless new repos have been added and the current repo is distant or has high traffic.

# How to use:
## ./setinknetrepo [inkNet repo]

# Eg:
## ./setinknetrepo toronto.verb.ink


NEWINKCERTREPO=$1

/bin/sed -i "s/INKNET_REPO=.*/INKNET_REPO=\"${NEWINKCERTREPO}\"/g" /opt/verb/conf/inknet/inknetinfo

