#!/bin/sh
#inkVerbSerf! verb.ink

# This turns off bruteforce protection for nextcloud

# How to use:
## ./setnextcloudbfdoff


# First remove any existing declaration for this setting
/bin/sed -i "/  'auth\.bruteforce\.protection\.enabled.*/d" /srv/www/vapps/nextcloud/config/config.php

# Put the setting just before the close of the settings array
/bin/sed -i "s/);/  'auth\.bruteforce\.protection\.enabled' => false,\n);/" /srv/www/vapps/nextcloud/config/config.php
