#!/bin/sh
#inkVerbSerf! verb.ink

# This sets a new Postfix SQL database password appendage and installs it where it is needed

# How to use:
## ./setpostfixpassapg

# Include the configs
. /opt/verb/conf/sitemailpath
. /opt/verb/conf/sitemailpass

# Check prerequesites
if [ ${SITEMAILSTATUS} = "VMAIL_SERVER" ] || [ ${SITEMAILSTATUS} = "EMAIL_BACKUP_MX" ] || [ ${SITEMAILSTATUS} = "PMAIL_SERVER" ]; then
/bin/echo "
Email server is installed, proceeding...
"
else
/bin/echo "
Email server not installed, nothing to change.
"
exit 0; fi

# Set the variables
tbrSMPAPG="${SITEMAILPASSAPG}"
NEWMAILPASSAPG="$(/usr/bin/pwgen -s -1 5)"

# MySQL password
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
GRANT ALL PRIVILEGES ON mail.* TO 'mail'@'localhost' IDENTIFIED BY 'mailpass${NEWMAILPASSAPG}';
FLUSH PRIVILEGES;"

# Postfix & Dovecot password
/bin/sed -i "s/mailpass${tbrSMPAPG}/mailpass${NEWMAILPASSAPG}/" /etc/dovecot/dovecot-sql.conf.ext
/bin/sed -i "s/mailpass${tbrSMPAPG}/mailpass${NEWMAILPASSAPG}/" /etc/amavis/conf.d/50-user
/bin/sed -i "s/mailpass${tbrSMPAPG}/mailpass${NEWMAILPASSAPG}/" /etc/postfix/mysql_virtual_alias_domainaliases_maps.cf
/bin/sed -i "s/mailpass${tbrSMPAPG}/mailpass${NEWMAILPASSAPG}/" /etc/postfix/mysql_virtual_alias_maps.cf
/bin/sed -i "s/mailpass${tbrSMPAPG}/mailpass${NEWMAILPASSAPG}/" /etc/postfix/mysql_virtual_domains_maps.cf
/bin/sed -i "s/mailpass${tbrSMPAPG}/mailpass${NEWMAILPASSAPG}/" /etc/postfix/mysql_virtual_mailbox_domainaliases_maps.cf
/bin/sed -i "s/mailpass${tbrSMPAPG}/mailpass${NEWMAILPASSAPG}/" /etc/postfix/mysql_virtual_mailbox_maps.cf
/bin/sed -i "s/mailpass${tbrSMPAPG}/mailpass${NEWMAILPASSAPG}/" /etc/postfix/mysql_virtual_sender_login_maps.cf

# PFA
if [ ${SITEPFAPATH} != "PFA_NOT_ALLOWED" ] && [ ${SITEPFAPATH} != "PFA_NOT_INSTALLED" ]; then
/bin/sed -i "s/mailpass${tbrSMPAPG}/mailpass${NEWMAILPASSAPG}/" /srv/www/email/postfixadmin/config.local.php; fi

# The site-wide config
/bin/sed -i "s/SITEMAILPASSAPG.*/SITEMAILPASSAPG=\"${NEWMAILPASSAPG}\"/g" /opt/verb/conf/sitemailpass

# Finish
/bin/echo "Postfix and friends are now using a new database password."

