#!/bin/bash
#inkVerbSerf! verb.ink

# This changes the path of the PostfixAdmin web path
## This changes the path already set by installfpa

# How to use:
## ./setpfapath [folder]

# Eg:
## To use at pfa.NAME.verb.email/mysecretpath do: ./installpfa easy mysecretpath


# Include the config files
. /opt/verb/conf/sitenameip
. /opt/verb/conf/sitemailpath

PFAFOLDER=$1

/bin/rm -rf /srv/www/html/${SITEEMAILTLD}.pfa
/bin/cp -R /srv/www/html/0ne /srv/www/html/${SITEEMAILTLD}.pfa
/bin/ln -s /srv/www/email/postfixadmin /srv/www/html/${SITEEMAILTLD}.pfa/${PFAFOLDER}
/bin/chown -R www:www /srv/www/html/${SITEEMAILTLD}.pfa
/bin/sed -i "s/SITEPFAPATH=.*/SITEPFAPATH=\"${PFAFOLDER}\"/g" /opt/verb/conf/sitemailpass
/bin/sed -i "s/\$CONF\['postfix_admin_url'\] = 'https:\/\/.*/\$CONF\['postfix_admin_url'\] = 'https:\/\/pfa\.${SITENAME}\.verb\.${SITEEMAILTLD}\/${PFAFOLDER}';/g" /srv/www/email/postfixadmin/config.inc.php





if [ -e "/opt/verb/mods/setpfapath.after" ]; then . /opt/verb/mods/setpfapath.after; fi # Follows this script
