#!/bin/sh
#inkVerbSerf! verb.ink

# This sets the PostfixAdmin password hash for installation
## The hash is retrieved from the setup.php page

# How to use:
## ./setpfapass [hash]


PFAPASSHASH=$1

# Replace whatever current hash settings with the hash
/bin/sed -i "s/\$CONF\['configured'\] = .*/\$CONF\['configured'\] = true;/g" /srv/www/email/postfixadmin/config.local.php
/bin/sed -i "s/\$CONF\['setup_password'\] = .*/\$CONF\['setup_password'\] = '${PFAPASSHASH}';/g" /srv/www/email/postfixadmin/config.local.php
/bin/echo "Hash set. Return to PostfixAdmin setup to use the same password you entered."

