#!/bin/sh
#inkVerbSerf! verb.ink

# This sets the inkGet repo version list so that it will automatically update when the Verber is updated

# How to use:
## ./setrepoauto


/bin/sed -i "s/INKGET_LIST=.*/INKGET_LIST=\"AUTO_UPDATE\"/g" /opt/verb/conf/siteinkget





if [ -e "/opt/verb/mods/setrepoauto.after" ]; then . /opt/verb/mods/setrepoauto.after; fi # Follows this script
