#!/bin/sh
#inkVerbSerf! verb.ink

# This changes the path of the RoundCube web path
## This changes the path already set by installrc

# How to use:
## ./setrcpath [folder]

# Eg:
## (To use at pfa.NAME.verb.email/mysecretpath do:)
## ./installpfa easy mysecretpath


# Include the config file
. /opt/verb/conf/sitenameip
. /opt/verb/conf/sitemailpath

RCFOLDER=$1

/bin/rm -rf /srv/www/html/${SITEEMAILTLD}.rc
/bin/cp -R /srv/www/html/0ne /srv/www/html/${SITEEMAILTLD}.rc
/bin/ln -s /srv/www/email/roundcube /srv/www/html/${SITEEMAILTLD}.rc/${RCFOLDER}
/bin/chown -R www:www /srv/www/html/${SITEEMAILTLD}.rc
/bin/sed -i "s/SITERCPATH=.*/SITERCPATH=\"${RCFOLDER}\"/g" /opt/verb/conf/sitemailpass
/bin/sed -i "s/\$CONF\['footer_link'\] = 'https:\/\/.*/\$CONF\['footer_link'\] = 'https:\/\/rc\.${SITENAME}\.verb\.${SITEEMAILTLD}\/${RCFOLDER}';/g" /srv/www/email/postfixadmin/config.inc.php
