#!/bin/bash
#inkVerbSerf! verb.ink

# This turns off vapp MySQL vbak cron job

# How to use:
## ./setvappmysqlvbakoff

/bin/rm rf /etc/cron.d/vappmysql-vbak





if [ -e "/opt/verb/mods/setvappmysqlvbakoff.after" ]; then . /opt/verb/mods/setvappmysqlvbakoff.after; fi # Follows this script
