#!/bin/bash
#inkVerbSerf! verb.ink

# This sets the symlink for a vapp from the html/ folder to the vapps/ folder

# How to use:
## ./setvapplinkon [vapp name]


# Include the config file
. /opt/verb/conf/siteport
. /opt/verb/conf/siteurilist

VAPPNAME=$1

case ${VAPPNAME} in

fossil)
/bin/rm -rf /srv/www/verb/${itsqlTLD}/fossil
/bin/ln -sfn /srv/www/vip/${VAPPNAME} /srv/www/verb/${itsqlTLD}/fossil
/bin/echo "${VAPPNAME} symlink is set."
;;

net2ftp)
/bin/rm -rf /srv/www/verb/${itsqlTLD}/net2ftp
/bin/ln -s /srv/www/vapps/${VAPPNAME} /srv/www/verb/${itsqlTLD}/net2ftp
/bin/echo "${VAPPNAME} symlink is set."
;;

ampache)
/bin/rm -rf /srv/www/verb/kiwi.k/ampache
/bin/ln -s /srv/www/vapps/${VAPPNAME} /srv/www/verb/kiwi.k/ampache
/bin/echo "${VAPPNAME} symlink is set."
;;

mediawiki)
/bin/rm -rf /srv/www/verb/ink.i/wiki
/bin/ln -sfn /srv/www/vapps/${VAPPNAME} /srv/www/verb/ink.i/wiki
/bin/echo "${VAPPNAME} symlink is set."
;;

nextcloud)
/bin/rm -rf /srv/www/verb/blue
/bin/ln -sfn /srv/www/vapps/${VAPPNAME} /srv/www/verb/blue
/bin/echo "${VAPPNAME} symlink is set."
;;

orangehrm)
/bin/rm -rf /srv/www/verb/red.r/hrm
/bin/ln -s /srv/www/vapps/${VAPPNAME} /srv/www/verb/red.r/hrm
/bin/echo "${VAPPNAME} symlink is set."
;;

owa)
/bin/rm -rf /srv/www/verb/red.r/owa
/bin/ln -sfn /srv/www/vapps/${VAPPNAME} /srv/www/verb/red.r/owa
/bin/echo "${VAPPNAME} symlink is set."
;;

suitecrm)
/bin/rm -rf /srv/www/verb/red
/bin/ln -s /srv/www/vapps/${VAPPNAME} /srv/www/verb/red
/bin/echo "${VAPPNAME} symlink is set."
;;

october.inkblog)
/bin/rm -rf /srv/www/verb/ink.i/blog
/bin/ln -sfn /srv/www/vapps/${VAPPNAME} /srv/www/verb/ink.i/blog
/bin/echo "${VAPPNAME} symlink is set."
;;

wp.inkbb)
/bin/rm -rf /srv/www/verb/ink.i/bb
/bin/ln -sfn /srv/www/vapps/${VAPPNAME} /srv/www/verb/ink.i/bb
/bin/echo "${VAPPNAME} symlink is set."
;;

wp.inkblog)
/bin/rm -rf /srv/www/verb/ink.i/blog
/bin/ln -sfn /srv/www/vapps/${VAPPNAME} /srv/www/verb/ink.i/blog
/bin/echo "${VAPPNAME} symlink is set."
;;

esac





if [ -e "/opt/verb/mods/setvapplinkon.after" ]; then . /opt/verb/mods/setvapplinkon.after; fi # Follows this script
