#!/bin/bash
#inkVerbSerf! verb.ink

# This displays the setup password for PostfixAdmin
# How to use:
## ./showpfasetuppass


# Include the configs
. /opt/verb/conf/pfasetuppass

# Show the info
/usr/bin/echo "${PFASETUPTPASS}"
