#!/bin/bash
#inkVerbSerf! verb.ink

# This displays the settings and info for this Verber
## This is useful for many things, including Clients that need name and IP to connect to it

# How to use:
## ./showverber


# Include the config
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/sitemailpath
. /opt/verb/conf/inklists/verberverno

# Display info
/bin/echo "IP: ${SITEIP}
Namespace: ${SITENAME}
Primary TLD: ${SITETLD}
Primary URI: ${nameURI}
Host: ${SITETLD}
FQDN: ${hostURI}
Timezone: ${SITETIMECITY}, ${SITETIMEREGION}
Update channel: ${SITEUPDATEREPO}
Version: ${VERNO}
Type: ${VTYPE}

IT/SQL URL: ${itsqlTLD}
Email main domain URI: ${emailURI}
Email server URI: ${emailTLDURI}
Email Status: ${SITEMAILSTATUS}
PFA path: ${SITEPFAPATH}"





if [ -e "/opt/verb/mods/showverber.after" ]; then . /opt/verb/mods/showverber.after; fi # Follows this script
