#!/bin/bash
#inkVerbSerf! verb.ink

# This displays the Inker information that this Verber is connected to.
## This could be useful to retrieve names for setting up this Verber as a Client to the CA Inker

# How to use:
## ./showrink


# Check the config
if [ ! -f /opt/verb/conf/inknet/rink.client.cnf ]; then
/bin/echo "This is not yet connected to an Inker via inkNet."
exit 0
fi

# Include the config
. /opt/verb/conf/inknet/rink.client.cnf

# Display info
/bin/echo "Here you go. This Verber's Inker info...
IP: ${CAVERBERIP}
Name: ${CAVERBERNAME}
URI: ${CAVERBERURI}
"





if [ -e "/opt/verb/mods/showrink.after" ]; then . /opt/verb/mods/showrink.after; fi # Follows this script
