#!/bin/bash
#inkVerbSerf! verb.ink

# This displays the inkDKIM information in OpenDKIM for a specific domain so it can be added to an opendkim txt record in the DNS file
## inkDKIM is the inkVerb method of handling OpenDKIM keys

# How to use:
## ./showinkdkim [domain.tld]


DOMAIN=$1

/bin/echo $(/bin/cat /etc/opendkim/keys/${DOMAIN}/inkdkim.txt)





if [ -e "/opt/verb/mods/showinkdkim.after" ]; then . /opt/verb/mods/showinkdkim.after; fi # Follows this script
