#!/bin/sh
#inkVerbKnight! verb.ink

# This displays the current Verber version number

# How to use:
## ./showverbver

. /opt/verb/conf/inklists/verberverno
. /opt/verb/conf/sitenameip
/bin/echo "${SITEUPDATEREPO} ${VERNO}"





if [ -e "/opt/verb/mods/showverbver.after" ]; then . /opt/verb/mods/showverbver.after; fi # Follows this script
