#!/bin/bash
#inkVerbSerf! verb.ink

# This displays the full URL of the serve address set by setserve
# How to use:
## ./showserve


# Include the configs
. /opt/verb/conf/sitenameip

# Show the info
/bin/echo "https://${SERVEPATH}"




if [ -e "/opt/verb/mods/showserve.after" ]; then . /opt/verb/mods/showserve.after; fi # Follows this script
