#!/bin/sh
#inkVerbSerf! verb.ink

# This removes the Postfix Admin backup generated when updating Postfix Admin
# Prereq: Postfix Admin was updated via updaterc and is functioning properly

# How to use:
## ./updatepfarmvbak


/bin/rm -rf /srv/www/email/postfixadmin.vbak

/bin/echo "
Postfix Admin update backup removed.
"

