#!/bin/bash
#inkVerbSerf! verb.ink

# This updates an existing Roundcube installation once it has been updated in the inkVerb repo
## After, ensure that Roundcube works correctly, then run updatercrmvbak

# How to use:
## ./updaterc


# Include the config file
. /opt/verb/conf/sitenameip

# Download and unpack
cd /srv/www || exit 0
## Remove any existing roundcube folder
if [ -d roundcube ]; then
/bin/rm -rf roundcube; fi
## Get the update
if [ -d /srv/www/email/roundcube.vbak ]; then
/bin/rm -rf /srv/www/email/roundcube.vbak; fi
/bin/cp -R /srv/www/email/roundcube /srv/www/email/roundcube.vbak
/opt/verb/serfs/inkget roundcube; wait
/opt/verb/serfs.txzout roundcube; wait
/srv/www/roundcube/bin/installto.sh /srv/www/email/roundcube
wait
## Disable the installer
/bin/sed -i "s/\$config\['enable_installer'\].*/\$config\['enable_installer'\] = false;/g" /srv/www/email/roundcube/config/config.inc.php
## Remove the updater
cd /srv/www || exit 0
/bin/rm -rf /srv/www/roundcube

# Set up plugins that Composer broke
cd /srv/www/email/roundcube/plugins/ || exit 0
if [ ! -d "/srv/www/email/roundcube/plugins/authres_status" ]; then
/bin/cp /opt/verb/conf/lab/inkvmail/roundcube/authres_status.txz .
/opt/verb/serfs.txzout authres_status; wait; fi
if [ ! -d "/srv/www/email/roundcube/plugins/contextmenu" ]; then
/bin/cp /opt/verb/conf/lab/inkvmail/roundcube/contextmenu.txz .
/opt/verb/serfs.txzout contextmenu; wait; fi

# Copy the branding files
/bin/cp /opt/verb/conf/lab/inkvmail/roundcube/roundcubepics/verbink_logo.png /srv/www/email/roundcube/
/bin/cp /opt/verb/conf/lab/inkvmail/roundcube/roundcubepics/skins/elastic/images/logo.svg /srv/www/email/roundcube/skins/elastic/images/
/bin/cp /opt/verb/conf/lab/inkvmail/roundcube/roundcubepics/skins/elastic/images/favicon.ico /srv/www/email/roundcube/skins/elastic/images/
/bin/cp /opt/verb/conf/lab/inkvmail/roundcube/roundcubepics/favicon.ico /srv/www/email/roundcube/
/bin/cp /opt/verb/conf/lab/inkvmail/roundcube/roundcubepics/skins/larry/images/verbink_logo.png /srv/www/email/roundcube/skins/larry/images/
/bin/cp /opt/verb/conf/lab/inkvmail/roundcube/roundcubepics/skins/larry/images/watermark.jpg /srv/www/email/roundcube/skins/larry/images/
/bin/cp /opt/verb/conf/lab/inkvmail/roundcube/roundcubepics/skins/larry/images/favicon.ico /srv/www/email/roundcube/skins/larry/images/

# Notify status
/bin/echo "
RoudCube update complete.

If all works well, you may delete the backup wtih updatercrmvbak before updating again.

Now updating plugins with Composer. Hold your breath and think good thoughts...
"

# Composer Plugins update
cd /srv/www/email/roundcube || exit 0
php composer.phar update -n

# Finish
/bin/echo "
All done. :-)
"





if [ -e "/opt/verb/mods/updaterc.after" ]; then . /opt/verb/mods/updaterc.after; fi # Follows this script
