#!/bin/bash
#inkVerbSerf! verb.ink

# This downloads and updates the Verber™ core files, including serfs and inklists
## This also runs scripts that make other changes that may affect the Verber

# How to use:
## ./updateverber


# Include the config
. /opt/verb/conf/sitenameip

# Download the latest checked version from GitHub
cd /opt/verb/ || exit 0
git clone https://github.com/${SITEUPDATEORG}/${SITEUPDATEREPO}

# Run the update script
/bin/chmod 750 /opt/verb/${SITEUPDATEREPO}/update
/opt/verb/${SITEUPDATEREPO}/update
wait

# Remove the entire updater
/bin/rm -rf /opt/verb/${SITEUPDATEREPO}





if [ -e "/opt/verb/mods/updateverber.after" ]; then . /opt/verb/mods/updateverber.after; fi # Follows this script
