#!/bin/sh
#inkVerbSerf! verb.ink

# This copies all original verb folders to www/html if they don't exist
## This is used by killvapp and others
## This is used by make-verber
## This does not change ownership of folders to www-data, which must be done separately on a production server.

# How to use:
## ./updatehtmlverbs


# Include the config
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

# Make the commute to where we will work
/bin/mkdir -p /srv/www/verb
cd /srv/www/verb

# Remove broken links
/usr/bin/find -L . -name . -o -type d -prune -o -type l -exec rm {} +

# Initial sites
/bin/rm -rf 0sitedefaultInProgress
/bin/cp -r /opt/verb/conf/lab/www/0sitedefaultInProgress .
/bin/chmod -R 750 0sitedefaultInProgress
/bin/rm -rf vsslsitedefault
/bin/cp -r 0sitedefaultInProgress vsslsitedefault
/bin/rm -rf 0ne
/bin/mkdir 0ne
/bin/echo "<?php header(\"Location: http://${inkURI}\"); die(); ?>" > /srv/www/verb/0ne/index.php
/bin/chmod -R 750 0ne

# Block web folder listing
/bin/echo "Options -Indexes" >> /srv/www/verb/.htaccess
/bin/echo "Options -Indexes" >> /srv/www/verb/0ne/.htaccess
/bin/echo "Options -Indexes" >> /srv/www/verb/0sitedefaultInProgress/.htaccess

# Verb sites
if [ ! -e "ink" ]; then /bin/cp -r 0sitedefaultInProgress ink; fi
if [ ! -e "${itsqlTLD}.sql" ]; then /bin/cp -r 0ne ${itsqlTLD}.sql; fi
if [ ! -e "ink.i" ]; then /bin/cp -r 0ne ink.i; fi
if [ ! -e "email" ]; then /bin/cp -r 0ne email; fi
if [ ! -e "email.e" ]; then /bin/cp -r 0ne email.e; fi
if [ ! -e "one" ]; then /bin/cp -r 0ne one; fi
if [ ! -e "one.o" ]; then /bin/cp -r 0ne one.o; fi
if [ ! -e "blue" ]; then /bin/cp -r 0ne blue; fi
if [ ! -e "blue.b" ]; then /bin/cp -r 0ne blue.b; fi
if [ ! -e "vip" ]; then /bin/cp -r 0ne vip; fi
if [ ! -e "vip.v" ]; then /bin/cp -r 0ne vip.v; fi
if [ ! -e "vip.files" ]; then /bin/cp -r 0ne vip.files; fi
if [ ! -e "kiwi" ]; then /bin/cp -r 0ne kiwi; fi
if [ ! -e "kiwi.k" ]; then /bin/cp -r 0ne kiwi.k; fi
if [ ! -e "red" ]; then /bin/cp -r 0ne red; fi
if [ ! -e "red.r" ]; then /bin/cp -r 0ne red.r; fi

# Serve URI
/bin/rm -rf /srv/www/verb/${SITESERVE}.serve
/bin/mkdir -p /srv/www/verb/${SITESERVE}.serve/${SERVEDIR}
/bin/echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${nameURI}\"); die(); ?>" > /srv/www/verb/${SITESERVE}.serve/index.php

# Own
/bin/chown -R www:www /srv/www/verb
/bin/chmod -R 750 ${itsqlTLD}.sql
/bin/chmod -R 750 email
/bin/chmod -R 750 email.e
/bin/chmod -R 750 one
/bin/chmod -R 750 one.o
/bin/chmod -R 750 ink
/bin/chmod -R 750 ink.i
/bin/chmod -R 750 blue
/bin/chmod -R 750 blue.b
/bin/chmod -R 750 vip
/bin/chmod -R 750 vip.v
/bin/chmod -R 750 vip.files
/bin/chmod -R 750 kiwi
/bin/chmod -R 750 kiwi.k
/bin/chmod -R 750 red
/bin/chmod -R 750 red.r

# Finish
/bin/echo "Done. Except for any installed apps, any missing Verber html folders have been set to original setup state."




if [ -e "/opt/verb/mods/updatehtmlverbs.after" ]; then . /opt/verb/mods/updatehtmlverbs.after; fi # Follows this script
