#!/bin/sh
#inkVerbKnight! verb.ink

# This displays the current Verber version number

# How to use:
## ./inkver

. /opt/verb/conf/inklists/verberverno
. /opt/verb/conf/sitenameip
/bin/echo "${SITEUPDATEREPO} ${VERNO}"

