#!/bin/sh
#inkVerbSerf! verb.ink

# This turns on a tld of the verb sites, such as verb.red, but not the other verb.tld sites, all are on until turned off via verboff
## This is done through ensiteapache
## For *.verb.one or custom *.verb.vip, this only turns on NAME.verb.one and one.NAME.verb.one
## All other custom verb.one and custom verb.vip sites must be turned on again via newonesub

# How to use:
## ./verbon [tld]

# Eg:
## ./verbon kiwi


# Include the config file
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

SITEON=$1

/bin/sed -i "s/VERB${SITEON}=.*/VERB${SITEON}=true/g" /opt/verb/conf/sitetldstatus

if [ "${SITEON}" = "email" ]
then
    /opt/verb/serfs/ensiteapache ${emailURI} email.${emailURI} pfa.${emailURI} mail.${emailURI} rc.${emailURI}
    /usr/bin/apachectl graceful
    /bin/echo "Done."
exit 0
fi

if [ "${SITEON}" = "city" ]
then
    /opt/verb/serfs/ensiteapache ${cityURI} city.${cityURI} center.${cityURI}
    /usr/bin/apachectl graceful
    /bin/echo "Done."
exit 0
fi

if [ "${SITEON}" = "one" ]
then
    /opt/verb/serfs/ensiteapache ${oneURI} one.${oneURI}
    /usr/bin/apachectl graceful
    /bin/echo "Done."
exit 0
fi


if [ "${SITEON}" = "ink" ]
then
    /opt/verb/serfs/ensiteapache ${inkURI} ink.${inkURI} ask.${inkURI} bb.${inkURI} blog.${inkURI} code.${inkURI} home.${inkURI} shop.${inkURI} sn.${inkURI} wiki.${inkURI}
    /usr/bin/apachectl graceful
    /bin/echo "Done."
exit 0
fi


if [ "${SITEON}" = "blue" ]
then
    /opt/verb/serfs/ensiteapache ${blueURI} blue.${blueURI} nc.${blueURI} owncloud.${blueURI} seafile.${blueURI}
    /bin/echo "Done."
exit 0
fi


if [ "${SITEON}" = "vip" ]
then
    /opt/verb/serfs/ensiteapache ${vipURI} vip.${vipURI} cgi.${vipURI} ftp.${vipURI} files.${vipURI} fossil.${vipURI} mysql.${vipURI} net2ftp.${vipURI} repo.${vipURI}
    /usr/bin/apachectl graceful
    /bin/echo "Done."
exit 0
fi


if [ "${SITEON}" = "kiwi" ]
then
    /opt/verb/serfs/ensiteapache ${kiwiURI} kiwi.${kiwiURI} ampache.${kiwiURI} art.${kiwiURI} gallery.${kiwiURI} media.${kiwiURI} podcast.${kiwiURI} studio.${kiwiURI}
    /usr/bin/apachectl graceful
    /bin/echo "Done."
exit 0
fi


if [ "${SITEON}" = "pink" ]
then
    /opt/verb/serfs/ensiteapache ${pinkURI} pink.${pinkURI}
    /usr/bin/apachectl graceful
    /bin/echo "Done."
exit 0
fi


if [ "${SITEON}" = "red" ]
then
    /opt/verb/serfs/ensiteapache ${redURI} red.${redURI} act.${redURI} crm.${redURI} erp.${redURI} hrm.${redURI} odoo.${redURI} scm.${redURI}
    /usr/bin/apachectl graceful
    /bin/echo "Done."
exit 0
fi


if [ "${SITEON}" = "rocks" ]
then
    /opt/verb/serfs/ensiteapache ${rocksURI} rocks.${rocksURI}
    /usr/bin/apachectl graceful
    /bin/echo "Done."
exit 0
fi
