#!/bin/sh
#inkVerbSerf! verb.ink

# This creates or resets the system smtp user for vmail, such as is used by msmtp for php to send emails

# How to use:
## ./vmailsysmailbox


# Check to see if vmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed. Do that first."
  exit 0; fi

# Include the config
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

# Cleanup previous entries
if [ -f "/opt/verb/conf/vsysmail.msmtp" ]; then
  . /opt/verb/conf/vsysmail.msmtp
  /usr/bin/rm -rf /var/vmail/${vmaildirectory}
  oldusername="${username}"
fi

# Prep all vairables
PASSWORD=$(/usr/bin/pwgen -s1 24)
randomuser=$(/usr/bin/pwgen -s1A 5)
/usr/bin/cat <<EOF > /opt/verb/conf/vsysmail.msmtp
PASSWORD="${PASSWORD}"
user="sys_${randomuser}"
username="sys_${randomuser}@${nameURI}"
maildomain="${nameURI}"
name="System"
vmaildirectory="${nameURI}/sys_${randomuser}/"
mailboxsize="1048576" # 1MB, 2GB=2097152000, 1GB=1048576000, 5GB=5242880000
EOF

# Security check
/opt/verb/serfs/setsecure; wait

# Disable the old entry in the database
if [ -n "${oldusername}" ]; then
  password="$(/bin/echo $PASSWORD | /usr/bin/openssl passwd -1 -stdin)"
  /usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.vmail.cnf -e "UPDATE mailbox
  SET username = 'sys_${randomuser}@${nameURI}', password = '${password}', name = 'System', maildir = ${nameURI}/sys_${randomuser}, domain = '${nameURI}', modified = CURRENT_TIMESTAMP, active = 1
  WHERE username = '${oldusername}';
  UPDATE alias
  SET address = 'sys_${randomuser}@${nameURI}', goto = 'sys_${randomuser}@${nameURI}', domain = '${nameURI}', modified = CURRENT_TIMESTAMP, active = 1
  WHERE address = '${oldusername}';"
  echo "oldusername"
else
  echo "no old username"
fi

# Run it quick to create the account
/opt/verb/donjon/sysmails.sh msmtp; wait
if [ "$?" = 0 ]; then
  echo "Error updating new System mail user in databse"
  exit 6;
fi

# Set up cron
## MSMTP background jobs (manage the crontab files directly)
/bin/echo '22 * * * * root /opt/verb/donjon/sysmails.sh msmtp' > /etc/cron.d/sysmailmsmtp
## Permissions
/bin/chmod 0644 /etc/cron.d/sysmailmsmtp

# Create & set the config
/usr/bin/cat <<EOF >  /etc/msmtprc
defaults
auth           on
tls            on
tls_trust_file /etc/ssl/server/mail/vmail.crt
logfile        /var/log/msmtp.log
account sys
host mail.${nameURI}
port 587
from sys_${randomuser}@$nameURI
user sys_${randomuser}@$nameURI
password ${PASSWORD}
account default : sys
EOF
/bin/chmod 0600 /etc/msmtprc
/bin/chown www:www /etc/msmtprc

# Confirm the php.ini entry
if ! /bin/grep -q '^sendmail_path = "/usr/bin/msmtp -C /etc/msmtprc -t"' /opt/verb/conf/php.$SITENAME.ini; then
  /bin/sed -i "s/^sendmail_path = /;sendmail_path = /" /opt/verb/conf/php.$SITENAME.ini
  if /bin/grep -q ';sendmail_path = phpsendmail_path286' /opt/verb/conf/php.$SITENAME.ini; then
    /bin/sed -i "s/;sendmail_path = phpsendmail_path286/sendmail_path = \"\/usr\/bin\/msmtp -C \/etc\/msmtprc -t\"/" /opt/verb/conf/php.$SITENAME.ini
  else
    /bin/echo "sendmail_path = \"/usr/bin/msmtp -C /etc/msmtprc -t\"" >> /opt/verb/conf/php.$SITENAME.ini
  fi
  /usr/bin/systemctl restart httpd
fi
