#!/bin/sh
#inkVerbSerf! verb.ink

# This delets an email domain

# How to use:
## ./vmaildeldomain [domain]

# Check to see if vmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed, not adding $domain to PFA"
  exit 0; fi

domain="$1"

# Run the update
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.vmail.cnf -e "DELETE FROM domain WHERE domain='$domain';"

# Finish
/bin/echo "Email domain $domain deleted...
The original mail should still be on the server, which you can access if you create the same domain again,
To remove any mail still on the server, use vmailpurgedomain"
