#!/bin/sh
#inkVerbSerf! verb.ink

# This shows the vmail domains

# How to use:
## ./vmailshowdomains

# Check to see if vmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed, not adding $domain to PFA"
  exit 0; fi

# Run the query
query=$(/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.vmail.cnf -e "SELECT domain FROM domain;")
domainlist="$(/bin/echo ${query} | sed "s/domain ALL //")"

# Show the results
for dom in $domainlist; do
  echo $dom
done
