#!/bin/sh
#inkVerbSerf! verb.ink

# This purges (deletes) the vmail directory of an email box from the server

# How to use:
## ./vmailpurgebox [emailUser (no domain)] [domain]


# Check to see if vmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed. Do that first."
  exit 0; fi

# Variables
emailUser="$1"
domain="$2"
vmaildirectory="$domain/$emailUser/"
address="$domain@$emailUser"

# Delete
/bin/rm -rf /var/vmail/$vmaildirectory

# Finish
/bin/echo "Email box $address purged from server"
