#!/bin/sh
#inkVerbSerf! verb.ink

# This shows the vmail domains

# How to use:
## ./vmailshowboxes

# Check to see if vmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed, not adding $domain to PFA"
  exit 0; fi

domain="$1"

# All domains
if [ -z "$1" ]; then
  query=$(/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.vmail.cnf -e "SELECT username FROM mailbox;")
# Specified domain
else
  domain="$1"
  query=$(/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.vmail.cnf -e "SELECT username FROM mailbox WHERE domain='$domain';")
fi

# Show the results
boxlist="$(/bin/echo ${query} | sed "s/username //")"
for box in $boxlist; do
  echo $box
done
