#!/bin/sh
#inkVerbSerf! verb.ink

# This sets an alias to "active"

# How to use:
## ./vmailonalias [emal address]

# Check to see if vmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed, not adding $domain to PFA"
  exit 0; fi

address="$1"

# Run the update
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.vmail.cnf -e "UPDATE alias SET active=1, modified=CURRENT_TIMESTAMP WHERE address='$address';"

# Finish
/bin/echo "Email alias $address set to active"
