#!/bin/sh
#inkVerbSerf! verb.ink

# This sets a domain to "inactive"

# How to use:
## ./vmailoffdomain [domain]

# Check to see if vmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed, not adding $domain to PFA"
  exit 0; fi

domain="$1"

# Run the update
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.vmail.cnf -e "UPDATE domain SET active=0, modified=CURRENT_TIMESTAMP WHERE domain='$domain';"

# Finish
/bin/echo "Domain $domain set to inactive"
