#!/bin/sh
#inkVerbSerf! verb.ink

# This sets an email box to "active"

# How to use:
## ./vmailonbox [emal address]

# Check to see if vmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed, not adding $domain to PFA"
  exit 0; fi

address="$1"

# Run the update
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.vmail.cnf -e "UPDATE mailbox SET active=1, modified=CURRENT_TIMESTAMP WHERE username='$address';"

# Finish
/bin/echo "Email address $address set to active"
