#!/bin/sh
#inkVerbSerf! verb.ink

# This creates a new admin for PFA
## Currently, this will not work until PFA has already been installed, but commented SQL code is in place to add the needed tables in installpostfixvmail, but that code may need to be updated

# How to use:
## ./vmailpfanewadmin [username (an email address)] [name - optional]

# Eg:
## ./vmailpfanewadmin james@inkisaverb.com "James Inksmith"


USERNAME="$1"
if [ -z "$2" ]; then
NAME="$1"
else
NAME="$2"
fi

# Check to see if vmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed. Do that first."
  exit 0; fi

# Prep the variables

# Defaults # can be changed for domain-specific admins
issuperadmin="1"
adminsdomains="ALL"

# Hash the password
PASSWORD=$(/usr/bin/pwgen -s -1 15)
password="$(/bin/echo $PASSWORD | /usr/bin/openssl passwd -1 -stdin)"

# Make the database entry
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.vmail.cnf -e "INSERT INTO admin (username, password, superadmin, created, modified, active) VALUES ('$USERNAME', '$password', '$issuperadmin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO domain_admins (username, domain, created, active) VALUES ('$USERNAME', '$adminsdomains', CURRENT_TIMESTAMP, 1);"

# Finish
/bin/echo "Created:
User login: $USERNAME
Password: $PASSWORD"
