#!/bin/sh
#inkVerbSerf! verb.ink

# This delets an email box

# How to use:
## ./vmaildelbox [emal address]

# Check to see if vmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed, not adding $domain to PFA"
  exit 0; fi

address="$1"

# Run the update
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.vmail.cnf -e "DELETE FROM mailbox WHERE username='$address';"

# Finish
/bin/echo "Email address $address deleted...
The original mail should still be on the server, which you can access if you create the same email address again,
To remove any mail still on the server, use vmailpurgebox"
