#!/bin/sh
#inkVerbSerf! verb.ink

# This creates or resets the system smtp user for vmail, such as is used by php to send emails

# How to use:
## ./vmailsysmailbox


# Check to see if vmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed. Do that first."
  exit 0; fi

# Include the config
. /opt/verb/conf/sitenameip
. /opt/verb/conf/siteurilist

# Prep all vairables
PASSWORD=$(/usr/bin/pwgen -s1 24)
password="$(/bin/echo $PASSWORD | /usr/bin/openssl passwd -1 -stdin)"
username="sys@$nameURI"
NAME="System"
vmaildirectory="$nameURI/sys/"
mailboxsize="1048576" # 1MB, 2GB=2097152000, 1GB=1048576000, 5GB=5242880000

# Make the database entry
## We need the alias entry for the mailbox to be active
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.vmail.cnf -e "DELETE FROM mailbox WHERE username = '$username';
INSERT INTO mailbox (username, password, name, maildir, quota, local_part, domain, created, modified, active) VALUES ('$username', '$password', '$NAME', '$vmaildirectory', '$mailboxsize', 'sys', '$nameURI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO alias (address, goto, domain, created, modified, active) VALUES ('$username', '$username', '$nameURI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);"

# Create & set the php config
/bin/echo "
defaults
auth           on
tls            on
tls_trust_file /etc/inkcert/mail/vmail.crt
logfile        /var/log/msmtp.log
account sys
host mail.$nameURI
port 587
from sys@$nameURI
user sys@$nameURI
password $PASSWORD
account default : sys" > /etc/msmtprc
/bin/chmod 0600 /etc/msmtprc
/bin/chown www:www /etc/msmtprc

# Confirm the php.ini entry
if ! /bin/grep -q '^sendmail_path = "/usr/bin/msmtp -C /etc/msmtprc -t"' /opt/verb/conf/php.$SITENAME.ini; then
  /bin/sed -i "s/^sendmail_path = /;sendmail_path = /" /opt/verb/conf/php.$SITENAME.ini
  if /bin/grep -q ';sendmail_path = phpsendmail_path286' /opt/verb/conf/php.$SITENAME.ini; then
    /bin/sed -i "s/;sendmail_path = phpsendmail_path286/sendmail_path = \"\/usr\/bin\/msmtp -C \/etc\/msmtprc -t\"/" /opt/verb/conf/php.$SITENAME.ini
  else
    /bin/echo "sendmail_path = \"/usr/bin/msmtp -C /etc/msmtprc -t\"" >> /opt/verb/conf/php.$SITENAME.ini
  fi
  systemctl restart httpd
fi
