#!/bin/sh
#inkVerbSerf! verb.ink

# This delets an email alias

# How to use:
## ./vmaildelalias [emal address]

# Check to see if vmail is installed
. /opt/verb/conf/sitemailpath
if [ "$SITEMAILSTATUS" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed, not adding $domain to PFA"
  exit 0; fi

address="$1"

# Run the update
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqldb.vmail.cnf -e "DELETE FROM alias WHERE address='$address';"

# Finish
/bin/echo "Email alias $address gone"
