#!/bin/bash
#inkVerbSerf! verb.ink

# This compresses a directory into a .tar.xz file, renamed as a .txz file, all in the PWD
## The resulting .txz file can simply be renamed to .tar.xz and be used accordingly
## This alternate extention name is intended to prevent tampering and to maintain consistency within inkVerb deployment

# The directory MUST be in the PWD!
# This will OVERWRITE any .txz destination file by the same name!

# How to use:
## ./vtxzin [directory]

# Eg:
## ./vtxzin mystuff


DIR=$1

/usr/bin/echo "Creating .txz archive file..."
/bin/tar c ${DIR} | /usr/bin/xz > ${DIR}.tar.xz
/bin/mv ${DIR}.tar.xz ${DIR}.txz
/usr/bin/echo "Done."




if [ -e "/opt/verb/mods/vtxzin.after" ]; then . /opt/verb/mods/vtxzin.after; fi # Follows this script
