#!/bin/sh
#inkVerbSerf! verb.ink

# This decompresses a .tvxz file and places its contents in same directory, all in the PWD
## The .vtxz file could simply be renamed to .tar.xz and be used accordingly
## This alternate extention name is intended to prevent tampering and to maintain consistency within inkVerb deployment

# The .vtxz file MUST be in the PWD!
# Do NOT include the .vtxz extension in the filename parameter!

# How to use:
## ./vtxzout [vtxzfile]

# Eg:
## ./vtxzout mystuff


FIL=$1

# Test for a .tar of the same name
if [ -e "${FIL}.tar" ]; then
/bin/echo "The file ${FIL}.tar exists, which conflicts with this operation. Deal with that out first."
exit 7; fi

/bin/mv ${FIL}.vtxz ${FIL}.tar.xz
/usr/bin/xz -d ${FIL}.tar.xz
/bin/tar -xf ${FIL}.tar
/bin/rm ${FIL}.tar
