#!/bin/sh
#inkVerbSerf! verb.ink

# This changes the Tesseract theme's "Follow Us On" social icon Title prefix to what you set. It can be left null for simple social media titles
## This only applies to the home.your-name.ink WordPress installation

# How to use:
## ./wpfixtessfollowhome [replaced contend]


/bin/sed -i "s/Follow Us on/${CONTENT}/g" /srv/www/html/ink.home/wp-content/themes/tesseract-free-theme/inc/customizer-frontend-functions.php
/bin/sed -i "s/Follow Us on/${CONTENT}/g" /srv/www/html/ink.home/wp-content/themes/tesseract-free-theme/languages/tesseract.pot
