#!/bin/bash
#inkVerbSerf! verb.ink

# This turns off a WordPress vapp from being able to use multisite
## Specifically, this adds the multisite settings in wp-config.php necessary to begin the installation from the WordPress dashboard

# How to use:
## ./wpmusetoff [domain.tld]

# Eg:
## ./wpmusetoff inkisaverb.com
## ./wpmusetoff mysubsite.inkisaverb.com


WPDOMAIN=$1

# Check if already set
if /bin/grep -Fq "define( 'WP_ALLOW_MULTISITE', true );" /srv/www/html/${WPDOMAIN}/wp-config.php; then
/bin/echo "Proceeding..."; else
/bin/echo "Multisite isn't even set, dufis. Set it on with: wpmuseton"
exit 8; fi

# Delete the lines
/bin/sed -i "/* Multisite via inkVerb */d" /srv/www/html/${WPDOMAIN}/wp-config.php
/bin/sed -i "/define( 'WP_ALLOW_MULTISITE', true );/d" /srv/www/html/${WPDOMAIN}/wp-config.php

# Finish
/bin/echo "WP Multisite for http://${WPDOMAIN} is now disabled."





if [ -e "/opt/verb/mods/wpmusetoff.after" ]; then . /opt/verb/mods/wpmusetoff.after; fi # Follows this script
