#!/bin/sh
#inkVerbSerf! verb.ink

# This unlinks a domain to it's wp location in vapps
## It is useful to return a domain to its www/domains space when turning off or no longer using a wordpress installation
## This does NOT turn off or uninstall wordpress from the domain

# How to use:
## ./wpunlinkdomain [full domain of WP site]


DOMAIN=$1

/bin/rm -f /srv/www/html/${DOMAIN}
/bin/ln -s /srv/www/domains/${DOMAIN} /srv/www/html/${DOMAIN}
/bin/chown -R www:www /srv/www/html/${DOMAIN}

