#!/bin/sh
#inkVerbSerf! verb.ink

# This backs up all wordpress vapps into the vip folder

# How to use:
## ./wpvappbackupall


cd /srv/www/vapps
for vapp in wp.*; do
/opt/verb/serfs/backup $vapp 123 -nl
done





if [ -e "/opt/verb/mods/wpvappbackupall.after" ]; then . /opt/verb/mods/wpvappbackupall.after; fi # Follows this script
